% build a latex file using raw data

plotdir = [conf.plotdir,EXP,'/'];

list_plot=dir(sprintf('%s*%s_diags_TS_%s.png',plotdir,suffix,mode));
if length(list_plot)==0
    
    disp(['no plots ' sprintf('%s*%s_diags_TS_%s.png',plotdir,suffix,mode) ]);
    
elseif ~isfield(conf,'pdflatex'),
    
    disp('no latex compiler')
    
else
    
    namefile=strrep(EXP,'-','_');
    nfic=sprintf('%s%s%s_doc_%s.tex',conf.temporary,namefile,suffix,mode);
    fid=fopen(nfic,'w');
    fprintf(fid,...
        ['\\documentclass[twocolumn]{article}\n' ...
        '\\usepackage{graphicx}\n' ...
        '\\usepackage[landscape,top=1cm, bottom=1.5cm, left=1cm, right=1cm]{geometry}\n\n' ...
        '\\begin{document}\n\n']);
    
    a=dir(sprintf('%s/*%s_diags_TS_%s.png',plotdir,suffix,mode));
    lfic2={a.name};
    for ii=1:length(lfic2),
        I=strfind(lfic2{ii},sprintf('%s_diags_TS_%s.png',suffix,mode));
        lfic2{ii}=lfic2{ii}(1:I(1)-1);
    end
    
    plotdir = strrep(plotdir,'\','/');
    
    fprintf(fid,...
        ['\\begin{figure}[htb!]\n', ...
        '\\begin{centering}\n', ...
        '\\includegraphics[width=14cm,angle=0]{' plotdir EXP suffix '_recapARGO_' mode '.png}\n', ...
        '\\par\\end{centering}\n', ...
        '\\end{figure}\n', ...
        '\\begin{figure}[htb!]\n', ...
        '\\begin{centering}\n', ...
        '\\includegraphics[width=14cm,angle=0]{' plotdir EXP suffix '_histoARGO_' mode '.png}\n', ...
        '\\par\\end{centering}\n', ...
        '\\end{figure}\n\n', ...
        '\\clearpage\n\n' ]);
    
    for ii=1:2:length(lfic2),
        
        str2=lfic2{ii};
        fprintf(fid,...
            ['\\begin{figure}[htb!]\n', ...
            '\\begin{centering}\n', ...
            '\\includegraphics[height=10cm,angle=0]{' plotdir str2 suffix '_diags_TS_' mode '.png}\n', ...
            '\\includegraphics[height=10cm,angle=0]{' plotdir str2 suffix '_transect_' mode '.png}\n', ...
            '\\par\\end{centering}\n', ...
            '\\end{figure}\n' ]);
        
        if ii~=length(lfic2),
            str2=lfic2{ii+1};
            fprintf(fid,...
                ['\\begin{figure}[htb!]\n', ...
                '\\begin{centering}\n', ...
                '\\includegraphics[height=10cm,angle=0]{' plotdir str2 suffix '_diags_TS_' mode '.png}\n', ...
                '\\includegraphics[height=10cm,angle=0]{' plotdir str2 suffix '_transect_' mode '.png}\n', ...
                '\\par\\end{centering}\n', ...
                '\\end{figure}\n', ...
                '\\clearpage\n\n' ]);
        else
            fprintf(fid,'\\clearpage\n\n');
        end
        
    end
    
    fprintf(fid,'\\end{document}\n\n');
    fclose(fid);
    
    [T,cmdout]=system(sprintf('%s -interaction nonstopmode "%s"',conf.pdflatex,nfic));
    delete('*_doc_*.aux');
    delete('*_doc_*.log');
    
    movefile(sprintf('%s%s_doc_%s.pdf',namefile,suffix,mode),conf.texdir);
    
end