Description of ab2kl
Home > jlab > ab2kl.m
ab2kl
AB2KL  Converts A and B to ellipse parameters Kappa and Lambda.
   [K,L]=AB2KL(A,B)  Convert ellipse semi-major and semi-minor
   axes A and B to ellipse amplitude K and ellipse parameter L.
   K and L are related to A and B by
          K   = SQRT( (A^2 +B^2) / 2 )
          L   = SIGN(B) * (A^2 - B^2 ) / (A^2 + B^2)
   as discussed in Lilly and Gascard (2006).
   A and B are either arrays of the same size, or one may be an array
   and one may be a scalar.
   Usage: [kappa,lambda]=ab2kl(a,b)
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2009 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
ab2kl AB2KL Converts A and B to ellipse parameters Kappa and Lambda.
aresame ARESAME Test whether two N-D arrays are the same.
ecconv ECCONV Converts between eccentricity measures.
frac FRAC Fraction: FRAC(A,B)=A./B
kl2ab KL2AB Converts ellipse parameters Kappa and Lambda to A and B.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
ab2kl AB2KL Converts A and B to ellipse parameters Kappa and Lambda.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
elldiff ELLDIFF Differentiation of modulated elliptical signals.
ellipseplot ELLIPSEPLOT Plot ellipses.
jellipse jEllipse: Analysis of modulated elliptical, or bivariate, signals
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
kl2ab KL2AB Converts ellipse parameters Kappa and Lambda to A and B.