Description of allall
Home > jlab > allall.m
allall
ALLALL(X)=ALL(X(:))
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
anatrans ANATRANS Analytic part of signal.
aresame ARESAME Test whether two N-D arrays are the same.
bellpoly BELLPOLY Complete Bell polynomials.
cellchunk CELLCHUNK Converts cell array data into uniform length 'chunks'.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
doublen DOUBLEN Interpolates a time series to double its length.
ecconv ECCONV Converts between eccentricity measures.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellipseplot ELLIPSEPLOT Plot ellipses.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
inellipse INELLIPSE Locates points on the interior of ellipses.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
maternchol MATERNCHOL Cholesky decomposition of the Matern covariance matrix.
maternedge MATERNEDGE Long-time cutoff edge for the Matern impulse response function.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
mom2cum MOM2CUM Convert moments to cumulants.
morsea MORSEA Returns the generalized Morse wavelet amplitude "a".
mspec MSPEC Multitaper power and cross spectra.
periodize PERIODIZE Returns a doubly periodic version of an input array.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
provec PROVEC Generate progressive vector diagrams (simple and fancy).
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
readtopo READTOPO Read one-minute topography data from Smith and Sandwell.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
sleptap SLEPTAP Calculate Slepian tapers.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
timeseries_boundary TIMESERIES_BOUNDARY Apply boundary conditions to data before transform.
trajchunk TRAJCHUNK Converts Lagrangian trajectories into chunks based on the Coriolis period.
uv2latlon UV2LATLON Integrates horizontal velocity to give latitude and longitude.
vmean VMEAN Mean over finite elements along a specified dimension.
vmedian VMEDIAN Median over finite elements along a specified dimension.
vsize VSIZE Returns the sizes of multiple arguments.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
wavetrans WAVETRANS Continuous wavelet transform.