Description of anyany
Home > jlab > anyany.m
anyany
ANYANY(X)=ANY(X(:))
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
about_floats FLOATS Historical dataset of eddy-resolving subsurface floats.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
orbitbreaks ORBITBREAKS Separate orbit into passes based on turning points.
periodindex PERIODINDEX Returns time index in increments of instantaneous period.
periodize PERIODIZE Returns a doubly periodic version of an input array.
sleptap SLEPTAP Calculate Slepian tapers.
spheredist SPHEREDIST Computes great circle distances on a sphere.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
wavetrans WAVETRANS Continuous wavelet transform.