Description of arrayify
Home > jlab > arrayify.m
arrayify
ARRAYIFY  Converts a set of scalars or arrays into column arrays.
   [O1,O2,O3,...,ON]=ARRAYIFY(I1,I2,I3,...,IN) where each of the IN is
   either a scalar or an array with M elements, converts each input
   variable into a length M column vector.
   The input variables that are M-element arrays are resized to column
   vectors, while scalars are replicated to have M identical elements.
   ARRAYIFY will return an error if any of the input variables that are
   not scalars have different numbers of elements from each other.
   ARRAYIFY(I1,I2,...IN); with no output arguments overwrites the original
   input variables.
   'arrayify --t' runs a test.
   Usage: [o1,o2,o3]=arrayify(i1,i2,i3);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
arrayify ARRAYIFY Converts a set of scalars or arrays into column arrays.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
This function is called by:
arrayify ARRAYIFY Converts a set of scalars or arrays into column arrays.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
materncov MATERNCOV Autocovariance function of the Matern random process.
maternedge MATERNEDGE Long-time cutoff edge for the Matern impulse response function.
maternimp MATERNIMP Impulse response function for the Matern random process.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
maternspec MATERNSPEC Fourier spectrum of the Matern random process.