Description of axeshandles
Home > jlab > axeshandles.m
axeshandles
AXESHANDLES  Returns handles to all axes children.
   AXESHANDLES returns a vector of handles to all axes childen
   regardless of which figure is their parent.
   AXESHANDLES(FIGNUM) returns a vector of handles to axes children of
   Figure FIGNUM.
   See also ALLCHILD, FINDALL, LINEHANDLES, CONTOURHANDLES, PATCHHANDLES.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 1998, 2004 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
flipx FLIPX Flips the direction of the x-axis
flipy FLIPY Flips the direction of the y-axis
jgraph jGraph: Plotting tools and refinements for making high-quality figures
linering LINERING Moves lines through the current line style order.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
xlin XLIN Sets x-axis scale to linear.
xlog XLOG Sets x-axis scale to logarithmic.
xoffset XOFFSET Offsets lines in the x-direction after plotting.
ylin YLIN Sets y-axis scale to linear.
ylog YLOG Sets y-axis scale to log.
yoffset YOFFSET Offsets lines in the y-direction after plotting.