Description of bellpoly
Home > jlab > bellpoly.m
bellpoly
BELLPOLY  Complete Bell polynomials.
   BN=BELLPOLY(K1,K2,...KN) with N arguments returns the Nth order
   complete Bell polynomial BN.
   For details, see the article at Wikipedia:
        http://en.wikipedia.org/wiki/Bell_polynomials.
   The Bell polynomials are used by Lilly and Olhede (2008b) to
   create terms called "instantaneous modulation functions"
   quantifying signal time variability.
   BCELL=BELLPOLY(KCELL) also works, where KCELL is a cell array
   containing N elements of identical size.
   BELLPOLY uses an iterative algorithm.
   See also CUM2MOM, INSTMOM.
   'bellpoly --t' runs some tests.
   Usage: [b1,b2,b3]=bellpoly(k1,k2,k3);
          bcell=bellpoly(kcell);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2009 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
bellpoly BELLPOLY Complete Bell polynomials.
choose CHOOSE Binomial coefficient: CHOOSE(N,K) = "N choose K"
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
bellpoly BELLPOLY Complete Bell polynomials.
cum2mom CUM2MOM Convert cumulants to moments.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules