Description of bindata
Home > jlab > bindata.m
bindata
BINDATA  Rapidly sort data into adjacent bins.
   BINDATA is a low-level function called by the TWOD* functions.
   [NUM,XI]=BINDATA(BIN,X) sorts the array X by its values into adjactent
   bins, with bin edges given by BIN.
   NUM and XI are arrays of the same size as X.  NUM gives the bin
   number to which the corresponding elements of X are assigned, and
   XI is the midpoint value of that bin.
   [NUM,XI,MID]=BINDATA(BIN,X) also returns an array MID of the bin
   midpoints, which has length LENGTH(BIN)-1.
   BINDATA uses a clever algorithm to run amazingly fast.
   BINDATA is useful for making histograms of large datasets.
   'bindata --t' runs a test.
   See also TWODHIST, TWODSTATS, TWODMED.
   Usage: [num,xi]=bindata(bin,x);
          [num,xi,xmid]=bindata(bin,x);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
bindata BINDATA Rapidly sort data into adjacent bins.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
minmin MINMIN(X)=MIN(X(ISFINITE(X)))
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
This function is called by:
bindata BINDATA Rapidly sort data into adjacent bins.
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.