Description of blurspec
Home > jlab > blurspec.m
blurspec
BLURSPEC  Returns the blurred and aliased spectrum given the autocovariance.
   BLURSPEC is used to rapidly compute blurred, aliased, and other
   modified versions of a spectrum from a known autocovariance.
   Performing these calculations in the time domain, making use of
   Fourier relationships between modified versions of the autocovariance
   and spectrum, is much faster than working in the frequency domain.
   __________________________________________________________________
   Blurred and aliased spectra
   [F,S]=BLURSPEC(R) inverse Fourier transforms a given *one-sided*
   autocovariance R to obtain a spectrum S that incorporates the effects
   of aliasing, as well as blurring by the default taper, the 'boxcar'.
   Here F is an array of frequencies and S is the one-sided Fourier
   spectrum.  If R is length N, the output arrays will be length (N/2+1)
   if N is even and (N+1)/2 if N is odd.
   [F,SPP,SNN]=BLURSPEC(R) for complex-valued R returns SPP and SNN, the
   positive and negative rotary spectra, respectively.
   BLURSPEC(DT,R) optionally uses the sample interval DT in computing the
   frequency array F.
   __________________________________________________________________
   Tapered and aliased spectra
   BLURSPEC(R,'tapered',TAPER) incorporates the spectral smoothing due to
   the use of data TAPER, rather than the boxcar taper, in addition to the
   effects of aliasing.  TAPER must be the same length as R.
   __________________________________________________________________
   Aliased-only spectrum
   BLURSPEC(R,'aliased') computes an approximation to *aliased* spectrum,
   without blurring.  This approximation will be accurate to the extent
   that R has decayed to zero by the end of its duration.
   This is much faster than explicitly summing over aliased frequencies.
   __________________________________________________________________
   Differenced spectra
   BLURSPEC(R,'difference') returns the blurred and aliased spectrum of
   the first forward difference of the process with autocovariance R.  In
   this case the output will be length N-1.
   BLURSPEC(R,'seconddifference') returns the blurred and aliases spectrum
   of the second forward difference of the process with autocovariance R.
   The output will be length N-2.
   These options can be combined with the 'taper' and 'aliased' options
   described above.
   __________________________________________________________________
   'blurspec --t' runs some tests.
   Usage: [f,S]=blurspec(R);
          [f,Spp,Snn]=blurspec(dt,R);
          [f,Spp,Snn]=blurspec(dt,R,'tapered',TAPER);
          [f,Spp,Snn]=blurspec(dt,R,'aliased');
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2015 J.M. Lilly and A.M. Sykulski
                                 --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
blurspec BLURSPEC Returns the blurred and aliased spectrum given the autocovariance.
fourier FOURIER The one-sided Fourier frequencies for a given length time series.
frac FRAC Fraction: FRAC(A,B)=A./B
maternc MATERNC Returns the normalization function C_ALPHA for a Matern process.
materncov MATERNCOV Autocovariance function of the Matern random process.
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vrep VREP Replicates an array along a specified dimension.
vsum VSUM Sum over finite elements along a specified dimension.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
This function is called by:
blurspec BLURSPEC Returns the blurred and aliased spectrum given the autocovariance.
jmatern jMatern: Parametric spectral analysis based on the Matern process