Description of boxon
Home > jlab > boxon.m
boxon
 BOXON  Sets 'box' property to 'on'.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2006 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jpcolor JPCOLOR Modified version of PCOLOR appropriate for cell-centered grids.
makefigs_topoplot
patchcontourf PATCHCONTOURF Generate filled contours using patches, with specified colors.
regionplot REGIONPLOT Plots a simple box indicating a latitude / longitude region.
topoplot TOPOPLOT Plot regional or global topography at one-sixth degree resolution.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.
twospecplot TWOSPECPLOT Plots a pair of rotary or Cartesian spectra.