Description of cellmean
Home > jlab > cellmean.m
cellmean
CELLMEAN  Mean value of each element a cell array or set of cell arrays.
   M=CELLMEAN(X) where X is a cell array of N arrays,
       X{1}=X1, X{2}=X2,..., X{N}=XN
   returns the N x 1 array of mean values M with
      M(1)=MEAN(X1(:)),  M(2)=MEAN(X2(:)),...,  M(N)=MEAN(XN(:)).
   In taking the mean, non-finite values are ignored, as in VMEAN.
   M is a column vector of the same length as X.
   [M1,M2,...,MP]=CELLMEAN(X1,X2,...,XP) also works for P different
   input arguments.
   CELLMEAN(X1,X2,...XP);  with no output arguments overwrites the
   original input variables.
   See also JCELL, VTOOLS.
   Usage: m=cellmean(x);
          [m1,m2,m3]=cellmean(x1,x2,x3);
          cellmean(x1,x2,x3);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
col2mat COL2MAT Expands 'column-appended' data into a matrix.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vcolon VCOLON Condenses its arguments, like X(:).
vmean VMEAN Mean over finite elements along a specified dimension.
This function is called by:
jcell jCell: Tools for operating on cell arrays of column vectors