Description of cellsize
Home > jlab > cellsize.m
cellsize
CELLSIZE  Size of each element in a cell array along specified dimension.
   S=CELLSIZE(X,DIM) where X is a cell array of N arrays,
       X{1}=X1, X{2}=X2,..., X{N}=XN
   returns the N x 1 array of lengths S with
      S(1)=SIZE(X1,DIM), S(2)=SIZE(X2,DIM),..., S(N)=SIZE(XN,DIM).
   S is the same size as X.
   CELLSIZE requires the cell array X to have four or fewer dimensions.
   See also CELLENGTH.
   Usage: s=cellsize(x,dim);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2009 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
cellsize CELLSIZE Size of each element in a cell array along specified dimension.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
cellength CELLENGTH Length of each element in a cell array.
cellsize CELLSIZE Size of each element in a cell array along specified dimension.
jcell jCell: Tools for operating on cell arrays of column vectors