Description of cellabs
Home > jlab > cellabs.m
cellabs
CELLABS  Absolute value of each element in a cell array.
   XA=CELLABS(X) where X is a cell array of N arrays,
       X{1}=X1, X{2}=X2,..., X{N}=XN
   returns the length N cell array of XA with
      XA(1)=ABS(X1), XA(2)=ABS(X2),..., XA(N)=ABS(XN).
   See also JCELL.
   Usage: xa=cellabs(x);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2009 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
jcell jCell: Tools for operating on cell arrays of column vectors
twodmed TWODMED Median value of a function of two variables.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.