Description of cellplot
Home > jlab > cellplot.m
cellplot
CELLPLOT  Rapidly plot all elements of a cell array of numeric arrays.
   CELLPLOT(X) where X is a cell array containing N arrays,
       X{1}=X1, X{2}=X2,..., X{N}=XN
   is the same as
      PLOT(X1), PLOT(X2),..., PLOT(XN).
   However, CELLPLOT is vastly quicker than the obvious loop and also has
   some handy features, as described below.
   CELLPLOT(X,Y), where X and Y are both cell arrays of N arrays, performs
      PLOT(X1,Y1), PLOT(X1,Y1),..., PLOT(XN,YN).
   H=CELLPLOT(...) returns the handle to the plots.
   CELLPLOT is compatible with the M_MAP toolbox, as described below.%
   CELLPLOT(X) or CELLPLOT(X,Y) still works if X and Y are not cell
   arrays, but are vectors or matrices.  This is useful in accessing the
   additional options described below.
   __________________________________________________________________
   Additional options
   CELLPLOT(...,STY) uses the linestyle specified by STY.  STY is a
   string following the format in LINESTYLE, e.g. STY='2b g r--'.
   CELLPLOT(...,'M_MAP') will work with Rich Pawlowicz's M_MAP
   package by calling M_PLOT.
   CELLPLOT(...,INDEX) only plots the elements of the cell array
   indicated by index.
   The string arguments and INDEX can be combined provided they are
   after the one or two input cell array variables.
   __________________________________________________________________
   CELLPLOT on the sphere
   When plotting data on the sphere, there is an annoying wrap-around
   effect when the data crosses the dateline at longitude 180.  This
   leads to lines extending all the way across the plot.
   CELLPLOT(LONO,LON,LAT) where LONO is the value of a cutoff longitude
   uses LONO as the right-hand-edge of the plot, and LONO-360 as the
   left-hand-edge, with no wraparound effects.
   This works together also with the 'm_map' option.  In this case LONO
   should be between -180 and 180, and one must set the maximum longitude
   in M_MAP to LONO. For a global plot, this means one will call M_PROJ as
         M_PROJ(...,'longitudes',[LONO-360 LONO],...).
   If you run CELLPLOT with M_MAP and data doesn't show up, make sure
   the longitudes have been set correctly.
   __________________________________________________________________
   See also LINESTYLE.
   Usage: cellplot(x)
          cellplot(x,y)
          h=cellplot(x,y,index,'m_map');
          cellplot(lono,lat,lon,index);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
boxon BOXON Sets 'box' property to 'on'.
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
cellength CELLENGTH Length of each element in a cell array.
col2cell COL2CELL Converts 'column-appended' data into cell arrays of column vectors.
deg360 DEG360 Converts degrees to the range [0, 360].
frac FRAC Fraction: FRAC(A,B)=A./B
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
mat2col MAT2COL Compress NAN-padded matrix data into long columns.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
minmin MINMIN(X)=MIN(X(ISFINITE(X)))
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
This function is called by:
about_drifters DRIFTERS Global surface drifter dataset from the Global Drifter Program.
about_floats FLOATS Historical dataset of eddy-resolving subsurface floats.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
jcell jCell: Tools for operating on cell arrays of column vectors
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
makefigs_topoplot
regionplot REGIONPLOT Plots a simple box indicating a latitude / longitude region.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.
twospecplot TWOSPECPLOT Plots a pair of rotary or Cartesian spectra.