Description of cell2col
Home > jlab > cell2col.m
cell2col
CELL2COL  Converts cell arrays of column vectors into 'column-appended' data.
   COL=CELL2COL(X) concatenates X, a cell array of N column vectors, into a
   single column vector COL with N blocks of data, each ending with a NAN.
   If the data is complex, each column will end with NAN+SQRT(-1)*NAN;
   To mark missing data, any pre-exiting NANs in X will be replaced with
   INFs, and any complex NANs will be replaced with complex INFs.
   CELL2COL(X) where X is a cell array of numeric arrays of any dimension
   also works.  In this case each array will be convered into a column
   vector via X{1}=X{1}(:) and so forth prior to concatenation.
   __________________________________________________________________
   Multiple input /output arguments
   [C1,C2,...,CN]=CELL2COL(X1,X2,...,XN) also works.
   __________________________________________________________________
   Variable overwriting
   CELL2COL(X1,X2,...,XN) with no output arguments overwrites the input
   variables.
   __________________________________________________________________
   Invertibility
   CELL2COL is inverted by COL2CELL, provided
       (i)  The cell arrays XN are all column vectors of the same size and
       (ii) The first input argument X1 contains no NANs.
   __________________________________________________________________
   See also COL2CELL, COL2MAT, MAT2COL, COLBREAKS, COL2CELL.
   Usage: col=cell2col(x);
          [c1,c2,...,cN]=cell2col(x1,x2,...,xN);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
nonnan NONNAN Return all non-NAN elements of an array.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
This function is called by:
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
cellchunk CELLCHUNK Converts cell array data into uniform length 'chunks'.
cellmean CELLMEAN Mean value of each element a cell array or set of cell arrays.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
col2cell COL2CELL Converts 'column-appended' data into cell arrays of column vectors.
curveinterp CURVEINTERP Interpolate a field or its gradient onto a set of curves.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellipseplot ELLIPSEPLOT Plot ellipses.
inregion INREGION Tests whether lat/lon points lie within a specified box.
jcell jCell: Tools for operating on cell arrays of column vectors
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
trajchunk TRAJCHUNK Converts Lagrangian trajectories into chunks based on the Coriolis period.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.
trajfill TRAJFILL Fills float or drifter trajectories with linear interpolation.
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
twospecplot TWOSPECPLOT Plots a pair of rotary or Cartesian spectra.