Description of cellreal
Home > jlab > cellreal.m
cellreal
CELLREAL  Real part of each element in a cell array.
   XR=CELLREAL(X) where X is a cell array of N arrays,
       X{1}=X1, X{2}=X2,..., X{N}=XN
   returns the length N cell array XR with
      XR(1)=REAL(X1), XR(2)=REAL(X2),..., XR(N)=REAL(XN).
   See also JCELL.
   Usage: xr=cellreal(x);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2009 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
jcell jCell: Tools for operating on cell arrays of column vectors
uv2latlon UV2LATLON Integrates horizontal velocity to give latitude and longitude.
xy2latlon XY2LATLON Converts local Cartesian coordinates into latitude and longitude.