Description of cellmult
Home > jlab > cellmult.m
cellmult
CELLMULT  Multiplication acting on each element in a cell array.
   Z=CELLMULT(X,Y) where X and Y are both cell arrays of N arrays,
       X{1}=X1, X{2}=X2,..., X{N}=XN
   with the Nth element in X and in Y having the same size, returns the
   cell array Z containing their products,
       Z{1}=X{1}.*Y{1}, Z{2}=X{2}.*Y{2},..., Z{N}=X{N}.*Y{N}.
   X may also be a scalar or an array of N=LENGTH(Y) numbers.
   Usage: z=cellmult(x,y);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008--2013 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
curveinterp CURVEINTERP Interpolate a field or its gradient onto a set of curves.
jcell jCell: Tools for operating on cell arrays of column vectors
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.