Description of cellength
Home > jlab > cellength.m
cellength
CELLENGTH  Length of each element in a cell array.
   L=CELLENGTH(X) where X is a cell array of N arrays,
       X{1}=X1, X{2}=X2,..., X{N}=XN
   returns the N x 1 array of lengths L with
      L(1)=LENGTH(X1), L(2)=LENGTH(X2),..., L(N)=LENGTH(XN).
   L is the same size as X.
   CELLENGTH requires the cell array X to have four or fewer dimensions.
   See also CELLSIZE.
   Usage: len=cellength(x);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2009 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
cellsize CELLSIZE Size of each element in a cell array along specified dimension.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
about_drifters DRIFTERS Global surface drifter dataset from the Global Drifter Program.
about_floats FLOATS Historical dataset of eddy-resolving subsurface floats.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
commentlines COMMENTLINES Returns the comment lines from m-files.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
jcell jCell: Tools for operating on cell arrays of column vectors
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
trajchunk TRAJCHUNK Converts Lagrangian trajectories into chunks based on the Coriolis period.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.