Description of closedcurves
Home > jlab > closedcurves.m
closedcurves
CLOSEDCURVES  Locate and interpolate closed curves in a possibly periodic domain.
   _______________________________________________________________________
   ______________________________________________________________________
   [XC,YC]=CLOSEDCURVES(F,FO) returns closed curves of the matrix F at
   level FO, i.e. curves where F=FO, as the cell arrays XC and YC.
   If F has N contiguous patches at the contour level FO, then XC and YC
   will be length N cell arrays.
   After rounding, the values of XC will be indices into the *columns*
   of F, while YC will be indices into the *rows*.
   [XC,YC]=CLOSEDCURVES(X,Y,F,FO) alternately specifies X and Y axes to go
   with F.  X is associated with the *columns* of F and Y with its *rows*.
   The lengths of X and Y must match SIZE(F,2) and SIZE(F,1) respectively.
   Use CELLPLOT(XC,YC) to plot the curves.
   CLOSEDCURVES works by calling Matlab's CONTOUR routine, re-arranging
   the contour matrix output, and throwing away non-closed contours.
   CLOSEDCURVES has options for considering a periodic domain, and for
   interpolating the curves at a specified resolution, as described below.
   The above figure shows closed curves of the Okubo-Weiss parameter P,
   specifically the contour level P = -4 times its own standard deviation,
   in a numerical simulation of quasi-geostrophic (QG) turbulence.
   __________________________________________________________________
   Periodic extension
   CLOSEDCURVES can look for curves within a singly or doubly periodic
   version of the input field F.
   CLOSEDCURVES(...,'periodic') will make F doubly periodic before looking
   for closed curves.
   The X and Y axes will be extended based on their regular spacing, and
   these extended values will be returned in XC and YC for curves that
   fall into the periodically extended domain.
   CLOSEDCURVES(...,'periodic',N) extends F by N points in all directions.
   CLOSEDCURVES(...,'periodic',N,M) extends F by M points at both the left
   and the right (rows), and N points at the top and the bottom (columns).
   To apply the periodic extension in only one of the dimesions, use
   CLOSEDCURVES(...,'periodic',N,0) or CLOSEDCURVES(...,'periodic',0,M).
   The above figure illustrates the difference between the periodized and
   non-periodized algorithm.  In periodic domain such as this one, closed
   curves at the region boundary will be missed wihtout periodization.
   See PERIODIZE for details.
   __________________________________________________________________
   Interpolation
   CLOSEDCURVES can also interpolate the curves to a specified number of
   points along each curve, in order to increase the spatial resolution.
   [XC,YC]=CLOSEDCURVES(...,'interpolate',NPOINTS) will spline-interpolate
   each curve to be length NPOINTS.
   In this case, XC and YC will be *matrices* instead of cell arrays.  The
   number of rows of XC and YC is then NPOINTS, with each column
   corresponding to a separate curve.
   Choosing a high value of NPOINTS, say NPOINTS=256, will minimize errors
   in integral calculations based on these curves, such as those carried
   out by CURVEMOMENTS.
   __________________________________________________________________
   See also CURVEMOMENTS, CURVEINTERP, PERIODIZE.
   'closedcurves --t' runs a test.
   'closedcurves --f' generates the above figure.
   Usage: [xc,yc]=closedcurves(f,fo);
          [xc,yc]=closedcurves(x,y,f,fo);
          [xc,yc]=closedcurves(x,y,f,fo,'interpolate',256);
          [xc,yc]=closedcurves(x,y,f,fo,'periodic',M);
          [xc,yc]=closedcurves(x,y,f,fo,'periodic',N,M);
          [xc,yc]=closedcurves(x,y,f,fo,'periodic',N,M,'interpolate',256);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
cellength CELLENGTH Length of each element in a cell array.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
crop CROP Gets rid of whitespace around an image. [by A. Bliss]
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
flipmap FLIPMAP Flips the current colormap upside-down.
fontsize FONTSIZE Rapidly set title, axes, label, and text fontsizes.
frac FRAC Fraction: FRAC(A,B)=A./B
hlines HLINES Add horizontal lines to a plot.
jpcolor JPCOLOR Modified version of PCOLOR appropriate for cell-centered grids.
minmin MINMIN(X)=MIN(X(ISFINITE(X)))
noxlabels NOXLABELS Remove some or all x-axis tick mark labels.
noylabels NOYLABELS Remove some or all y-axis tick mark labels.
periodize PERIODIZE Returns a doubly periodic version of an input array.
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
reporttest REPORTTEST Reports the result of an m-file function auto-test.
use USE Copies structure fields into named variables in workspace.
vindex VINDEX Indexes an N-D array along a specified dimension.
vlines VLINES Add vertical lines to a plot.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
xtick XTICK Sets locations of x-axis tick marks.
ytick YTICK Sets locations of y-axis tick marks.
This function is called by:
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curveinterp CURVEINTERP Interpolate a field or its gradient onto a set of curves.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
joceans jOceans: Oceanography-specific data and model analysis tools
patchcontourf PATCHCONTOURF Generate filled contours using patches, with specified colors.