Description of col2mat
Home > jlab > col2mat.m
col2mat
COL2MAT  Expands 'column-appended' data into a matrix.
   M=COL2MAT(C), where C is a column vector of data segments
   separated by NANs, expands the data into a matrix such that each
   segment has its own column.  For instance, the intervals may
   represent CTD casts of various depths, and the NANs mark
   transitions between casts.
   M will have enough rows to fit the longest data segment. Segments
   are read into columns of M from the top down, leaving empty spaces
   at the bottom which are filled in with NANs.
   If the data is complex, then gaps are filled with NAN+SQRT(-1)*NAN;
   [M1,M2,....]=COL2MAT(C1,C2,...), where C1,C2,... are input column
   vectors, also works, as does [M1,M2,....]=COL2MAT(MAT), where MAT
   is a matrix of column vectors.  In both cases the first column is
   used as the reference for the others, so that only the locations
   of NANs in the first column matters.
   COL2MAT, MAT2COL, and COLBREAKS together form a system for moving
   data with segments of nonuniform length rapidly back and forth
   between a column format and a padded-matrix format.  CTD or float
   data, for instance, can be stored in the (usually much smaller)
   column format and converted into the matrix format upon loading.
   COL2MAT(C1,C2,...); with no output arguments overwrites the
   original input variables.
   See also MAT2COL, COLBREAKS, COL2CELL, CELL2COL.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2013 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
about_drifters DRIFTERS Global surface drifter dataset from the Global Drifter Program.
cellmean CELLMEAN Mean value of each element a cell array or set of cell arrays.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
trajchunk TRAJCHUNK Converts Lagrangian trajectories into chunks based on the Coriolis period.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.
twodmed TWODMED Median value of a function of two variables.