Description of col2cell
Home > jlab > col2cell.m
col2cell
COL2CELL  Converts 'column-appended' data into cell arrays of column vectors.
   X=COL2CELL(COL) converts the column vector COL of N data blocks into a
   cell array X containing N column vectors.
   The column vector COL has a NAN marking the end of each block.  The
   cell array X exludes the NANs.
   Since NANs mark the end of each block, missing or bad data in COL
   should instead be indicated by INFs.
   __________________________________________________________________
   Multiple input /output arguments
   [X1,X2,...,XN]=COL2CELL(C1,C2,...,CN) also works, where the CN are all
   the same size.
   In this case C1 is the 'key' and the locations of NANs in C1 is used
   to break all the CN into cells.   Thus the CN with N>1 may contain
   additional NANS.
   __________________________________________________________________
   Variable overwriting
   COL2CELL(C1,C2,...,CN) with no output arguments overwrites the input
   variables.
   __________________________________________________________________
   Invertibility
   COL2CELL is inverted by CELL2COL.
   __________________________________________________________________
   'col2cell --t' runs a test.
   See also CELL2COL, COL2MAT, MAT2COL, COLBREAKS.
   Usage: x=col2cell(col);
          [x1,x2,...,xN]=col2cell(c1,c2,...,cN);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
col2cell COL2CELL Converts 'column-appended' data into cell arrays of column vectors.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
This function is called by:
about_drifters DRIFTERS Global surface drifter dataset from the Global Drifter Program.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
col2cell COL2CELL Converts 'column-appended' data into cell arrays of column vectors.
curveinterp CURVEINTERP Interpolate a field or its gradient onto a set of curves.
jcell jCell: Tools for operating on cell arrays of column vectors
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.