Description of commentlines
Home > jlab > commentlines.m
commentlines
COMMENTLINES  Returns the comment lines from m-files.
   COMMENTLINES is used to facilitate making 'Contents.m' files.
   COMMENTLINES returns a string matrix which contains all the comment
   lines, i.e the first line beginning with '%', from all m-files in the
   current directory.
   COMMENTLINES DIRNAME applies to directory DIRNAME.
   COMMENTLINES with no input argument appies itself to the current
   working directory.
   COMMENTLINES FILENAME applies to just m-file FILENAME.
   Examples:  commentlines plot
              commentlines elmat
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2002--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
cellength CELLENGTH Length of each element in a cell array.
findpath FINDPATH Returns the full pathname of a directory on the Matlab search path.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
This function is called by:
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules