Description of Contents
Home > jlab > Contents.m
Contents
  jLab v1.5 by J. M. Lilly
  A Matlab toolbox for large-scale data analysis, signal processing,
  mapping, and oceanographic applications.
  Requires Matlab version 2014b.
  ________________________________________________________________________
 General purpose modules
   jcommon -  Useful general-purpose functions, common to other JLAB modules
   jgraph  -  Plotting tools and refinements for making high-quality figures
   jcell   -  Tools for operating on cell arrays of column vectors
   jvarfun -  Perform common operations on multiple variables simultaneously
   jsphere -  Tools for latitude, longitude, and spherical geometry
 Statistical analysis and mapping
   jstats -  Fast statistical analysis of large datasets in two dimensions
   jmap   -  Mapping scattered data using local polynomial fitting
   jtopo  -  Tools and data for plotting topography
 Signal analysis
   jspectral - Multitaper spectral analysis, and other time series tools
   jwavelet  - Continuous wavelet analysis using generalized Morse wavelets
   jridges   - Wavelet ridge analysis of modulated oscillatory signals
   jellipse  - Analysis of modulated elliptical, or bivariate, signals
   jmatern   - Parametric spectral analysis based on the Matern process
 Oceanography-specific tools and data
   jdata    - Oceanographic datasets included with JLAB-FULL distribution
   joceans  - Oceanography-specific data and model analysis tools
 Administrative M-files
   jlab_install    - Instructions for installing JLAB.
   jlab_license    - License statement and permissions for JLAB package.
   jlab_highlights - Introduction to some of the most useful routines.
   jlab_allhelp    - Displays the help comments for all JLAB modules.
   jlab_changes    - Changes to JLAB in each release.
   jlab_thanks     - Sources of support for developing this software.
   jlab_makefigs   - Makes figures for papers by J.M. Lilly.
 _________________________________________________________________________
 Send comments, questions, and bug reports to "eponym@jmlilly.net".
This function calls:
jcell jCell: Tools for operating on cell arrays of column vectors
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jdata jData: Oceanographic datasets included with JLAB-FULL distribution
jellipse jEllipse: Analysis of modulated elliptical, or bivariate, signals
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_addpath JLAB_ADDPATH Adds JLAB subdirectories to your Matlab search path.
jlab_allhelp JLAB_ALLHELP Displays the help comments for all JLAB modules.
jlab_changes JLAB_CHANGES Changes to JLAB in each release.
jlab_highlights JLAB_HIGHLIGHTS Introduction to some of the most useful routines.
jlab_install JLAB_INSTALL Instructions for installing JLAB.
jlab_license JLAB_LICENSE License statement and permissions for JLAB package.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jlab_runtests JLAB_RUNTESTS Runs a test suite for JLAB package.
jlab_thanks JLAB_THANKS Sources of support for developing this software.
jmap jMap: Mapping scattered data using local polynomial fitting
jmatern jMatern: Parametric spectral analysis based on the Matern process
joceans jOceans: Oceanography-specific data and model analysis tools
jridges jRidges: Wavelet ridge analysis of modulated oscillatory signals
jspectral jSpectral: Multitaper spectral analysis, and other time series tools
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
jstats jStats: Fast statistical analysis of large datasets in two dimensions
jtopo jTopo: Tools and data for plotting topography
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
This function is called by: