Description of corfreq
Home > jlab > corfreq.m
corfreq
CORFREQ  Coriolis frequency in radians per hour.
   FC=CORFREQ(LAT) returns the Coliolis frequency at latitude LAT in
   *radians* per hour.  FC is negative in the Northern Hemisphere and
   positive in the Southern Hemisphere.
   The input argument LAT may also be a cell array of numeric arrays.  In
   this case FC will also be a cell array of the same size.
   'corfreq --t' runs a test.
   Usage: fc=corfreq(lat);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
corfreq CORFREQ Coriolis frequency in radians per hour.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
corfreq CORFREQ Coriolis frequency in radians per hour.
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
mspec MSPEC Multitaper power and cross spectra.
trajchunk TRAJCHUNK Converts Lagrangian trajectories into chunks based on the Coriolis period.
twospecplot TWOSPECPLOT Plots a pair of rotary or Cartesian spectra.