Description of curvemoments
Home > jlab > curvemoments.m
curvemoments
CURVEMOMENTS  Centroid, area, and many other moments of a closed curve.
   _______________________________________________________________________
   ______________________________________________________________________
   [XO,YO]=CURVEMOMENTS(XC,YC) returns the centroid of the region bounded
   by the closed curve specified by the column vectors XC and YC.
   [XO,YO,L,R,D]=CURVEMOMENTS(XC,YC) also returns the arc length L, area
   radius R defined such that pi R^2 is the enclosed area, and the root-
   mean-squared distance D from the curve periphery to the centroid.
   [XO,YO,L,R,D,A,B,THETA]=CURVEMOMENTS(XC,YC) also returns the region's
   second central moment, the area moment of inertia.  This describes an
   ellipse with semi-major and minor axes A and B, and orientation THETA.
   The moments are calculated from the curve (XC,YC) using expressions
   for converting spatial to line integrals derived from Green's theorem.
   XC and YC may be matrices, with each column specifying a different
   closed curve.  In this case, all curves must contain the same number
   of points, corresponding to the rows.  No NaNs may be present.
   XC and YC may also be cell arrays of column vectors.  In this case, the
   moments will be numerical arrays with the same lengths as XC and YC.
   The above figure illustrates an application of CURVEMOMENTS to a
   quasigeostrophic eddy field from QGSNAPSHOT.  The blue curves are
   curves of constant Okubo-Weiss parameter.  These are well matched by
   the red curves, constructed from the second central moment quantites
   A, B, and THETA, and centered at the curve centroids XO, YO.
   __________________________________________________________________
   Velocity moments: Vorticity, angular momentum, kinetic energy, etc.
   CURVEMOMENTS can also compute various moments based on the velocity.
   [VORT,DIV,MOM,KE]=CURVEMOMENTS(XC,YC,ZC) where ZC is the complex-valued
   velocity ZC=U+iV along the curve, returns the spatially-averaged
   vorticity VORT, the spatially-averaged divergence MOM, and the angular
   momentum MOM and kinetic energy KE averaged along the curve periphery.
   For the velocity moments, CURVEMOMENTS expects XC and YC to have units
   of km while ZC is in cm/s.  VORT and DIV then have units of 1/s, MOM
   and MOMSTD have units of cm^2/s, and KE has units of cm^2/s^2.
   Note that VORT and DIV are computed as integrals of the tangential and
   normal velocities along the curve, respectively, then converted to area
   averages by applying Stokes' theorem and the divergence theorem.
   MOM is the average angular momentum along the curve with respect to the
   curve centroid. KE is the average value of the kinetic energy along the
   curve, a velocity quantity analagous to averaged squared distance D^2.
   __________________________________________________________________
   See also CLOSEDCURVES, CURVEINTERP.
   'curvemoments --t' runs some tests.
   'curvemoments --f' generates the above figure.
   Usage: [xo,yo]=curvemoments(xc,yc);
          [xo,yo,L,R,D]=curvemoments(xc,yc);
          [xo,yo,L,R,D,a,b,theta]=curvemoments(xc,yc);
          [vort,div,mom,ke,momstd]=curvemoments(xc,yc,zc);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013--20154 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
ab2kl AB2KL Converts A and B to ellipse parameters Kappa and Lambda.
allall ALLALL(X)=ALL(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
cellength CELLENGTH Length of each element in a cell array.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
crop CROP Gets rid of whitespace around an image. [by A. Bliss]
curveinterp CURVEINTERP Interpolate a field or its gradient onto a set of curves.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
ellipseplot ELLIPSEPLOT Plot ellipses.
flipmap FLIPMAP Flips the current colormap upside-down.
fontsize FONTSIZE Rapidly set title, axes, label, and text fontsizes.
frac FRAC Fraction: FRAC(A,B)=A./B
jpcolor JPCOLOR Modified version of PCOLOR appropriate for cell-centered grids.
noxlabels NOXLABELS Remove some or all x-axis tick mark labels.
noylabels NOYLABELS Remove some or all y-axis tick mark labels.
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
reporttest REPORTTEST Reports the result of an m-file function auto-test.
specdiag SPECDIAG Diagonalize a 2 x 2 spectral matrix.
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
vempty VEMPTY Initializes multiple variables to empty sets or empty cell arrays.
vmean VMEAN Mean over finite elements along a specified dimension.
vrep VREP Replicates an array along a specified dimension.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
vtranspose VTRANSPOSE Transpose multiple input arguments simultaneously.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
xtick XTICK Sets locations of x-axis tick marks.
ytick YTICK Sets locations of y-axis tick marks.
This function is called by:
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
joceans jOceans: Oceanography-specific data and model analysis tools