Description of dawsonderiv
Home > jlab > dawsonderiv.m
dawsonderiv
DAWSONDERIV  Derivatives of the Dawson function.
   DAWSONDERIV is a low-level function called for testing purposes by
   MORSEWAVE.
   DCELL=DAWSONDERIV(X,N) returns the first N derivatives of the Dawson
   function at positions X.
   All elements of DCELL have the same size as X.  DCELL{1} is the first
   derivative, and so forth.
   A form for the derivatives of the DAWSON function is given by Lilly
   and Olhede (2008b), and involves Hermite polynomials.
   See also DAWSON, HERMPOLY.
   'dawsonderiv --t' runs a test.
   'dawsonderiv --f' generates a sample figure.
   Usage: dn=dawsonderiv(x,n);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
choose CHOOSE Binomial coefficient: CHOOSE(N,K) = "N choose K"
dawson DAWSON The Dawson function. [By P.J. Acklam]
dawsonderiv DAWSONDERIV Derivatives of the Dawson function.
hermpoly HERMPOLY Hermite polynomials. [with F. Rekibi]
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vdiff VDIFF Length-preserving first central difference.
vsum VSUM Sum over finite elements along a specified dimension.
This function is called by:
dawsonderiv DAWSONDERIV Derivatives of the Dawson function.
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).