Description of dawson
Home > jlab > dawson.m
dawson
DAWSON The Dawson function. [By P.J. Acklam]
   DAWSON is a low-level function called for testing purposes by
   MORSEWAVE.
   Y = DAWSON(X) is Dawson's integral for each element of X.
   X must be real.
   Dawson's integral F(x) is defined as
     F(x) = exp(-x^2) * integral from 0 to x of exp(t^2) dt
   The Dawson function is also the Hilbert transform of the Gaussian,
   see for example Lilly and Olhede (2009).
   See also ERF, ERFC, DAWSONDERIV.
   'dawson --t' runs a test.
   Usage: x=dawson(x);
   __________________________________________________________________
   Written 2004 P.J. Acklam, redistributed with permission, thank you
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015  P.J. Acklam and J.M. Lilly
                             --- type 'help jlab_license' for details
This function calls:
anatrans ANATRANS Analytic part of signal.
dawson DAWSON The Dawson function. [By P.J. Acklam]
frac FRAC Fraction: FRAC(A,B)=A./B
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vsum VSUM Sum over finite elements along a specified dimension.
This function is called by:
dawson DAWSON The Dawson function. [By P.J. Acklam]
dawsonderiv DAWSONDERIV Derivatives of the Dawson function.
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).