Description of deg360
Home > jlab > deg360.m
deg360
DEG360  Converts degrees to the range [0, 360].
   [TH1,TH2,...THN]=DEG360(TH1,TH2,...THN) converts the input
   angles, which are measured in degrees, to the range [0, 360].
   More precisely, the output range is defined to include 0, but exclude
   360, so DEG360(360) is defined as 360-EPS where EPS is 1e-10.
   See also DEG180.
   'deg360 --t' runs a test.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2013 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
deg180 DEG180 Converts degrees to the range [-180,180].
deg360 DEG360 Converts degrees to the range [0, 360].
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
deg180 DEG180 Converts degrees to the range [-180,180].
deg360 DEG360 Converts degrees to the range [0, 360].
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
lonshift LONSHIFT Shifts longitude origin for plotting purposes.
regionplot REGIONPLOT Plots a simple box indicating a latitude / longitude region.