Description of divgeom
Home > jlab > divgeom.m
divgeom
DIVGEOM  Geometric decomposition of eddy vorticity flux divergence.
   [F1,F2,F3,F4]=DIVGEOM(K,L,THETA) returns the geometric decomposition
   of eddy vorticity flux divergence associated with variance ellipses
   having kinetic energy K, anisotropy L, and orientation THETA.
   K, L, and THETA are matrices of the same size.  These are defined on an
   X-Y grid with x oriented in *columns* and y oriented in *rows*.
   Note that K and L are related to ellipse parameters KAPPA and LAMBDA
   used elsewhere in JLAB by K=KAPPA^2 and L=LAMBDA*KAPPA^2.
   F1, F2, F3, and F4 are four different contributions to the eddy
   vorticity flux divergence, as follows:
       F1     Quadratic variations in the linear energy L
       F2     Product of linear variations in THETA and L
       F3     Quadratic variations in the orientation THETA
       F4     Product of linear variations in orientation THETA
   For details, see Waterman and Lilly (2015), Geometric decomposition of
   eddy-mean flow feedbacks in barotropic systems, J. Phys. Oceanogr.
   DIVGEOM(DX,...) alternately uses a grid spacing of DX for computing the
   derivatives, with a default value DX=1.
   [F1,F2,F3,F4,F]=DIVGEOM(...) also returns the total eddy flux
   divergence F, calculated directly, with F1+F2+F3+F4 = F apart from
   numerical error.
   By default, DIVGEOM calculates derivates with repeated applications of
   a first central difference.  DIVGEOM(...,'arakawa') alternately uses a
   modified first central difference appropriate for models that employ an
   Awakawa advection scheme.
   __________________________________________________________________
   Usage: [F1,F2,F3,F4]=divgeom(K,L,theta);
          [F1,F2,F3,F4,F]=divgeom(dx,K,L,theta);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
anatrans ANATRANS Analytic part of signal.
aresame ARESAME Test whether two N-D arrays are the same.
divgeom DIVGEOM Geometric decomposition of eddy vorticity flux divergence.
frac FRAC Fraction: FRAC(A,B)=A./B
jpcolor JPCOLOR Modified version of PCOLOR appropriate for cell-centered grids.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
packfig PACKFIG Squeeze together rows and/or columns of the current figure.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
use USE Copies structure fields into named variables in workspace.
vdiff VDIFF Length-preserving first central difference.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
This function is called by:
divgeom DIVGEOM Geometric decomposition of eddy vorticity flux divergence.
joceans jOceans: Oceanography-specific data and model analysis tools