Description of dlines
Home > jlab > dlines.m
dlines
DLINES   Add diagonal lines to a plot.
   DLINES(M,STYLE) puts diagonal lines with slopes M having style
   described by the string STYLE.
   By default, DLINES uses the lower left corner of the current axis
   as the line origin for M>0, and the lower right corner if M<0.
   DLINES(M,Y0,STYLE) instead uses Y0 as the intercept of the left-
   hand side of the current x-axis.
   (Note that the above descriptions refer to the axis sides with
   the 'normal', rather than 'reverse', directions.)
   The SYTLE strings follow the format specified in LINESTYLE.  Thus
   STYLE='2b--' draws blue dotted lines of width 2.
   STYLE is optional and defauts to STYLE='g--', a green dashed line.
   H=DLINES(...) returns an array of handles H to the lines.
   See also HLINES, VLINES.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
dlines DLINES Add diagonal lines to a plot.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
This function is called by:
dlines DLINES Add diagonal lines to a plot.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
morlfreq MORLFREQ Compute Morlet wavelet carrier frequency given peak frequency.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.