Description of doublen
Home > jlab > doublen.m
doublen
 DOUBLEN  Interpolates a time series to double its length.
   Y=DOUBLEN(X) for a column vector X of length M, returns the
   interpolation of X to length 2M.  M must be even.
   For matrix X of size M x N, each column is interpolated to length
   2M, and Y is size 2M x N.
   The interpolated vector Y may be considered to be of the same
   duration, but with twice the sample rate, as the original vector.
   In the interpolated vector, all frequencies higher than the
   original Nyquist are set to zero.
   DOUBLEN uses the frequency-domain zero padding algorithm of Mallat
   (1999), second edition, Section 4.5.4.
   'doublen --t' runs a test
   'doublen --f' generates a sample figure
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
doublen DOUBLEN Interpolates a time series to double its length.
isodd ISODD True for odd integer values; false otherwise.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vfilt VFILT Filtering along rows without change in length.
This function is called by:
doublen DOUBLEN Interpolates a time series to double its length.
jspectral jSpectral: Multitaper spectral analysis, and other time series tools
wigdist WIGDIST Wigner distribtion (alias-free algorithm).