Description of ecconv
Home > jlab > ecconv.m
ecconv
ECCONV  Converts between eccentricity measures.
   Y=ECCONV(X,STR) converts the eccentricity measure X into eccentricity
   measure Y as specified by the string STR.
   STR is of the form 'in2out' where the names 'in' and 'out' may be
   chosen from the following table.
       STR        Name                    Definition
       ----------------------------------------------------------------
      'ecc'       Eccentricity            sgn(b)*sqrt(1-b^2/a^2)
      'ell'       Ellipticity             b/a
      'lin'       Linearity               sgn(b)*(a^2-b^2)/(a^2+b^2)
      'circ'      Circularity             2ab/(a^2+b^2)
      'nu'        Eccentricity angle      asin(b/sqrt(a^2 + b^2))
      'rot'       Rotary ratio            sgn(b)*(a-abs(b))/(a+abs(b))
   where "a" and "b" are the semi-major and semi-minor axes respective.
   For example, ECC=ECCONV(L,'lin2ecc') converts the ellipse linearity L
   into eccentricity ECC.
   All quantities are positive for mathematically positive rotation
   and negative for mathematically negative rotation.  Note the linearity
   is undefined for the case of purely circular rotation a=abs(b);
   For further details, see Lilly and Gascard (2006).
   ____________________________________________________________________
   Cell array input/output
   If ECCONV is given cell array input, it returns cell array output.
   Thus X may be a cell arrays of numerical arrays, and the output Y will
   also be a cell array having an identical size as X.
   ____________________________________________________________________
   See also ELLCONV, ELLDIFF, TRANSCONV.
   Usage:   lin=ecconv(b./a,'ell2lin');
            ecc=ecconv(lin,'lin2ecc');
   'ecconv --t' runs a test.
   'ecconv --f' generates a sample figure.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2005--2012 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
ecconv ECCONV Converts between eccentricity measures.
ellipseplot ELLIPSEPLOT Plot ellipses.
fixlabels FIXLABELS Specify precision of axes labels.
fontsize FONTSIZE Rapidly set title, axes, label, and text fontsizes.
frac FRAC Fraction: FRAC(A,B)=A./B
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
xtick XTICK Sets locations of x-axis tick marks.
ytick YTICK Sets locations of y-axis tick marks.
This function is called by:
ab2kl AB2KL Converts A and B to ellipse parameters Kappa and Lambda.
ecconv ECCONV Converts between eccentricity measures.
ellrad ELLRAD Average and instantaneous ellipse radius.
jellipse jEllipse: Analysis of modulated elliptical, or bivariate, signals
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.