Description of ellband
Home > jlab > ellband.m
ellband
ELLBAND  Bandwidth of modulated elliptical signals in two or three dimensions.
   [A,B,C]=ELLBAND(KAPPA,LAMBDA,THETA,PHI) computes the instantaneous
   bandwidth of the elliptical signal characterized by RMS amplitude
   KAPPA, linearity LAMBDA, orientation THETA, and orbital phase PHI.
   The three output arguments are
          A  - Amplitude modulation bandwidth
          B  - Deformation bandwidth
          C  - Precession bandwidth.
   and these satisfy UPSILON^2=A^2+B^2+C^2 where UPSILON is the joint
   instantaneous bandwidth of the bivariate signal.
   The form of these terms is as follows:
         A = 1/KAPPA d/dt KAPPA
         B = 1/2 * 1/SQRT(1-LAMBDA^2) *  d/dt LAMBDA
         C = LAMBDA d/dt THETA
   [A,B,C,UPSILON]=ELLBAND(KAPPA,LAMBDA,THETA,PHI) also returns the total
   instantaneous bandwith UPSILON=SQRT(A^2+B^2+C^2).
   ELLBAND(...,DIM) performs the analysis with time running along
   dimension DIM, as opposed to the default behavior of DIM=1.
   For details see Lilly and Olhede (2010).
   ELLBAND also works if the input arguments are cell arrays of numerical
   arrays, in which case the output will be similarly sized cell arrays.
   __________________________________________________________________
   Three dimensions
   ELLBAND can also compute the instantaneous bandwidth of modulated
   elliptical signals in three dimensions.
   [A,B,C,D,E]=ELLBAND(KAPPA,LAMBDA,THETA,PHI,ALPHA,BETA) returns the
   terms in the bandwidth from a modulated ellipical signal in a plane
   with a normal vector having azimuth angle ALPHA and zenith angle BETA.
   The five output arguments are
          A   - Amplitude modulation bandwidth, as in 2D
          B   - Deformation bandwidth, as in 2D
          C   - Precession bandwidth, as in 2D
          D   - Precession bandwidth with full 3D effects
          E   - Bandwidth due to motion of the normal to the plane
   and these, in principle, satisfy UPSILON^2=A^2+B^2+C^2+D^2+|E|^2 where
   UPSILON is the joint instantaneous bandwidth of the trivariate signal.
   See below for a caveat on this statement.
   Terms A--C are just as in the bivariate case.  The new terms are:
         D = LAMBDA [d/dt THETA + COS(BETA) * d/dt ALPHA]
         E = N^T X_+ / |X_+^H X_+|
   where N is the trivariate normal vector, X_+ is the trivariate analytic
   signal vector, and "T" denotes the matrix transpose, and "H" the
   Hermitian transpose.  Note that term E may be complex-valued.
   Note that term C does not contribute to the full bandwidth, but is
   output in order to compare the two-dimensional and three-dimensional
   effects in the full precession bandwidth, term D.
   An important point is that the trivariate ellipse parameters can be
   ill-defined for a nearly linear signal, and the elliptical bandwidth
   terms can give erroneously large values at isolated points.  To check
   for this, compare with the joint bandwidth from INSTMOM.
   [A,B,C,D,E,UPSILON]=ELLBAND(KAPPA,LAMBDA,THETA,PHI,ALPHA,BETA) also
   returns the total bandwith UPSILON=SQRT(A^2+B^2+C^2+D^2+|E|^2).
   For details see Lilly (2011).
   __________________________________________________________________
   ELLBAND(DT,...) sets the sample interval DT, which defaults to DT=1.
   DT may be a scalar, or if the input fields are cell arrays having
   length N, DT may be a numerical array of length N.
   See also ANATRANS, WAVETRANS, INSTMOM.
   'ellband --t' runs a test.
   'ellband --f' generates a figure from Lilly and Olhede (2010).
   Usage:  [a,b,c]=ellband(kappa,lambda,theta,phi);
           [a,b,c]=ellband(dt,kappa,lambda,theta,phi);
           [a,b,c]=ellband(dt,kappa,lambda,theta,phi,dim);
           [a,b,c,upsilon]=ellband(dt,kappa,lambda,theta,phi,dim);
           [a,b,c,d,e]=ellband(kappa,lambda,theta,phi,alpha,beta);
           [a,b,c,d,e]=ellband(dt,kappa,lambda,theta,phi,alpha,beta);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2006--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
ab2kl AB2KL Converts A and B to ellipse parameters Kappa and Lambda.
allall ALLALL(X)=ALL(X(:))
anatrans ANATRANS Analytic part of signal.
aresame ARESAME Test whether two N-D arrays are the same.
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
frac FRAC Fraction: FRAC(A,B)=A./B
instmom INSTMOM Univariate and multivariate instantaneous moments.
jmat3 JMAT3 3x3 rotation matrix through specified angle.
letterlabels LETTERLABELS For automatically putting letter labels on subplots.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
packfig PACKFIG Squeeze together rows and/or columns of the current figure.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
sleptap SLEPTAP Calculate Slepian tapers.
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
tmat TMAT 2x2 complex grouping matrix. TMAT = [1 i; 1 -i] / SQRT(2)
use USE Copies structure fields into named variables in workspace.
vcolon VCOLON Condenses its arguments, like X(:).
vdiff VDIFF Length-preserving first central difference.
vectmult VECTMULT Matrix multiplication for arrays of vectors.
vempty VEMPTY Initializes multiple variables to empty sets or empty cell arrays.
vfilt VFILT Filtering along rows without change in length.
vindex VINDEX Indexes an N-D array along a specified dimension.
vmean VMEAN Mean over finite elements along a specified dimension.
vrep VREP Replicates an array along a specified dimension.
vsum VSUM Sum over finite elements along a specified dimension.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
wavetrans WAVETRANS Continuous wavelet transform.
xtick XTICK Sets locations of x-axis tick marks.
ytick YTICK Sets locations of y-axis tick marks.
This function is called by:
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
jellipse jEllipse: Analysis of modulated elliptical, or bivariate, signals
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.