Description of ellcurves
Home > jlab > ellcurves.m
ellcurves
ELLCURVES  Returns curves corresponding to specified ellipse properties.
   For direct plotting of ellipses, see ELLPLOT, which calls ELLCURVES.
   Z=ELLCURVES(KAPPA,LAMBDA,THETA,ZO) returns complex-valued curves Z
   tracing out the periphery of ellipses with amplitude KAPPA, linearity
   LAMBDA, and orientation THETA, located at complex positions ZO=XO+iYO.
   All input arguments are arrays of the same length, say N.  By default,
   Z is calculated at 32 locations around the periphery.  Thus Z will be a
   complex-valued matrix with 32 rows and N columns.
   ELLCURVES(KAPPA,LAMBDA,THETA,PHI,Z) with five input arguments begins
   each ellipse at phase PHI.  For most applications, the starting phase
   does not matter.  The default value is to begin with a phase of zero.
   ELLCURVES(... ,'npoints',M) uses M points around the ellipse periphery.
   ELLCURVES(... ,'aspect',AR) with AR=[XAR YAR] multiplies the X-signal
   and Y-signal by XAR and YAR, respectively, for plotting purposes.
   ELLCURVES is called by ELLPLOT, and is also useful in applications,
   e.g. analysis of model fields within elliptical contours.
   The curves can be plotted with PLOT(Z).
   See also ELLIPSEPLOT, ELLSIG, INELLIPSE.
   Usage: z=ellcurves(kappa,lambda,theta,zo);
          z=ellcurves(kappa,lambda,theta,phi,zo);
          z=ellcurves(kappa,lambda,theta,phi,zo,'npoints',64);
          z=ellcurves(kappa,lambda,theta,phi,zo,'aspect',ar,'npoints',64);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2014--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
This function is called by:
ellipseplot ELLIPSEPLOT Plot ellipses.
jellipse jEllipse: Analysis of modulated elliptical, or bivariate, signals