Description of elldiff
Home > jlab > elldiff.m
elldiff
ELLDIFF  Differentiation of modulated elliptical signals.
   Given the properties of a time-varying elliptical signal, ELLDIFF
   finds the ellipse properties of the time derivative of that signal.
   [K2,L2,TH2,PHI2]=ELLDIFF(K,L,TH,PHI) where the input arguments
   specify a time-varying ellipse of the complex-valued time series
   Z=X+iY, returns the ellipse parameters for the associated time-
   varing ellipse of the first central difference of Z.
   K and L are the input ellipse amplitude and linearity, respectively,
   while TH and PHI are its orientation and orbital phase.  The output
   arguments are the same parameters for the differentiated ellipse.
   [...]=ELLDIFF(DT,...) optionally specifies a time-step of DT
   (default=1) for the differentiation.
   [...]=ELLDIFF(...,FACT) optionally multiplies the output amplitudes
   by the scale factor FACT (default=1), e.g. for a unit conversion from
   kilometers into centimeters.
   See also ELLPARAMS.
   Usage:  [k2,l2,theta2,phi2]=elldiff(k,l,theta,phi);
           [k2,l2,theta2,phi2]=elldiff(4*3600,k,l,theta,phi,1e5);
   'elldiff --t' runs a test
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2005--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
ab2kl AB2KL Converts A and B to ellipse parameters Kappa and Lambda.
aresame ARESAME Test whether two N-D arrays are the same.
elldiff ELLDIFF Differentiation of modulated elliptical signals.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
frac FRAC Fraction: FRAC(A,B)=A./B
imlog IMLOG Imaginary part of log: IMLOG(X)=UNWRAP(IMAG(LOG(X)))
kl2ab KL2AB Converts ellipse parameters Kappa and Lambda to A and B.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
vdiff VDIFF Length-preserving first central difference.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
This function is called by:
elldiff ELLDIFF Differentiation of modulated elliptical signals.
ellvel ELLVEL Average and instantaneous ellipse velocities.
jellipse jEllipse: Analysis of modulated elliptical, or bivariate, signals