Description of ellparams
Home > jlab > ellparams.m
ellparams
ELLPARAMS  Ellipse parameters of a modulated bivariate or trivariate oscillation.
   [KAPPA,LAMBDA,THETA,PHI]=ELLPARAMS(X,Y) where X and Y are analytic
   signals, returns the parameters of the complex-valued signal
   Z=REAL(X)+i REAL(Y), expressed as a modulated ellipse.
   Here KAPPA is the RMS ellipse amplitude, LAMBDA is the linearity,
   THETA is the orientation, and PHI is the instantaneous orbital phase.
   See Lilly and Gascard (2006) and Lilly and Olhede (2010a) for details.
   ELLPARAMS is inverted by ELLSIG, which returns the X and Y signals
   given the ellipse parameters.
   ELLPARAMS(...,DIM) performs the analysis with time running along
   dimension DIM, as opposed to the default behavior of DIM=1.
   __________________________________________________________________
   Trivariate signals
   ELLPARAMS also works for trivariate signals, which can be expressed as
   a modulated ellipse in three dimensions.
   [KAPPA,LAMBDA,THETA,PHI,ALPHA,BETA]=ELLPARAMS(X,Y,Z), where X, Y, and Z
   are all analytic signals, also returns the zenith angle ALPHA and the
   azimuth angle BETA in addition to the other ellipse parameters.
   See Lilly (2010) for details on the trivariate case.
   __________________________________________________________________
   Cell array input / output
   ELLPARAMS also works if the input arguments are cell arrays of numeric
   arrays, in which case the output arguments will also be cell arrays of
   the same size.
   __________________________________________________________________
   Alternate form
   [...]=ELLPARAMS(M) also works, where M is a two-column or three-column
   matrix, i.e. M=[X Y] or M=[X Y Z], for bivariate or trivariate signals,
   respectively.
   __________________________________________________________________
   'ellparams --t' runs a test.
   See also ELLSIG, ELLBAND, ELLDIFF, ELLVEL, ELLRAD, KL2AB, AB2KL.
   Usage: [kappa,lambda,theta,phi]=ellparams(M);
          [kappa,lambda,theta,phi]=ellparams(x,y);
          [kappa,lambda,theta,phi]=ellparams(x,y,dim);
          [kappa,lambda,theta,phi]=ellparams([x,y]);
          [kappa,lambda,theta,phi,alpha,beta]=ellparams(x,y,z);
          [kappa,lambda,theta,phi,alpha,beta]=ellparams([x,y,z]);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2009--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
anatrans ANATRANS Analytic part of signal.
aresame ARESAME Test whether two N-D arrays are the same.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
frac FRAC Fraction: FRAC(A,B)=A./B
imlog IMLOG Imaginary part of log: IMLOG(X)=UNWRAP(IMAG(LOG(X)))
instmom INSTMOM Univariate and multivariate instantaneous moments.
jmat3 JMAT3 3x3 rotation matrix through specified angle.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
use USE Copies structure fields into named variables in workspace.
vdiff VDIFF Length-preserving first central difference.
vectmult VECTMULT Matrix multiplication for arrays of vectors.
vempty VEMPTY Initializes multiple variables to empty sets or empty cell arrays.
vindex VINDEX Indexes an N-D array along a specified dimension.
This function is called by:
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
jellipse jEllipse: Analysis of modulated elliptical, or bivariate, signals
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.