Description of ellrad
Home > jlab > ellrad.m
ellrad
ELLRAD  Average and instantaneous ellipse radius.
   R=ELLRAD(KAPPA,LAMBDA,PHI,STR) where KAPPA and LAMBDA are the amplitude
   and linearity of a time-varying ellise, and PHI is its time-varying
   phase, returns various measures of the ellipse 'radius'.
   STR determines the radius quantity to be output.
       STR       Symbol     Description
       ----------------------------------------------------------------
      'geo'      RM         Geometric mean radius = SQRT(A*B)
      'ave'      RBAR       Period-averaged distance from the origin
      'ins'      RI         Instantaneous distance from the origin
   See Lilly and Gascard (2006) for details.
   If STR is omitted, the geometric mean radius is returned by default.
   RM=ELLRAD(KAPPA,LAMBDA) with PHI omitted also works for computing RM.
   ____________________________________________________________________
   Cell array input/output
   If ELLRAD is given cell array input, it returns cell array output.
   Thus KAPPA, LAMBDA, and PHI may each be cell arrays of the same size,
   where each element in the cell array is a numerical array.
   The output variables will be also cell arrays of this size.
   ____________________________________________________________________
   See also ELLVEL, ELLPARAMS, ELLDIFF.
   Usage:  rm=ellrad(kappa,lambda);
           rbar=ellrad(kappa,lambda,phi,'average');
           ri=ellrad(kappa,lambda,phi,'instantaneous');
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2005--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
ecconv ECCONV Converts between eccentricity measures.
frac FRAC Fraction: FRAC(A,B)=A./B
kl2ab KL2AB Converts ellipse parameters Kappa and Lambda to A and B.
This function is called by:
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
ellvel ELLVEL Average and instantaneous ellipse velocities.
jellipse jEllipse: Analysis of modulated elliptical, or bivariate, signals
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.