Description of ellrossby
Home > jlab > ellrossby.m
ellrossby
ELLROSSBY  Ellipse Rossby number, for oceanographic applications.
   RO=ELLROSSBY(LAT,LAMBDA,OMEGA) returns the ellipse Rossby number RO
   for an ellipse with linearity LAMBDA and joint instantaneous frequency
   OMEGA, in radians per day, at latitude LAT.
   The magnitude of the ellipse Rossby number is |RO|=|OMEGA/F| where F
   is the signed Coriolis frequency at latitude LAT.
   The sign of RO is SIGN(RO)=-SIGN(LAMBDA/F), so that RO is positive for
   cyclones, and negative for anticyclones, in both hemispheres.
   For circular eddies, this definition of Rossby number is equivalent to
   RO=-V/(R*F), where R is the radial distance to the eddy center and V is
   the signed instantaneous azimuthal velocity.
   The input arguments may also be cell arrays of numeric arrays, all
   having the same size.  RO will then be a similarly sized cell array.
   Alternatively, LAMBDA and OMEGA may be cell arrays and LAT a constant.
   'ellrossby --t' runs a test.
   Usage: ro=ellrossby(lat,lambda,omega);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2011--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
corfreq CORFREQ Coriolis frequency in radians per hour.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellrad ELLRAD Average and instantaneous ellipse radius.
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
ellvel ELLVEL Average and instantaneous ellipse velocities.
frac FRAC Fraction: FRAC(A,B)=A./B
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
use USE Copies structure fields into named variables in workspace.
vindex VINDEX Indexes an N-D array along a specified dimension.
vmean VMEAN Mean over finite elements along a specified dimension.
wavetrans WAVETRANS Continuous wavelet transform.
This function is called by:
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
jellipse jEllipse: Analysis of modulated elliptical, or bivariate, signals