Description of ellsig
Home > jlab > ellsig.m
ellsig
ELLSIG  Creates a modulated elliptical signal in two or three dimensions.
   Z=ELLSIG(KAPPA,LAMBDA,THETA,PHI) creates a time-varying, complex-valued
   elliptical signal Z=X+iY characterized by RMS amplitude KAPPA,
   linearity LAMBDA, orientation THETA, and orbital phase PHI.
   [X,Y]=ELLSIG(KAPPA,LAMBDA,THETA,PHI) returns the analytic part of the
   ellipse signal along the X and Y axes.
   See Lilly and Gascard (2006) and Lilly and Olhede (2010a) for details.
   ELLSIG is inverted by ELLPARAMS, which returns the ellipse parameters
   given the analytic signals X and Y.
   ______________________________________________________________________
   Three dimensions
   ELLSIG can also generate an elliptical signal in three dimenions.
   [X,Y,Z]=ELLSIG(KAPPA,LAMBDA,THETA,PHI,ALPHA,BETA) returns the analytic
   part of the ellipse signal along the X, Y, and Z axes.
   Here BETA is the "zenith angle" giving the orientation of the plane
   containing the ellipse with respect to the vertical, while ALPHA is
   the "azimuth angle", the angle the normal to the plane of the ellipse
   makes with the x-axis.
   In the trivariate case, LAMBDA is positive, and the direction of
   rotation of the particle projected onto the X-Y plane is changed by
   letting the zenith angle BETA exceed PI/2.
   See Lilly (2011) for details on the trivariate case.
   __________________________________________________________________
   Cell array input / output
   ELLSIG also works if the input arguments are cell arrays of numeric
   arrays, in which case the output arguments will also be cell arrays of
   the same size.
   ______________________________________________________________________
   [X,Y]=ELLSIG(...,'real') or [X,Y,Z]=ELLSIG(...,'real') takes the real
   part of the output arguments.
   ______________________________________________________________________
   'ellsig --t' runs some tests.
   Usage:  z=ellsig(kappa,lambda,theta,phi);
           [x,y]=ellsig(kappa,lambda,theta,phi);
           [x,y,z]=ellsig(kappa,lambda,theta,phi,alpha,beta);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2013 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
anatrans ANATRANS Analytic part of signal.
aresame ARESAME Test whether two N-D arrays are the same.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
jmat3 JMAT3 3x3 rotation matrix through specified angle.
kl2ab KL2AB Converts ellipse parameters Kappa and Lambda to A and B.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
use USE Copies structure fields into named variables in workspace.
vectmult VECTMULT Matrix multiplication for arrays of vectors.
This function is called by:
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellcurves ELLCURVES Returns curves corresponding to specified ellipse properties.
elldiff ELLDIFF Differentiation of modulated elliptical signals.
ellipseplot ELLIPSEPLOT Plot ellipses.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
ellvel ELLVEL Average and instantaneous ellipse velocities.
jellipse jEllipse: Analysis of modulated elliptical, or bivariate, signals
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.