Description of ellvel
Home > jlab > ellvel.m
ellvel
 ELLVEL  Average and instantaneous ellipse velocities.
   V=ELLVEL(KAPPA,LAMBDA,THETA,PHI,STR) where KAPPA and LAMBDA are the
   amplitude and linearity of a time-varying ellise, THETA is its time-
   varying orientation, and PHI is its time-varying phase, returns various
   measures of the ellispe 'velocity'.
   STR determines the velocity quantity to be output.
       STR       Symbol     Description
       ----------------------------------------------------------------
      'geo'      VM         Geometric mean velocity
      'ave'      VBAR       Period-averaged speed
      'kin'      VEKE       Kinetic energy velocity
      'cir'      VGAMMA     Circulation velocity
      'azi'      VAZ        Instantaneous azimuthal velocity
      'ins'      VI         Instantaneous speed
   All are signed quantities reflecting the direction of motion.  That is,
   a velocity is defined to be positive when the ellipse is orbited in the
   mathematically positive (counterclockwise) sense, and negative when the
   ellipse is orbited in the mathematically negative sense.
   VM=ELLVEL(KAPPA,LAMBDA,THETA,PHI) with STR omitted returns VM, the
   geometric mean velocity.  This is a basic of ellipse velocity that is
   analagous to the geometric mean radius as a measure of ellipse size.
   ELLVEL(DT,...,) optionally uses DT as the data sample rate, with a
   default value of DT=1.  DT is a scalar.
   ELLVEL(DT,...,FACT,STR) optionally converts the physical units of
   velocity through a multiplication by FACT, with a default value of
   FACT=1.  For example, FACT=1e5 converts kilometers into centimeters,
   while FACT=1e5/24/3600 converts km/day into cm/sec.
   ____________________________________________________________________
   Cell array input/output
   If ELLVEL is given cell array input, it returns cell array output.
   Thus KAPPA, LAMBDA, THETA, and PHI may each be cell arrays of the
   same size, where each element in the cell array is a numerical array.
   VM and other velocity measures will be also cell arrays of this size.
   In this case ELLVEL(DT,...) also works with DT a scalar or an
   array whose length is the number of elements in the cell arrays.
   ____________________________________________________________________
   See also ELLRAD, ELLPARAMS, ELLDIFF.
   Usage:  v=ellvel(kappa,lambda,theta,phi);
           v=ellvel(dt,kappa,lambda,theta,phi,1e5);
           vbar=ellvel(kappa,lambda,theta,phi,'ave');
   'ellvel --f' generates a sample figure.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2005--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
elldiff ELLDIFF Differentiation of modulated elliptical signals.
ellrad ELLRAD Average and instantaneous ellipse radius.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
ellvel ELLVEL Average and instantaneous ellipse velocities.
fixlabels FIXLABELS Specify precision of axes labels.
fontsize FONTSIZE Rapidly set title, axes, label, and text fontsizes.
frac FRAC Fraction: FRAC(A,B)=A./B
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
vdiff VDIFF Length-preserving first central difference.
vlines VLINES Add vertical lines to a plot.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
xtick XTICK Sets locations of x-axis tick marks.
ytick YTICK Sets locations of y-axis tick marks.
This function is called by:
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
ellvel ELLVEL Average and instantaneous ellipse velocities.
jellipse jEllipse: Analysis of modulated elliptical, or bivariate, signals
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.