Description of findpath
Home > jlab > findpath.m
findpath
FINDPATH  Returns the full pathname of a directory on the Matlab search path.
   FINDPATH(DIRNAME) returns the full pathname of directory DIRNAME,
   provided DIRNAME is on the Matlab search path.
   For example, 'findpath jlab' on a Mac might return
            '/Users/lilly/Desktop/DropBox/Matlab/jlab'.
   FINDPATH returns the empty string if DIRNAME is not found.
   Usage: findpath('dirname');
          findpath dirname
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
about_floats FLOATS Historical dataset of eddy-resolving subsurface floats.
commentlines COMMENTLINES Returns the comment lines from m-files.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_allhelp JLAB_ALLHELP Displays the help comments for all JLAB modules.
matsave MATSAVE Create and save structure of variables as a mat-file.