Description of fixlabels
Home > jlab > fixlabels.m
fixlabels
FIXLABELS  Specify precision of axes labels.
   FIXLABELS(PREC) rewrites the X and Y axis labels of the current axes tp
   precision PREC.  PREC denotes the tenths place of the highest-precision
   digit, so PREC=-2 includes the hundredths place.
   Unlike standard matlab labelling, FIXLABELS uses zeros instead of blank
   spaces to the right of the decimal point.
   FIXLABELS([XPREC,YPREC]) uses different precision for the X and Y axes.
   FIXLABELS(H,PREC) rewrites the labels of axes H.  H may also be a
   vector of axes handles, in which case PREC may either be a scalar or a
   vector PREC=[X1PREC Y1PREC X2PREC ...] .
   FIXLABELS with no arguments rewrites all X and Y axis labels of the
   current figure to the default (current) precision for that axis, but
   using zeros instead of blank spaces to the right of the decimal point.
   Note: make sure the tickmarks are where you want them in the hardcopy
   before calling FIXLABELS (since it sets the 'TICKMODE' and
   'TICKLABELMODE' properties to 'MANUAL').
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 1999--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
fixlabels FIXLABELS Specify precision of axes labels.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
xtick XTICK Sets locations of x-axis tick marks.
ytick YTICK Sets locations of y-axis tick marks.
ztick ZTICK Sets locations of z-axis tick marks.
This function is called by:
ecconv ECCONV Converts between eccentricity measures.
ellvel ELLVEL Average and instantaneous ellipse velocities.
fixlabels FIXLABELS Specify precision of axes labels.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
wigdist WIGDIST Wigner distribtion (alias-free algorithm).