Description of flipx
Home > jlab > flipx.m
flipx
 FLIPX    Flips the direction of the x-axis
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2002, 2004 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
axeshandles AXESHANDLES Returns handles to all axes children.
This function is called by:
jgraph jGraph: Plotting tools and refinements for making high-quality figures
twospecplot TWOSPECPLOT Plots a pair of rotary or Cartesian spectra.