Description of flipmap
Home > jlab > flipmap.m
flipmap
FLIPMAP Flips the current colormap upside-down.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2002, 2004 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
makefigs_topoplot
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
topoplot TOPOPLOT Plot regional or global topography at one-sixth degree resolution.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).