Description of flipy
Home > jlab > flipy.m
flipy
 FLIPY    Flips the direction of the y-axis
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2002, 2004 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
axeshandles AXESHANDLES Returns handles to all axes children.
This function is called by:
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.