Description of fontsize
Home > jlab > fontsize.m
fontsize
FONTSIZE Rapidly set title, axes, label, and text fontsizes.
   FONTSIZE(TITLES, LABEL, AXES, TEXT) sets the fontsizes of all titles,
   x/y/z labels, axes, and text objects in the current figure to the
   specified values.  To avoid changing a fontsize, use the empty set, as
   in FONTSIZE(14,[],12).
   FONTSIZE('NAME'), where NAME refers to a  predetermined set of font
   sizes, also works.  Type FONTSIZE with no arguments to see a list of
   available fontsize sets.
   When the input arguments are numbers (not named variables) or a string
   referring to a fontsize set, parenthesis may be omitted.  For instance:
        FONTSIZE 14 12 12 10
        FONTSIZE DEFAULT
   Additional named fontsize sets may be created by the user, as described
   in JLAB_SETTINGS.
   See also LINESTYLE, LINERING.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
ecconv ECCONV Converts between eccentricity measures.
ellvel ELLVEL Average and instantaneous ellipse velocities.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
makefigs_topoplot
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
regionplot REGIONPLOT Plots a simple box indicating a latitude / longitude region.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.