Description of fourier
Home > jlab > fourier.m
fourier
FOURIER  The one-sided Fourier frequencies for a given length time series.
   F=FOURIER(N) returns the one-sided (or positive) Fourier frequencies
   for a time series of length N.
   F is a radian or angular frequency so that the Nyquist is at PI.
   F=FOURIER(DT,N) uses sample rate DT in calculating the frequencies, so
   that the Nyquist will be at PI/DT.
   Note that the highest resolved frequency, MAX(F), differs for even or
   odd N.  For even N, it is the Nyquist PI/DT, but for odd N the Nyquist
   is not resolved and the highest resolved frequency is (N-1)/N * PI/DT.
   F has length FLOOR(N/2)+1, or N/2+1 for even N, and (N+1)/2 for odd N.
   See also CENTEREDTIMES.
   Usage: f=fourier(N);
          f=fourier(dt,N);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2011--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
fourier FOURIER The one-sided Fourier frequencies for a given length time series.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
blurspec BLURSPEC Returns the blurred and aliased spectrum given the autocovariance.
fourier FOURIER The one-sided Fourier frequencies for a given length time series.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jspectral jSpectral: Multitaper spectral analysis, and other time series tools
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
mspec MSPEC Multitaper power and cross spectra.