Description of frac
Home > jlab > frac.m
frac
FRAC  Fraction: FRAC(A,B)=A./B
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
ab2kl AB2KL Converts A and B to ellipse parameters Kappa and Lambda.
anatrans ANATRANS Analytic part of signal.
blurspec BLURSPEC Returns the blurred and aliased spectrum given the autocovariance.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curveinterp CURVEINTERP Interpolate a field or its gradient onto a set of curves.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
dawson DAWSON The Dawson function. [By P.J. Acklam]
divgeom DIVGEOM Geometric decomposition of eddy vorticity flux divergence.
ecconv ECCONV Converts between eccentricity measures.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
elldiff ELLDIFF Differentiation of modulated elliptical signals.
ellipseplot ELLIPSEPLOT Plot ellipses.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellrad ELLRAD Average and instantaneous ellipse radius.
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
ellvel ELLVEL Average and instantaneous ellipse velocities.
hermfun HERMFUN Orthonormal Hermite functions. [with F. Rekibi]
inellipse INELLIPSE Locates points on the interior of ellipses.
instmom INSTMOM Univariate and multivariate instantaneous moments.
isridgepoint ISRIDGEPOINT Finds wavelet ridge points using one of several criterion.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
latratio LATRATIO Set plot aspect ratio for latitude / longitude plot.
linecolor LINECOLOR Set line colors based on a property value within a colormap.
lininterp LININTERP Fast linear interpolation for arbitrary-sized arrays.
lonshift LONSHIFT Shifts longitude origin for plotting purposes.
maternc MATERNC Returns the normalization function C_ALPHA for a Matern process.
maternchol MATERNCHOL Cholesky decomposition of the Matern covariance matrix.
maternedge MATERNEDGE Long-time cutoff edge for the Matern impulse response function.
maternfun MATERNFUN Returns the Matern function.
maternimp MATERNIMP Impulse response function for the Matern random process.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
mom2cum MOM2CUM Convert moments to cumulants.
morlfreq MORLFREQ Compute Morlet wavelet carrier frequency given peak frequency.
morlwave MORLWAVE Morlet wavelet.
morsea MORSEA Returns the generalized Morse wavelet amplitude "a".
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
morseproj MORSEPROJ Projection coefficient for two generalized Morse wavelets.
morseprops MORSEPROPS Properties of the demodulated generalized Morse wavelets.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
morsexpand MORSEXPAND Generalized Morse wavelets via time-domain Taylor series.
mspec MSPEC Multitaper power and cross spectra.
msvd MSVD Singular value decomposition for polarization analysis.
packfig PACKFIG Squeeze together rows and/or columns of the current figure.
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
periodindex PERIODINDEX Returns time index in increments of instantaneous period.
polparams POLPARAM Spectral matrix polarization parameters.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
quadinterp QUADINTERP Fast quadratic interpolation for arbitrary-sized arrays.
ridgechains RIDGECHAINS Forms ridge curves by connecting transform ridge points.
ridgeinterp RIDGEINTERP Interpolate quantity values onto ridge locations.
ridgelen RIDGELEN Wavelet ridge length expressed as number of full cycles.
sig2latlon SIG2LATLON Converts an oscillatory signal to lat/lon displacements.
simplepdf SIMPLEPDF Gaussian, uniform, Cauchy, and exponential pdfs.
sleptap SLEPTAP Calculate Slepian tapers.
specdiag SPECDIAG Diagonalize a 2 x 2 spectral matrix.
spherecurl SPHERECURL Curl of a vector field on the surface of a sphere.
spheredist SPHEREDIST Computes great circle distances on a sphere.
spherediv SPHEREDIV Divergence of a vector field on the surface of a sphere.
spheregrad SPHEREGRAD Gradient of a field on the surface of a sphere.
spherelap SPHERELAP Laplacian of a field on the surface of a sphere.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
tmat TMAT 2x2 complex grouping matrix. TMAT = [1 i; 1 -i] / SQRT(2)
trajchunk TRAJCHUNK Converts Lagrangian trajectories into chunks based on the Coriolis period.
trajunwrap TRAJUNWRAP Unwraps Lagrangian trajectories from a periodic domain.
trajwrap TRAJWRAP Wraps Lagrangian trajectories to fit within a periodic domain.
uv2latlon UV2LATLON Integrates horizontal velocity to give latitude and longitude.
vfilt VFILT Filtering along rows without change in length.
vmean VMEAN Mean over finite elements along a specified dimension.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).
xy2latlon XY2LATLON Converts local Cartesian coordinates into latitude and longitude.