Description of hermfun
Home > jlab > hermfun.m
hermfun
HERMFUN  Orthonormal Hermite functions. [with F. Rekibi]
   H=HERMFUN(T,N) generates the fisrt N+1 orthonormal Hermite functions
   [H0,...HN] on a time axis specfied by the column vector T.
   HERMFUN uses the expression of Simons et al. 2003.
   Note that H(:,1) is the zeroth-order Hermite function, which is equal
   to a Gaussian.  H(:,2) is the first-order function, and so forth.
   See also HERMPOLY.
   'hermfun --f' generates a sample figure; compare with the Hermite
   function figure at
     http://en.wikipedia.org/wiki/Hermite_polynomials#Definition
   Usage:  h=hermfun(t,n);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 F. Rekibi and J. M. Lilly
                         --- type 'help jlab_license' for details
This function calls:
frac FRAC Fraction: FRAC(A,B)=A./B
hermfun HERMFUN Orthonormal Hermite functions. [with F. Rekibi]
hermpoly HERMPOLY Hermite polynomials. [with F. Rekibi]
This function is called by:
hermfun HERMFUN Orthonormal Hermite functions. [with F. Rekibi]
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
slidetrans SLIDETRANS Sliding-window ('moving-window') Fourier transform.