Description of hermpoly
Home > jlab > hermpoly.m
hermpoly
 HERMPOLY  Hermite polynomials. [with F. Rekibi]
   H=HERMPOLY(T,N) generates the first N+1 orthonormal Hermite polynomials
   [H0,...HN] on a time axis specfied by the column vector T.
   In the nomenclature of Wikipedia,
      http://en.wikipedia.org/wiki/Hermite_polynomials#Definition
   the polynomials returned by HERMPOLY are the "physicists'" definition.
   Note that H(:,1) is the zeroth-order Hermite polynomial, which is equal
   to one.  H(:,2) is the first-order polynomial, and so forth.
   See also HERMFUN, HERMEIG.
   'hermpoly --t' runs a test.
   Usage:  h=hermpoly(t,n);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 F. Rekibi and J. M. Lilly
                         --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
hermpoly HERMPOLY Hermite polynomials. [with F. Rekibi]
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
dawsonderiv DAWSONDERIV Derivatives of the Dawson function.
hermfun HERMFUN Orthonormal Hermite functions. [with F. Rekibi]
hermpoly HERMPOLY Hermite polynomials. [with F. Rekibi]
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).