Description of hlines
Home > jlab > hlines.m
hlines
HLINES   Add horizontal lines to a plot.
   HLINES(Y,STYLE) puts horizontal lines at locations Y having style
   described by the string STYLE.  HLINES draws the lines to fit the
   current axis.
   The SYTLE strings follow the format specified in LINESTYLE.  Thus
   STYLE='2b--' draws blue dotted lines of width 2.
   HLINES(Y) uses the default STYLE='g--', a green dashed line.
   H=HLINES(...) returns an array of handles H to the lines.
   See also VLINES, DLINES.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2008 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
This function is called by:
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
makefigs_topoplot
morlfreq MORLFREQ Compute Morlet wavelet carrier frequency given peak frequency.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
periodize PERIODIZE Returns a doubly periodic version of an input array.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
slidetrans SLIDETRANS Sliding-window ('moving-window') Fourier transform.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).