Description of hodograph
Home > jlab > hodograph.m
hodograph
HODOGRAPH   Generate hodograph plots (simple and fancy).
   A hodograph of a velocity time series is defined as a polar
   coordinate plot of the eastward component versus the northward.
   Simple hodographs:
     HODOGRAPH(U,V) generates a simple hodograph plotting U versus V.
     U and V are column vectors, or matrices with time oriented in
     columns.
     HODOGRAPH(CV), where CV=U+iV, also works.
   Fancy hodographs:
     A fancy hodograph use SCATTER to plot change the color and/or
     sizes of the points according to another parameter, say density.
     A colorbar is also plotted.
     HODOGRAPH(U,V,C) uses C as the symbol color.  The array C must
     have the same size as U and V.
     HODOGRAPH(U,V,C,S) also uses S as the symbol size.  The array S
     must have the same size as U and V.
     HODOGRAPH(CV,C) and HODOGRAPH(CV,C,S) also work.
     Note that since SCATTER is slow for large datasets, it is useful
     to decimate the data before plotting.  This is accomplished
     using HODOGRAPH(...,INDEX). Then only the points CV(INDEX,:) are
     plotted.
     [H,HC]=FHODOGRAPH(...) returns the handle H to the data, and the
     handle HC to the colorbar axis.
   As an example,
          load bravo94
          cv=vfilt(bravo.rcm.cv(:,3),24);
          th=100*detrend(bravo.cat.th(:,3));
          [h,hc]=hodograph(cv,th,20+0*th,[1:4000]);
          caxis([-8 8])
   makes Figure 6a of Lilly and Rhines (2002) JPO.
   Usage: hodograph(cv);
          [h,hc]=hodograph(cv,c,index);
          [h,hc]=hodograph(cv,c,s,index);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2012 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
vcolon VCOLON Condenses its arguments, like X(:).
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
This function is called by:
jgraph jGraph: Plotting tools and refinements for making high-quality figures
joceans jOceans: Oceanography-specific data and model analysis tools