Description of imlog
Home > jlab > imlog.m
imlog
IMLOG  Imaginary part of log: IMLOG(X)=UNWRAP(IMAG(LOG(X)))
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2006--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
elldiff ELLDIFF Differentiation of modulated elliptical signals.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
xyz2latlon XYZ2LATLON Converts 3D Cartesian coordinates into latitude and longitude.