Description of inellipse
Home > jlab > inellipse.m
inellipse
INELLIPSE  Locates points on the interior of ellipses.
   INELLIPSE(Z,KAPPA,LAMBDA,THETA,ZO) where Z is a complex-valued
   location Z=X+iY, and KAPPA, LAMBDA, THETA describe an ellipse at
   complex-valued position ZO=XO+iYO, is true if Z is inside the ellipse.
   KAPPA is the ellipse amplitude, LAMBDA is the linearity, and THETA is
   the orientation of the major axis with respect to the X-axis.
   KAPPA and LAMBDA are related to the semi-axis lengths A and B by
   KAPPA^2=(A^2+B^2)/2 and LAMBDA=(A^2-B^2)/(A^2+B^2).  For details, see
   Lilly and Gascard (2006).
   __________________________________________________________________
   Array or matrix input
   BOOL=INELLIPSE(Z,KAPPA,LAMBDA,THETA,ZO), where Z is a length M *row*
   vector, and the other input variables are length N *row* vector,
   returns an M x N boolean matrix BOOL.
   In this case the (m,n)th entry of BOOL is true if the mth location Z
   is inside the mth ellipse.
   If the input variables have the same number of multiple *rows*, say K,
   this is interpreted as corresponding to K different time.  In this case
   BOOL will be a 3D array with dimensions M x N x K.
   __________________________________________________________________
   See also ELLCURVES, ELLIPSEPLOT.
   'inellipse --f' generates sample figure.
   Usage: bool=inellipse(z,kappa,lambda,theta,zo);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
ellipseplot ELLIPSEPLOT Plot ellipses.
frac FRAC Fraction: FRAC(A,B)=A./B
inellipse INELLIPSE Locates points on the interior of ellipses.
kl2ab KL2AB Converts ellipse parameters Kappa and Lambda to A and B.
vrep VREP Replicates an array along a specified dimension.
vsize VSIZE Returns the sizes of multiple arguments.
This function is called by:
inellipse INELLIPSE Locates points on the interior of ellipses.
joceans jOceans: Oceanography-specific data and model analysis tools