Description of inregion
Home > jlab > inregion.m
inregion
 INREGION  Tests whether lat/lon points lie within a specified box.
   BOOL = INREGION(REGION,LAT,LON), where LAT and LON are arrays having
   the same size, returns an array BOOL which is true (=1) for all
   LAT/LON pairs which lie inside REGION, and false (=0) otherwise.
   REGION is an array with the format [WEST EAST SOUTH NORTH]. Longitudes
   may either be specified on the interval [-180, 180] or on [0, 360].
   The region may overlap the prime meridian (LON=0) or the dateline
   (LON=180).  Region boundaries are interpreted to exclude the poles.
   ______________________________________________________________________
   Cell array lat/lon input
   INREGION also works if LAT and LON are cell arrays.
   In this case, BOOL is also a cell array, with the Kth element of BOOL,
   BOOL{K}, being a boolean array of the same size as LAT{K} and LON{K}.
   ______________________________________________________________________
   Multiple boxes
   INREGION can detect if points are within any of several boxes.  To do
   so, just make REGION a cell array, REGION={R1,R2,...,RN} where the RN
   are numeric arrays, each with the format [WEST EAST SOUTH NORTH].
   In this way one can build up a more general region from the union of
   several rectangular regions.
   ______________________________________________________________________
   See also REGIONPLOT, FLOATREGION, INELLIPSE.
   'inregion --t' runs a test.
   Usage:  bool=inregion(region,lat,lon);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2006--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
deg180 DEG180 Converts degrees to the range [-180,180].
inregion INREGION Tests whether lat/lon points lie within a specified box.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
use USE Copies structure fields into named variables in workspace.
This function is called by:
inregion INREGION Tests whether lat/lon points lie within a specified box.
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
readtopo READTOPO Read one-minute topography data from Smith and Sandwell.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.