Description of instmom
Home > jlab > instmom.m
instmom
INSTMOM  Univariate and multivariate instantaneous moments.
   [A,OMEGA,UPSILON]=INSTMOM(X), where X is an analytic signal, computes
   the amplitude A, instantaneous *radian* frequency OMEGA, and
   instantaneous bandwidth assuming a unit sample rate.
   X is an array with the first dimension being "time".  Thus, X can be a
   matrix of analytic signals oriented as column vectors, or a 2- or 3-D
   wavelet transform such as output by WAVETRANS.
   The output arrays are the same size as X.
   The instantaneous frequency, bandwidth, and curvature are defined as
            A    = abs X
          OMEGA  = d/dt Im ln X = d/dt arg X
         UPSILON = d/dt Re ln X = d/dt ln abs X
   where i=SQRT(-1) as usual.
   INSTMOM(X,DIM) computes the moments along dimension DIM, instead of
   the default of computing the moments along the rows (DIM=1).
   For details, see
       Lilly & Olhede (2010), "Bivariate instantaneous frequency and
            bandwidth", IEEE Trans. Sig. Proc., 58 (2), 591--603.
   _____________________________________________________________________
   Sample interval
   INSTMOM(DT,...) uses sample interval DT, where DT is a scalar, for
   computing time derivatives.  DT=1 is the default.
   _____________________________________________________________________
   Joint instantaneous moments
   INSTMOM can also calculate the joint instananeous moments of
   multivariate signals, as defined in Lilly and Olhede (2010).
   [JA,JOMEGA,JUPSILON]=INSTMOM(X1,X2,...,XN,DIM) returns the *joint*
   instantaneous moments calculated across the N signals X1,X2,... XN,
   based on the univariate instantaneous moments along dimension DIM.
   The joint instantaneous amplitude JA is the root-mean-square of the
   component amplitudes across dimension JDIM, while JOMEGA is power-
   weighted average of the component instantaneous frequencies.
   For details and for the definition of the joint instantaneous bandwidth
   JUPSILON, see Lilly and Olhede (2010).
   [JA,JOMEGA,JUPSILON]=INSTMOM(X,DIM,JDIM) also works, where the joint
   instantaneous moments are calculated across dimensions JDIM of X.
   The joint instantaneous moments JA, JOMEGA, and JUPSILON then have the
   same size as X, except along dimension JDIM where they have only one
   entry.  Note that DIM is no longer optional when JDIM is used.
   _____________________________________________________________________
   Instantaneous curvature
   INSTMOM can also return the next-higher order instantaneous moment,
   which is more rarely encountered.
   [A,OMEGA,UPSILON,XI]=INSTMOM(X) returns the instantaneous curvature XI,
   defined as
            XI   = d^2/dt^2 abs X / abs X + i d^2/dt^2 arg X
                 = UPSILON^2 + d/dt UPSILON + i d/dt OMEGA
   Similarly [JA,JOMEGA,JUPSILON,JXI]=INSTMOM(X,DIM,JDIM) returns the
   joint instantaneous curvature JXI for the multivariate signal X.
   For details on the univariate and joint instantaneous curvature, see
       Lilly and Olhede (2012a), "Analysis of modulated multivariate
            oscillations", IEEE Trans. Sig. Proc., 60 (2), 600--612.
   _____________________________________________________________________
   Boundary conditions
   The first and last points must be treated differently, as the central
   difference is not defined there.  Three different methods can be used.
   INSTMOM(...,STR) specifies the method: STR= 'endpoint' (the default),
   'periodic', or 'nans'.  See VDIFF for details.
   _____________________________________________________________________
   'instmom --f' generates some sample figures.
   Usage: [a,om]=instmom(x);
          [a,om,up,xi]=instmom(dt,x);
          [a,om,up,xi]=instmom(dt,x,dim);
          [a,om,up,xi]=instmom(dt,x1,x2,x3,x4,dim);
          [a,om,up,xi]=instmom(dt,x,dim,jdim);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
anatrans ANATRANS Analytic part of signal.
aresame ARESAME Test whether two N-D arrays are the same.
bellpoly BELLPOLY Complete Bell polynomials.
fixlabels FIXLABELS Specify precision of axes labels.
frac FRAC Fraction: FRAC(A,B)=A./B
hlines HLINES Add horizontal lines to a plot.
instmom INSTMOM Univariate and multivariate instantaneous moments.
letterlabels LETTERLABELS For automatically putting letter labels on subplots.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
lnsd LNSD Last non-singleton dimension of an array.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
morsexpand MORSEXPAND Generalized Morse wavelets via time-domain Taylor series.
packfig PACKFIG Squeeze together rows and/or columns of the current figure.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
use USE Copies structure fields into named variables in workspace.
uvplot UVPLOT Plots the real and imaginary parts of a signal on the same axis.
vdiff VDIFF Length-preserving first central difference.
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
vlines VLINES Add vertical lines to a plot.
vmean VMEAN Mean over finite elements along a specified dimension.
vrep VREP Replicates an array along a specified dimension.
xtick XTICK Sets locations of x-axis tick marks.
ytick YTICK Sets locations of y-axis tick marks.
This function is called by:
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
instmom INSTMOM Univariate and multivariate instantaneous moments.
isridgepoint ISRIDGEPOINT Finds wavelet ridge points using one of several criterion.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jridges jRidges: Wavelet ridge analysis of modulated oscillatory signals
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.