Description of iseven
Home > jlab > iseven.m
iseven
ISEVEN  True for even integer values; false otherwise.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2001--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
isodd ISODD True for odd integer values; false otherwise.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
twodmed TWODMED Median value of a function of two variables.
vdiff VDIFF Length-preserving first central difference.
vfilt VFILT Filtering along rows without change in length.
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
wavetrans WAVETRANS Continuous wavelet transform.