Description of isodd
Home > jlab > isodd.m
isodd
ISODD  True for odd integer values; false otherwise.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2002--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
iseven ISEVEN True for even integer values; false otherwise.
This function is called by:
doublen DOUBLEN Interpolates a time series to double its length.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
twodmed TWODMED Median value of a function of two variables.
vmedian VMEDIAN Median over finite elements along a specified dimension.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).