Description of isridgepoint
Home > jlab > isridgepoint.m
isridgepoint
ISRIDGEPOINT  Finds wavelet ridge points using one of several criterion.
   ISRIDGEPOINT is a low-level function called by RIDGEWALK.
   BOOL=ISRIDGEPOINT(W,FS,CHI,STR) where W is a wavelet transform matrix
   at *radian* frequecies FS, finds all ridge points of W with amplitudes
   |W| exceeding the amplitude cutoff A.  Several different different
   ridge defintions may be used and are specified by STR.
   BOOL is a matrix of the same size as W, which is equal to one for
   those elements of W which are ridge points, and zero otherwise.
   STR may be either of the following:
        'phase'       Rate of transform change of phase definition
        'amplitude'   Maxima of transfom amplitude definition
   For all definitions, ISRIDGEPOINT rejects spurious ridge points.
   These tend to occur on the flanks of interesting signals, and
   reflect the wavelet structure rather than the signal structure.
   A ridge point is considered spurious if either it is located at an
   amplitude minima, or if the frequency anomaly (transform frequency
   minus scale frequency) is a maximum.
   See also RIDGEQUANTITY, RIDGEWALK.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2006--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
frac FRAC Fraction: FRAC(A,B)=A./B
instmom INSTMOM Univariate and multivariate instantaneous moments.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
vrep VREP Replicates an array along a specified dimension.
This function is called by:
jridges jRidges: Wavelet ridge analysis of modulated oscillatory signals
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.