Description of jcell
Home > jlab > jcell.m
jcell
 jCell:  Tools for operating on cell arrays of column vectors
 Basic mathematical operations
   cellabs    - Absolute value of each element in a cell array.
   cellmax    - Maximum of each element in a cell array.
   cellmin    - Minimum of each element in a cell array.
   cellmean   - Mean value of each element a cell array or set of cell arrays.
   cellreal   - Real part of each element in a cell array.
   cellimag   - Imaginary part of each element in a cell array.
   celllog10  - Base ten logarithm of each element in a cell array.
   celladd    - Addition acting on each element in a cell array.
   cellmult   - Multiplication acting on each element in a cell array.
 Reshaping, indexing, and sizes
   cell2col   - Converts cell arrays of column vectors into 'column-appended' data.
   col2cell   - Converts 'column-appended' data into cell arrays of column vectors.
   cellindex  - Applies a cell array of indices to a cell array of column vectors.
   cellchunk  - Converts cell array data into uniform length 'chunks'.
   cellength  - Length of each element in a cell array.
   cellsize   - Size of each element in a cell array along specified dimension.
 Plotting
   cellplot   - Rapidly plot all element of a cell array of numeric arrays.
 See also jVarfun.
This function calls:
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
cellabs CELLABS Absolute value of each element in a cell array.
celladd CELLADD Addition acting on each element in a cell array.
cellchunk CELLCHUNK Converts cell array data into uniform length 'chunks'.
cellength CELLENGTH Length of each element in a cell array.
cellimag CELLIMAG Imaginary part of each element in a cell array.
cellindex CELLINDEX Applies a cell array of indices to a cell array of column vectors.
celllog10 CELLLOG10 Base ten logarithm of each element in a cell array.
cellmax CELLMAX Maximum of each element in a cell array.
cellmean CELLMEAN Mean value of each element a cell array or set of cell arrays.
cellmin CELLMIN Minimum of each element in a cell array.
cellmult CELLMULT Multiplication acting on each element in a cell array.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
cellreal CELLREAL Real part of each element in a cell array.
cellsize CELLSIZE Size of each element in a cell array along specified dimension.
col2cell COL2CELL Converts 'column-appended' data into cell arrays of column vectors.
This function is called by:
Contents jLab v1.5 by J. M. Lilly