Description of jcommon
Home > jlab > jcommon.m
jcommon
 jCommon:  Useful general-purpose functions, common to other JLAB modules
 Array functions
   aresame    - Test whether two N-D arrays are the same.
   arrayify   - Converts a set of scalars or arrays into column arrays.
   blocklen   - Counts the lengths of 'blocks' in an array.
   blocknum   - Numbers the contiguous blocks of an array.
   lnsd       - Last non-singleton dimension of an array.
   matmult    - Matrix multiplication for arrays of matrices.
   nonnan     - Return all non-NAN elements of an array.
   vectmult   - Matrix multiplication for arrays of vectors.
 File and directory tools
   commentlines - Returns the comment lines from m-files.
   findfiles    - Returns all files in a directory with a specified extension.
   findpath     - Returns the full pathname of a directory on the Matlab search path.
   jhelp        - Opens linked JLAB help files in Matlab's internal web browser.
   whichdir     - Returns directory name containing file in search path.
 Mathematical aliases
   choose     - Binomial coefficient: CHOOSE(N,K) = "N choose K"
   frac       - Fraction: FRAC(A,B)=A./B
   imlog      - Imaginary part of log: IMLOG(X)=UNWRAP(IMAG(LOG(X)))
   iseven     - True for even integer values; false otherwise.
   isodd      - True for odd integer values; false otherwise.
   oprod      - Outer product:  OPROD(X,Y)=X*CONJ(Y')
   res        - Residual after flooring:  RES(X)=X-FLOOR(X)
   rot        - Complex-valued rotation:  ROT(X)=EXP(SQRT(-1)*X)
   squared    - Squares the modulus of its argument:  SQUARED(X)=ABS(X).^2
 Matrices, polynomials, and special functions
   jmat       - 2x2 rotation matrix through specified angle.
   jmat3      - 3x3 rotation matrix through specified angle.
   tmat       - 2x2 complex grouping matrix.  TMAT = [1  i; 1 -i] / SQRT(2)
   bellpoly   - Complete Bell polynomials.
   hermpoly   - Hermite polynomials. [with F. Rekibi]
   hermfun    - Orthonormal Hermite functions. [with F. Rekibi]
 Dataset organization as structures
   make       - Create a structure containing named variables as fields.
   matsave    - Create and save structure of variables as a mat-file.
   use        - Copies structure fields into named variables in workspace.
 Statistics
   cum2mom    - Convert cumulants to moments.
   mom2cum    - Convert moments to cumulants.
   pdfprops   - Mean and variance associated with a probability distribution.
   simplepdf  - Gaussian, uniform, Cauchy, and exponential pdfs.
 Filling bad data points
   fillbad    - Linearly interpolate over bad data points.
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
arrayify ARRAYIFY Converts a set of scalars or arrays into column arrays.
bellpoly BELLPOLY Complete Bell polynomials.
blocklen BLOCKLEN Counts the lengths of 'blocks' in an array.
blocknum BLOCKNUM Numbers the contiguous blocks of an array.
choose CHOOSE Binomial coefficient: CHOOSE(N,K) = "N choose K"
commentlines COMMENTLINES Returns the comment lines from m-files.
cum2mom CUM2MOM Convert cumulants to moments.
fillbad FILLBAD Linearly interpolate over bad data points.
findfiles FINDFILES Returns all files in a directory with a specified extension.
findpath FINDPATH Returns the full pathname of a directory on the Matlab search path.
frac FRAC Fraction: FRAC(A,B)=A./B
hermfun HERMFUN Orthonormal Hermite functions. [with F. Rekibi]
hermpoly HERMPOLY Hermite polynomials. [with F. Rekibi]
imlog IMLOG Imaginary part of log: IMLOG(X)=UNWRAP(IMAG(LOG(X)))
iseven ISEVEN True for even integer values; false otherwise.
isodd ISODD True for odd integer values; false otherwise.
jhelp JHELP Opens linked JLAB help files in Matlab's internal web browser.
jmat JMAT 2x2 rotation matrix through specified angle.
jmat3 JMAT3 3x3 rotation matrix through specified angle.
lnsd LNSD Last non-singleton dimension of an array.
make MAKE Create a structure containing named variables as fields.
matmult MATMULT Matrix multiplication for arrays of matrices.
matsave MATSAVE Create and save structure of variables as a mat-file.
mom2cum MOM2CUM Convert moments to cumulants.
nonnan NONNAN Return all non-NAN elements of an array.
oprod OPROD Outer product: OPROD(X,Y)=X*CONJ(Y')
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
res RES Residual after flooring: RES(X)=X-FLOOR(X)
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
simplepdf SIMPLEPDF Gaussian, uniform, Cauchy, and exponential pdfs.
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
tmat TMAT 2x2 complex grouping matrix. TMAT = [1 i; 1 -i] / SQRT(2)
to_grab_from_caller TO_GRAB_FROM_CALLER Returns a string to grab variable values from caller.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
use USE Copies structure fields into named variables in workspace.
vectmult VECTMULT Matrix multiplication for arrays of vectors.
whichdir WHICHDIR Returns directory name containing file in search path.
This function is called by:
Contents jLab v1.5 by J. M. Lilly