Description of jdata
Home > jlab > jdata.m
jdata
 jData: Oceanographic datasets included with JLAB-FULL distribution
 Mat-files
   alongtrack - Sea surface height anomalies from the Beckley merged dataset.
                   Type 'about_alongtrack' for a description.
   drifters   - Global surface drifter dataset from the Global Drifter Program.
                   Type 'about_drifters' for a description.
   floats     - Historical dataset of eddy-resolving subsurface floats.
                   Type 'about_floats' for a description.
 Other files
   topo_18.1.img - One minute global topography.  See READTOPO for details.
 See also jTopo.
This function calls:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
about_drifters DRIFTERS Global surface drifter dataset from the Global Drifter Program.
about_floats FLOATS Historical dataset of eddy-resolving subsurface floats.
jdata jData: Oceanographic datasets included with JLAB-FULL distribution
This function is called by:
Contents jLab v1.5 by J. M. Lilly
jdata jData: Oceanographic datasets included with JLAB-FULL distribution