Description of jdeg2rad
Home > jlab > jdeg2rad.m
jdeg2rad
JDEG2RAD  Converts degrees to radians.
   [R1,R2,...RN]=JDEG2RAD(D1,D2,...DN) converts the input angles from
   degrees to radians.  Output angles are in the range [-pi,pi), that
   is, +/-180 degrees is defined to corresponds to -pi radians.
   NANs and INFs in the input arguments are preserved.
   See also JRAD2DEG, DEG180, DEG360.
   'jdeg2rad --t' runs a test.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2006--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
jdeg2rad JDEG2RAD Converts degrees to radians.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
jdeg2rad JDEG2RAD Converts degrees to radians.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jrad2deg JRAD2DEG Converts radians to degrees.
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
latratio LATRATIO Set plot aspect ratio for latitude / longitude plot.
sphere2uvw SPHERE2UVW Converts a 3D spherical vector to a 3D Cartesian vector.
spherecurl SPHERECURL Curl of a vector field on the surface of a sphere.
spheredist SPHEREDIST Computes great circle distances on a sphere.
spherediv SPHEREDIV Divergence of a vector field on the surface of a sphere.
spheregrad SPHEREGRAD Gradient of a field on the surface of a sphere.
spherelap SPHERELAP Laplacian of a field on the surface of a sphere.
xy2latlon XY2LATLON Converts local Cartesian coordinates into latitude and longitude.