Description of jellipse
Home > jlab > jellipse.m
jellipse
 jEllipse:  Analysis of modulated elliptical, or bivariate, signals
  Elliptical signal properties
   ellband    - Bandwidth of modulated elliptical signals in two or three dimensions.
   ellparams  - Ellipse parameters of a modulated bivariate or trivariate oscillation.
   ellvel     - Average and instantaneous ellipse velocities.
   ellrad     - Average and instantaneous ellipse radius.
  Elliptical signal generation and conversions
   ellsig     - Creates a modulated elliptical signal in two or three dimensions.
   sig2latlon - Converts an oscillatory signal to lat/lon displacements.
   elldiff    - Differentiation of modulated elliptical signals.
  Plotting tools
   ellcurves   - Returns curves corresponding to specified ellipse properties.
   ellipseplot - Plot ellipses.
  Basic ellipse properties
   ab2kl      - Converts A and B to ellipse parameters Kappa and Lambda.
   kl2ab      - Converts ellipse parameters Kappa and Lambda to A and B.
   ecconv     - Converts between eccentricity measures.
   ellrossby  - Ellipse Rossby number, for oceanographic applications.
  See also jRidges, jSpectral, jWavelet.
This function calls:
ab2kl AB2KL Converts A and B to ellipse parameters Kappa and Lambda.
ecconv ECCONV Converts between eccentricity measures.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellcurves ELLCURVES Returns curves corresponding to specified ellipse properties.
elldiff ELLDIFF Differentiation of modulated elliptical signals.
ellipseplot ELLIPSEPLOT Plot ellipses.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellrad ELLRAD Average and instantaneous ellipse radius.
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
ellvel ELLVEL Average and instantaneous ellipse velocities.
kl2ab KL2AB Converts ellipse parameters Kappa and Lambda to A and B.
sig2latlon SIG2LATLON Converts an oscillatory signal to lat/lon displacements.
This function is called by:
Contents jLab v1.5 by J. M. Lilly