Description of jlab_runtests
Home > jlab > jlab_runtests.m
jlab_runtests
JLAB_RUNTESTS  Runs a test suite for JLAB package.
   JLAB_RUNTESTS runs automated tests for the JLAB package.
   'jlab_runtests tests' runs all automated tests.
   'jlab_runtests figures' makes all sample figures.
   'jlab_runtests' with no arguments does both.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2002--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
findfiles FINDFILES Returns all files in a directory with a specified extension.
vsum VSUM Sum over finite elements along a specified dimension.
whichdir WHICHDIR Returns directory name containing file in search path.
This function is called by:
Contents jLab v1.5 by J. M. Lilly