Description of jlab_makefigs
Home > jlab > jlab_makefigs.m
jlab_makefigs
JLAB_MAKEFIGS  Makes figures for papers by J.M. Lilly.
   JLAB_MAKEFIGS NAME makes all figures for the publication NAME, as follows.
   'jlab_makefigs superfamily':
   Lilly, J. M., and S. C. Olhede (2012). Generalized Morse wavelets as a
      superfamily of analytic wavelets. IEEE Transactions on Signal
      Processing 60 (11), 6036--6041.
   'jlab_makefigs multivariate':
   Lilly, J. M., and S. C. Olhede (2012). Analysis of modulated
      multivariate oscillations. IEEE Transactions on Signal Processing,
      60 (2), 600--612.
   'jlab_makefigs vortex':
   Lilly, J. M., R. K. Scott, and S. C. Olhede (2011). Extracting waves
      and vortices from Lagrangian trajectories. Geophysical Research
      Letters, 38, L23605, 1--5.
   'jlab_makefigs trivariate':
   Lilly, J. M. (2011). Modulated oscillations in three dimensions. IEEE
      Transactions on Signal Processing, 59 (12), 5930--5943.
   'jlab_makefigs analytic':
   Lilly, J. M., and S. C. Olhede (2010). On the analytic wavelet
      transform. IEEE Transactions on Information Theory, 56 (8),
      4135--4156.
   'jlab_makefigs bandwidth':
   Lilly, J. M., and S. C. Olhede (2010). Bivariate instantaneous
      frequency and bandwidth. IEEE Transactions on Signal Processing,
      58 (2), 591--603.
   'jlab_makefigs asilomar':
   Lilly, J. M., and S. C. Olhede (2009). Wavelet ridge estimation of
      jointly modulated multivariate oscillations. IEEE 43rd Asilomar
      Conference on Signals, Systems, and Computers, 452--456.
   'jlab_makefigs morsies':
   Lilly, J. M., and S. C. Olhede, (2009). Higher-order properties of
      analytic wavelets. IEEE Transactions on Signal Processing, 57 (1),
      146--160.
   'jlab_makefigs ridges':
   Lilly, J. M., and J.-C. Gascard (2006). Wavelet ridge diagnosis of
      time-varying elliptical signals with application to an oceanic eddy.
      Nonlinear Processes in Geophysics 13, 467--483.
   'jlab_makefigs all' makes the figures for all papers.
   'jlab_makefigs NAME print' will  print all figure for paper NAME as
   .eps files in the current diretory, e.g. 'jlab_makefigs ridges print'.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
ab2kl AB2KL Converts A and B to ellipse parameters Kappa and Lambda.
anatrans ANATRANS Analytic part of signal.
anyany ANYANY(X)=ANY(X(:))
boxoff BOXON Sets 'box' property to 'off'.
boxon BOXON Sets 'box' property to 'on'.
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
celladd CELLADD Addition acting on each element in a cell array.
cellength CELLENGTH Length of each element in a cell array.
cellmult CELLMULT Multiplication acting on each element in a cell array.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
col2mat COL2MAT Expands 'column-appended' data into a matrix.
corfreq CORFREQ Coriolis frequency in radians per hour.
discretecolorbar DISCRETECOLORBAR Plots a colorbar with discrete variation.
ecconv ECCONV Converts between eccentricity measures.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellipseplot ELLIPSEPLOT Plot ellipses.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellrad ELLRAD Average and instantaneous ellipse radius.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
ellvel ELLVEL Average and instantaneous ellipse velocities.
fillbad FILLBAD Linearly interpolate over bad data points.
fixlabels FIXLABELS Specify precision of axes labels.
flipmap FLIPMAP Flips the current colormap upside-down.
flipy FLIPY Flips the direction of the y-axis
fontsize FONTSIZE Rapidly set title, axes, label, and text fontsizes.
fourier FOURIER The one-sided Fourier frequencies for a given length time series.
frac FRAC Fraction: FRAC(A,B)=A./B
hlines HLINES Add horizontal lines to a plot.
instmom INSTMOM Univariate and multivariate instantaneous moments.
inticks INTICKS Sets the 'tickdir' property of the current axis to 'in'.
iseven ISEVEN True for even integer values; false otherwise.
jdeg2rad JDEG2RAD Converts degrees to radians.
jmat3 JMAT3 3x3 rotation matrix through specified angle.
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
latratio LATRATIO Set plot aspect ratio for latitude / longitude plot.
letterlabels LETTERLABELS For automatically putting letter labels on subplots.
linecolor LINECOLOR Set line colors based on a property value within a colormap.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
make MAKE Create a structure containing named variables as fields.
matmult MATMULT Matrix multiplication for arrays of matrices.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
minmin MINMIN(X)=MIN(X(ISFINITE(X)))
morlfreq MORLFREQ Compute Morlet wavelet carrier frequency given peak frequency.
morlwave MORLWAVE Morlet wavelet.
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsederiv MORSEDERIV Frequency-domain derivatives of generalized Morse wavelets.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morseprops MORSEPROPS Properties of the demodulated generalized Morse wavelets.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
mspec MSPEC Multitaper power and cross spectra.
nocontours NOCONTOURS Removes contours from a CONTOURF plot.
nonnan NONNAN Return all non-NAN elements of an array.
noylabels NOYLABELS Remove some or all y-axis tick mark labels.
outticks OUTTICKS Sets the 'tickdir' property of the current axis to 'out'.
packfig PACKFIG Squeeze together rows and/or columns of the current figure.
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
periodindex PERIODINDEX Returns time index in increments of instantaneous period.
radearth RADEARTH The radius of the earth in kilometers.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
simplepdf SIMPLEPDF Gaussian, uniform, Cauchy, and exponential pdfs.
sleptap SLEPTAP Calculate Slepian tapers.
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
tmat TMAT 2x2 complex grouping matrix. TMAT = [1 i; 1 -i] / SQRT(2)
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
use USE Copies structure fields into named variables in workspace.
uvplot UVPLOT Plots the real and imaginary parts of a signal on the same axis.
vdiff VDIFF Length-preserving first central difference.
vectmult VECTMULT Matrix multiplication for arrays of vectors.
vfilt VFILT Filtering along rows without change in length.
vindex VINDEX Indexes an N-D array along a specified dimension.
vlines VLINES Add vertical lines to a plot.
vmean VMEAN Mean over finite elements along a specified dimension.
vrep VREP Replicates an array along a specified dimension.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
vsum VSUM Sum over finite elements along a specified dimension.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.
wavetrans WAVETRANS Continuous wavelet transform.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).
xlog XLOG Sets x-axis scale to logarithmic.
xtick XTICK Sets locations of x-axis tick marks.
xy2latlon XY2LATLON Converts local Cartesian coordinates into latitude and longitude.
ylog YLOG Sets y-axis scale to log.
yoffset YOFFSET Offsets lines in the y-direction after plotting.
ytick YTICK Sets locations of y-axis tick marks.
ztick ZTICK Sets locations of z-axis tick marks.
This function is called by:
Contents jLab v1.5 by J. M. Lilly