Description of jlab_license
Home > jlab > jlab_license.m
jlab_license
JLAB_LICENSE  License statement and permissions for JLAB package.
   Copyright (C) 1993--2015 J.M. Lilly
   _______________________________________________________________________
   Citation
   If you use this software in research resulting in a scientific
   publication, the software should be acknowledged and cited as
   Lilly, J. M. (2015), JLAB: Matlab freeware for data analysis,
       Version 1.5, http://www.jmlilly.net/software.html.
   _______________________________________________________________________
   License
   JLAB is distributed under the
     "Creative Commons Attribution-Noncommercial-ShareAlike License"
   Version 4.0, available at
      http://creativecommons.org/licenses/by-nc-sa/4.0/
   You are free:
       To Share -- copy and redistribute the material in any format
       To Adapt -- remix, transform, and build upon the material
   Under the following conditions:
     Attribution -- You must give appropriate credit, provide a link to
          the license, and indicate if changes were made. You may do so in
          any reasonable manner, but not in any way that suggests the
          licensor endorses you or your use.
       Noncommercial -- You may not use the material for commercial
           purposes.
       ShareAlike --  If you remix, transform, or build upon the
          material, you must distribute your contributions under the same
          license as the original.
   See the above link for the full text of the license.
   _______________________________________________________________________
   Disclaimer
   This software is provided 'as-is', without any express or implied
   warranty. In no event will the author be held liable for any damages
   arising from the use of this software.
   _______________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 1993--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
jlab_license JLAB_LICENSE License statement and permissions for JLAB package.
This function is called by:
Contents jLab v1.5 by J. M. Lilly
jlab_license JLAB_LICENSE License statement and permissions for JLAB package.