Description of jmap
Home > jlab > jmap.m
jmap
 jMap:  Mapping scattered data using local polynomial fitting
   polysmooth - Smoothing scattered 2D data with local polynomial fitting.
   spheresort - Sorted great circle distances to nearby points on the earth.
   twodsort   - Distances from data points to nearby grid points.
This function calls:
matinv MATINV Fast inversion of arrays of small matrices.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
twodsort TWODSORT Distances from data points to nearby grid points.
This function is called by:
Contents jLab v1.5 by J. M. Lilly