Description of jmat3
Home > jlab > jmat3.m
jmat3
JMAT3 3x3 rotation matrix through specified angle.
   J=JMAT3(PHI,N) creates a rotation matrix about axis N in three
   dimensions, e.g. JMAT3(PHI,3) returns
       J=[COS(PHI) -SIN(PHI) 0;
          SIN(PHI)  COS(PHI) 0;
             0        0      1]
   such that J*X rotates the column-vector X by PHI radians
   counterclockwise in the XY plane.
   If LENGTH(PHI)>1, then J will have dimension 3 x 3 x SIZE(PHI).
   N may either be a scalar or an array of the same length as PHI.
   See also VECTMULT, JMAT.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2010 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
vectmult VECTMULT Matrix multiplication for arrays of vectors.