Description of jmat
Home > jlab > jmat.m
jmat
JMAT 2x2 rotation matrix through specified angle.
   J=JMAT(PHI) creates a rotation matrix
       J=[COS(PHI) -SIN(PHI);
          SIN(PHI)  COS(PHI)]
   such that J*X rotates the column-vector X by PHI radians
   counterclockwise.
   If LENGTH(PHI)>1, then J will have dimension  2 x 2 x SIZE(PHI);
   See also JPOLY, VECTMULT, JMAT3, IMAT, KMAT, and TMAT.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
specdiag SPECDIAG Diagonalize a 2 x 2 spectral matrix.
vectmult VECTMULT Matrix multiplication for arrays of vectors.