Description of jmatern
Home > jlab > jmatern.m
jmatern
 jMatern:  Parametric spectral analysis based on the Matern process
 Top-level functions
   maternoise - Generates realizations of the Matern random process.  [with A. Sykulski]
   maternspec - Fourier spectrum of the Matern random process.
   materncov  - Autocovariance function of the Matern random process.
   maternimp  - Impulse response function for the Matern random process.
 Other utilities
   blurspec   - Returns the blurred and aliased spectrum given the autocovariance.
   fminsearchbnd: - FMINSEARCH, but with bound constraints by transformation. [By J. D'Errico]
 Low-level Matern functions
   maternc    - Returns the normalization function C_ALPHA for a Matern process.
   maternchol - Cholesky decomposition of Matern the covariance matrix.
   maternedge - Long-time cutoff edge for the Matern impulse response function.
   maternfun  - Returns the Matern function.
 See also jSpectral.
This function calls:
blurspec BLURSPEC Returns the blurred and aliased spectrum given the autocovariance.
fminsearchbnd FMINSEARCHBND: FMINSEARCH, but with bound constraints by transformation. [By J. D'Errico]
maternc MATERNC Returns the normalization function C_ALPHA for a Matern process.
maternchol MATERNCHOL Cholesky decomposition of the Matern covariance matrix.
materncov MATERNCOV Autocovariance function of the Matern random process.
maternedge MATERNEDGE Long-time cutoff edge for the Matern impulse response function.
maternfun MATERNFUN Returns the Matern function.
maternimp MATERNIMP Impulse response function for the Matern random process.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
This function is called by:
Contents jLab v1.5 by J. M. Lilly