Description of joceans
Home > jlab > joceans.m
joceans
 jOceans:  Oceanography-specific data and model analysis tools
 Conversions for Lagrangian trajectories
   latlon2uv   - Converts latitude and longitude to horizontal velocity.
   uv2latlon   - Integrates horizontal velocity to give latitude and longitude.
 Manipulating Lagrangian trajectories
   trajextract - Extracts Lagrangian trajectory segments within given region.
   trajfill    - Fills float or drifter trajectories with linear interpolation.
   trajunwrap  - Unwraps Lagrangian trajectories from a periodic domain.
   trajwrap    - Wraps Lagrangian trajectories to fit within a periodic domain.
   trajchunk   - Converts cell array data into chunks based on the Coriolis period.
 Idealized numerical model tools
   psi2fields   - Velocity and other fields from the streamfunction. [with P.E. Isachsen]
   periodize    - Returns a doubly periodic version of an input array.
 Eulerian eddy identification and analysis
   inellipse    - Locates points on the interior of ellipses.
   closedcurves - Locate and interpolate closed curves in a possibly periodic domain.
   curvemoments - Centroid, area, and many other moments of a closed curve.
   divgeom      - Geometric decomposition of eddy vorticity flux divergence.
  Plotting tools for mooring data
   hodograph  - Generate hodograph plots (simple and fancy).
   provec     - Generate progressive vector diagrams (simple and fancy).
   stickvect  - Plots "stick vectors" for multicomponent velocity time series.
  See also jSphere, jMatern.
This function calls:
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curveinterp CURVEINTERP Interpolate a field or its gradient onto a set of curves.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
divgeom DIVGEOM Geometric decomposition of eddy vorticity flux divergence.
hodograph HODOGRAPH Generate hodograph plots (simple and fancy).
inellipse INELLIPSE Locates points on the interior of ellipses.
joceans jOceans: Oceanography-specific data and model analysis tools
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
orbitbreaks ORBITBREAKS Separate orbit into passes based on turning points.
periodize PERIODIZE Returns a doubly periodic version of an input array.
provec PROVEC Generate progressive vector diagrams (simple and fancy).
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
stickvect STICKVECT Plots "stick vectors" for multicomponent velocity time series.
trajchunk TRAJCHUNK Converts Lagrangian trajectories into chunks based on the Coriolis period.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.
trajfill TRAJFILL Fills float or drifter trajectories with linear interpolation.
trajunwrap TRAJUNWRAP Unwraps Lagrangian trajectories from a periodic domain.
trajwrap TRAJWRAP Wraps Lagrangian trajectories to fit within a periodic domain.
uv2latlon UV2LATLON Integrates horizontal velocity to give latitude and longitude.
This function is called by:
Contents jLab v1.5 by J. M. Lilly
joceans jOceans: Oceanography-specific data and model analysis tools