Description of jpcolor
Home > jlab > jpcolor.m
jpcolor
JPCOLOR  Modified version of PCOLOR appropriate for cell-centered grids.
   JPCOLOR(XMID,YMID,Z) makes a PCOLOR plot with XMID and YMID marking the
   *centers* of the cells of Z.  X and Y should have uniform spacing.
   This is unlike PCOLOR(X,Y,Z), where X and Y mark the cell *edges*.
   Similarly, unlike PCOLOR, JPCOLOR does not throw away the last row and
   column of Z.
   The default shading for JPCOLOR is FLAT rather than FACETED.  JPCOLOR
   also sets the level of the PCOLOR image to the back of the plot.
   'jpcolor --f' generates a figure showing the differences from PCOLOR.
   Usage: jpcolor(x,y,z);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
boxon BOXON Sets 'box' property to 'on'.
jpcolor JPCOLOR Modified version of PCOLOR appropriate for cell-centered grids.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
about_jtopo JTOPO One-sixth degree global topography based on Smith and Sandwell.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
divgeom DIVGEOM Geometric decomposition of eddy vorticity flux divergence.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jpcolor JPCOLOR Modified version of PCOLOR appropriate for cell-centered grids.
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
readtopo READTOPO Read one-minute topography data from Smith and Sandwell.
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.