Description of jrad2deg
Home > jlab > jrad2deg.m
jrad2deg
JRAD2DEG  Converts radians to degrees.
   [D1,D2,...DN]=JRAD2DEG(R1,R2,...RN) converts the input angles from
   radians to degrees.  Output angles are in the range [-180,180),
   that is, +/- pi radians is defined to correspond to -180 degrees.
   NANs and INFs in the input arguments are preserved.
   See also JDEG2RAD, DEG180, DEG360.
   'jrad2deg --t' runs a test.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2006--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
jdeg2rad JDEG2RAD Converts degrees to radians.
jrad2deg JRAD2DEG Converts radians to degrees.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
jrad2deg JRAD2DEG Converts radians to degrees.
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
xy2latlon XY2LATLON Converts local Cartesian coordinates into latitude and longitude.
xyz2latlon XYZ2LATLON Converts 3D Cartesian coordinates into latitude and longitude.