Description of jridges
Home > jlab > jridges.m
jridges
 jRidges:  Wavelet ridge analysis of modulated oscillatory signals
  Top-level functions
   ridgewalk  - Extract wavelet transform ridges, including bias estimates.
   ridgemap   - Maps ridge quantities back onto the time series.
   instmom    - Univariate and multivariate instantaneous moments.
  Ridge utilities
   ridgelen   - Wavelet ridge length expressed as number of full cycles.
   periodindex - Returns time index in increments of instantaneous period.
  See also jEllipse, jWavelet.
This function calls:
instmom INSTMOM Univariate and multivariate instantaneous moments.
isridgepoint ISRIDGEPOINT Finds wavelet ridge points using one of several criterion.
lininterp LININTERP Fast linear interpolation for arbitrary-sized arrays.
periodindex PERIODINDEX Returns time index in increments of instantaneous period.
quadinterp QUADINTERP Fast quadratic interpolation for arbitrary-sized arrays.
ridgechains RIDGECHAINS Forms ridge curves by connecting transform ridge points.
ridgeinterp RIDGEINTERP Interpolate quantity values onto ridge locations.
ridgelen RIDGELEN Wavelet ridge length expressed as number of full cycles.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
This function is called by:
Contents jLab v1.5 by J. M. Lilly