Description of jspectral
Home > jlab > jspectral.m
jspectral
  jSpectral:  Multitaper spectral analysis, and other time series tools
  Multitaper spectral analysis
   sleptap    - Calculate Slepian tapers.
   mspec      - Multitaper power and cross spectra.
  Multitaper polarization analysis
   msvd       - Singular value decomposition for polarization analysis.
   polparams  - Spectral matrix polarization parameters.
   specdiag   - Diagonalize a 2 x 2 spectral matrix.
 Assorted other transforms
   slidetrans  - Sliding-window ('moving-window') Fourier transform.
   anatrans    - Analytic part of signal.
   wigdist     - Wigner distribtion (alias-free algorithm).
 Time series analysis utilities
   doublen     - Interpolates a time series to double its length.
   fourier     - The one-sided Fourier frequencies for a given length time series.
   sampletimes - Computes mean sampling intervals and their statistics.
  Plotting tools
   twospecplot - Plots a pair of rotary or Cartesian spectra.
  See also jWavelet, jEllipse, jMatern.
This function calls:
anatrans ANATRANS Analytic part of signal.
doublen DOUBLEN Interpolates a time series to double its length.
fourier FOURIER The one-sided Fourier frequencies for a given length time series.
jspectral jSpectral: Multitaper spectral analysis, and other time series tools
mspec MSPEC Multitaper power and cross spectra.
msvd MSVD Singular value decomposition for polarization analysis.
polparams POLPARAM Spectral matrix polarization parameters.
sampletimes SAMPLETIMES Computes mean sampling intervals and their statistics.
sleptap SLEPTAP Calculate Slepian tapers.
slidetrans SLIDETRANS Sliding-window ('moving-window') Fourier transform.
specdiag SPECDIAG Diagonalize a 2 x 2 spectral matrix.
timeseries_boundary TIMESERIES_BOUNDARY Apply boundary conditions to data before transform.
twospecplot TWOSPECPLOT Plots a pair of rotary or Cartesian spectra.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).
This function is called by:
Contents jLab v1.5 by J. M. Lilly
jspectral jSpectral: Multitaper spectral analysis, and other time series tools