Description of jsphere
Home > jlab > jsphere.m
jsphere
 jSphere:  Tools for latitude, longitude, and spherical geometry
 Simple lat / lon conversions
   deg180     - Converts degrees to the range [-180,180].
   deg360     - Converts degrees to the range [0, 360].
   jdeg2rad   - Converts degrees to radians.
   jrad2deg   - Converts radians to degrees.
 Distances and regions
   inregion   - Tests whether lat/lon points lie within a specified box.
   spheredist - Computes great circle distances on a sphere.
 Earth constants and frequencies
   radearth   - The radius of the earth in kilometers.
   corfreq    - Coriolis frequency in radians per hour.
   tidefreq   - Frequencies of the eight major tidal components.
 Coordinate transformations
   latlon2xy  - Converts latitude and longitude into local Cartesian coordinates.
   latlon2xyz - Converts latitude and longitude into 3D Cartesian coordinates.
   xy2latlon  - Converts local Cartesian coordinates into latitude and longitude.
   xyz2latlon - Converts 3D Cartesian coordinates into latitude and longitude.
   sphere2uvw - Converts a 3D spherical vector to a 3D Cartesian vector.
 Differential operators
   spherecurl - Curl of a vector field on the surface of a sphere.
   spherediv  - Divergence of a vector field on the surface of a sphere.
   spheregrad - Gradient of a field on the surface of a sphere.
   spherelap  - Laplacian of a field on the surface of a sphere.
 Plotting tools
   latratio   - Set plot aspect ratio for latitude / longitude plot.
   lonshift   - Shifts longitude origin for plotting purposes.
   regionplot - Plots a simple box indicating a latitude / longitude region.
This function calls:
corfreq CORFREQ Coriolis frequency in radians per hour.
deg180 DEG180 Converts degrees to the range [-180,180].
deg360 DEG360 Converts degrees to the range [0, 360].
inregion INREGION Tests whether lat/lon points lie within a specified box.
jdeg2rad JDEG2RAD Converts degrees to radians.
jrad2deg JRAD2DEG Converts radians to degrees.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
latlon2xyz LATLON2XYZ Converts latitude and longitude into 3D Cartesian coordinates.
latratio LATRATIO Set plot aspect ratio for latitude / longitude plot.
lonshift LONSHIFT Shifts longitude origin for plotting purposes.
radearth RADEARTH The radius of the earth in kilometers.
regionplot REGIONPLOT Plots a simple box indicating a latitude / longitude region.
sphere2uvw SPHERE2UVW Converts a 3D spherical vector to a 3D Cartesian vector.
spherecurl SPHERECURL Curl of a vector field on the surface of a sphere.
spheredist SPHEREDIST Computes great circle distances on a sphere.
spherediv SPHEREDIV Divergence of a vector field on the surface of a sphere.
spheregrad SPHEREGRAD Gradient of a field on the surface of a sphere.
spherelap SPHERELAP Laplacian of a field on the surface of a sphere.
tidefreq TIDEFREQ Frequencies of the eight major tidal components.
xy2latlon XY2LATLON Converts local Cartesian coordinates into latitude and longitude.
xyz2latlon XYZ2LATLON Converts 3D Cartesian coordinates into latitude and longitude.
This function is called by:
Contents jLab v1.5 by J. M. Lilly