Description of jstats
Home > jlab > jstats.m
jstats
 jStats:  Fast statistical analysis of large datasets in two dimensions
   twodhist   - Two-dimensional histogram.
   twodstats  - Mean, variance, and covariance of functions of two variables.
   twodmed    - Median value of a function of two variables.
This function calls:
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
This function is called by:
Contents jLab v1.5 by J. M. Lilly