Description of jtopo
Home > jlab > jtopo.m
jtopo
 jTopo:  Tools and data for plotting topography
 Mat-files
   jtopo  - One-sixth degree global topography based on Smith and Sandwell.
               Type 'about_jtopo' for a description.
 M-files
   topoplot  - Plot regional or global topography at one-sixth degree resolution.
   readtopo  - Read topography data from the Smith and Sandwell database.
  See also jData.
This function calls:
about_jtopo JTOPO One-sixth degree global topography based on Smith and Sandwell.
readtopo READTOPO Read one-minute topography data from Smith and Sandwell.
topo_copyright TOPO_COPYRIGHT Copyright statement for the Smith and Sandwell topography.
topoplot TOPOPLOT Plot regional or global topography at one-sixth degree resolution.
This function is called by:
Contents jLab v1.5 by J. M. Lilly
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
about_jtopo JTOPO One-sixth degree global topography based on Smith and Sandwell.
patchcontourf PATCHCONTOURF Generate filled contours using patches, with specified colors.
topoplot TOPOPLOT Plot regional or global topography at one-sixth degree resolution.