Description of jvarfun
Home > jlab > jvarfun.m
jvarfun
 jVarfun:  Perform common operations on multiple variables simultaneously.
  Sizes and statistics
   vsize      - Returns the sizes of multiple arguments.
   vmean      - Mean over finite elements along a specified dimension.
   vsum       - Sum over finite elements along a specified dimension.
   vstd       - Standard deviation over finite elements along a specfied dimension.
   vmoment    - Central moment over finite elements along a specfied dimension.
   vmedian    - Median over finite elements along a specified dimension.
  Reshaping, shifting, swapping
   vcolon     - Condenses its arguments, like X(:).
   vshift     - Cycles the elements of an array along a specified dimension.
   vsqueeze   - Squeezes multiple input arguments simultaneously.
   vrep       - Replicates an array along a specified dimension.
   vswap      - VSWAP(X,A,B) replaces A with B in numeric array X.
   vtranspose - Transpose multiple input arguments simultaneously.
  Initializing
   vzeros     - Initializes multiple variables to arrays of zeros or nans.
   vempty     - Initializes multiple variables to empty sets or empty cell arrays.
  Operations and indexing
   vfilt      - Filtering along rows without change in length.
   vdiff      - Length-preserving first central difference.
   vindex     - Indexes an N-D array along a specified dimension.
   vindexinto - Indexes into N-D array along a specified dimension.
  Reshaping dataset composed of irregular length segments
   col2mat    - Expands 'column-appended' data into a matrix.
   colbreaks  - Insert NANs into discontinuties in a vector.
   mat2col    - Compress NAN-padded matrix data into long columns.
  See also jCell.
This function calls:
col2mat COL2MAT Expands 'column-appended' data into a matrix.
colbreaks COLBREAKS Insert NANs into discontinuties in a vector.
mat2col MAT2COL Compress NAN-padded matrix data into long columns.
vcolon VCOLON Condenses its arguments, like X(:).
vdiff VDIFF Length-preserving first central difference.
vempty VEMPTY Initializes multiple variables to empty sets or empty cell arrays.
vfilt VFILT Filtering along rows without change in length.
vindex VINDEX Indexes an N-D array along a specified dimension.
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
vmean VMEAN Mean over finite elements along a specified dimension.
vmedian VMEDIAN Median over finite elements along a specified dimension.
vmoment VMOMENT Central moment over finite elements along a specfied dimension.
vrep VREP Replicates an array along a specified dimension.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
vsize VSIZE Returns the sizes of multiple arguments.
vsqueeze VSQUEEZE Squeezes multiple input arguments simultaneously.
vstd VSTD Standard deviation over finite elements along a specfied dimension.
vsum VSUM Sum over finite elements along a specified dimension.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
vtranspose VTRANSPOSE Transpose multiple input arguments simultaneously.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
This function is called by:
Contents jLab v1.5 by J. M. Lilly