Description of jwavelet
Home > jlab > jwavelet.m
jwavelet
 jWavelet: Continuous wavelet analysis using generalized Morse wavelets
 Top-level wavelet transform functions
   wavetrans  - Continuous wavelet transform.
   morsewave  - Generalized Morse wavelets of Olhede and Walden (2002).
   morsespace - Logarithmically-spaced frequencies for generalized Morse wavelets.
   wavespecplot - Plot of wavelet spectra together with time series.
 Details of generalized Morse wavelets
   morsearea  - Time-frequency concentration area of Morse wavelets. [with F. Rekibi]
   morsebox   - Heisenberg time-frequency box for generalized Morse wavelets.
   morsefreq  - Frequency measures for generalized Morse wavelets. [with F. Rekibi]
   morseprops - Properties of the demodulated generalized Morse wavelets.
   morsexpand - Generalized Morse wavelets via time-domain Taylor series.
   morsederiv - Frequency-domain derivatives of generalized Morse wavelets.
 Morlet wavelet
   morlwave   - Morlet wavelet.
   morlfreq   - Compute Morlet wavelet carrier frequency given peak frequency.
 See also jRidges, jSpectral, jEllipse.
This function calls:
dawson DAWSON The Dawson function. [By P.J. Acklam]
dawsonderiv DAWSONDERIV Derivatives of the Dawson function.
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
morlfreq MORLFREQ Compute Morlet wavelet carrier frequency given peak frequency.
morlwave MORLWAVE Morlet wavelet.
morsea MORSEA Returns the generalized Morse wavelet amplitude "a".
morsearea MORSEAREA Time-frequency concentration area of Morse wavelets. [with F. Rekibi]
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsederiv MORSEDERIV Frequency-domain derivatives of generalized Morse wavelets.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
morseproj MORSEPROJ Projection coefficient for two generalized Morse wavelets.
morseprops MORSEPROPS Properties of the demodulated generalized Morse wavelets.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
morsexpand MORSEXPAND Generalized Morse wavelets via time-domain Taylor series.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.
wavetrans WAVETRANS Continuous wavelet transform.
This function is called by:
Contents jLab v1.5 by J. M. Lilly
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets