Description of kl2ab
Home > jlab > kl2ab.m
kl2ab
KL2AB  Converts ellipse parameters Kappa and Lambda to A and B.
   [A,B]=KL2AB(K,L) converts ellipse amplitude K and ellipse
   parameter L to semi-major and semi-minor axes A and B.
   A and B are related to K and L by
         A = SIGN(L) * K * SQRT(1 + ABS(L))
         B = SIGN(L) * K * SQRT(1 - ABS(L))
   as discussed in Lilly and Gascard (2006).
   K and L are either arrays of the same size, or one may be an array
   and one may be a scalar.
   Usage: [a,b]=kl2ab(kappa,lambda)
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2009 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
ab2kl AB2KL Converts A and B to ellipse parameters Kappa and Lambda.
aresame ARESAME Test whether two N-D arrays are the same.
kl2ab KL2AB Converts ellipse parameters Kappa and Lambda to A and B.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
ab2kl AB2KL Converts A and B to ellipse parameters Kappa and Lambda.
elldiff ELLDIFF Differentiation of modulated elliptical signals.
ellrad ELLRAD Average and instantaneous ellipse radius.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
inellipse INELLIPSE Locates points on the interior of ellipses.
jellipse jEllipse: Analysis of modulated elliptical, or bivariate, signals
kl2ab KL2AB Converts ellipse parameters Kappa and Lambda to A and B.