Description of latlon2xyz
Home > jlab > latlon2xyz.m
latlon2xyz
LATLON2XYZ  Converts latitude and longitude into 3D Cartesian coordinates.
   [X,Y,Z]=LATLON2XYZ(LAT,LON) converts latitude and longitude of
   a position on the surface of a sphere into Cartesian coordinates.
   LAT and LON are in degrees and X, Y, and Z are in kilometers.
   LAT and LON may either be arrays of the same size, or LON may be an
   array and LAT a scalar.  X, Y, and Z will have the same size as LON.
   The Cartesian coordinate system is a right-handed system whose
   origin lies at the center of the sphere.  It is oriented with the
   Z-axis passing though the poles and the X-axis passing through
   the point LAT=0, LON=0.
   By default, the radius of the sphere is taken as RADEARTH.
   LATLON2XYZ(LAT,LON,R) uses a sphere of radius R, in kilometers,
   instead.
   LATLON2XYZ is inverted by XYZ2LATLON.
   See JSPHERE for related functions.
   'latlon2xyz --t' runs a test.
   Usage: [x,y,z]=latlon2xyz(lat,lon);
          [x,y,z]=latlon2xyz(lat,lon,R);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2006--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
latlon2xyz LATLON2XYZ Converts latitude and longitude into 3D Cartesian coordinates.
radearth RADEARTH The radius of the earth in kilometers.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
latlon2xyz LATLON2XYZ Converts latitude and longitude into 3D Cartesian coordinates.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
trajfill TRAJFILL Fills float or drifter trajectories with linear interpolation.
uv2latlon UV2LATLON Integrates horizontal velocity to give latitude and longitude.
xyz2latlon XYZ2LATLON Converts 3D Cartesian coordinates into latitude and longitude.