Description of latlon2uv
Home > jlab > latlon2uv.m
latlon2uv
LATLON2UV  Converts latitude and longitude to horizontal velocity.
   [U,V]=LATLON2UV(NUM,LAT,LON) where NUM is the data in DATENUM format
   and LAT and LON are the latitude and longitude in degrees, outputs the
   eastward and northward velocity components U and V in cm/s, computed
   using the first central difference.
   CV=LATLON2UV(...) with one output argument returns the complex- valued
   velocity CV=U+SQRT(-1)*V. NANs in LAT or LON become NAN+SQRT(-1)*NAN.
   NUM is a column vector or a matrix of the same size as LAT and LON.
   LAT and LON are matices having SIZE(NUM,1) rows.  U and V are the same
   size as LAT and LON.
   LATLON2UV computes the velocity components from the distance travelled
   across the surface of the sphere and the heading, taking account of
   the sphericity of the earth.
   The first and last points must be treated differently, as the central
   difference is not defined there.  At the first and last point we use,
   respectively, the first forward and first backward difference.
   The radius of the earth is given by the function RADEARTH.
   ___________________________________________________________________
   Cell array input / output
   LATLON2UV returns cell array output given cell array input.
   That is, if NUM, LAT, and LON, are all cell arrays of length K,
   containing K different numerical arrays, then the output will also be
   cell arrays of length K.
   ___________________________________________________________________
   Difference algorithm
   By default, LATLON2UV uses a first central difference algorithm which
   is defined to be the average of a forward and a backward difference.
   LATLON2UV(...,'forward') uses a first forward difference.  Velocity is
   computed based on the great circle distance and bearing from each point
   to the next point.
   LATLON2UV(...,'backward') uses a first backward difference.  Velocity
   is computed based on the great circle distance and bearing from each
   point to the previous point.  This is equivalent to the first forward
   difference computed backward in time.
   The first forward and first backward difference can be thought of as
   giving the Cartesian velocities of a departing and arriving particle,
   respectively.
   ___________________________________________________________________
   See also XY2LATLON, LATLON2XY, UV2LATLON.
   Usage:  [u,v]=latlon2uv(num,lat,lon);
           cv=latlon2uv(num,lat,lon);
   'latlon2uv --t' runs a test.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
imlog IMLOG Imaginary part of log: IMLOG(X)=UNWRAP(IMAG(LOG(X)))
jdeg2rad JDEG2RAD Converts degrees to radians.
jrad2deg JRAD2DEG Converts radians to degrees.
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
latlon2xyz LATLON2XYZ Converts latitude and longitude into 3D Cartesian coordinates.
radearth RADEARTH The radius of the earth in kilometers.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
spheredist SPHEREDIST Computes great circle distances on a sphere.
use USE Copies structure fields into named variables in workspace.
vdiff VDIFF Length-preserving first central difference.
vindex VINDEX Indexes an N-D array along a specified dimension.
vrep VREP Replicates an array along a specified dimension.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
xyz2latlon XYZ2LATLON Converts 3D Cartesian coordinates into latitude and longitude.
This function is called by:
about_drifters DRIFTERS Global surface drifter dataset from the Global Drifter Program.
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
joceans jOceans: Oceanography-specific data and model analysis tools
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
uv2latlon UV2LATLON Integrates horizontal velocity to give latitude and longitude.