Description of latratio
Home > jlab > latratio.m
latratio
LATRATIO  Set plot aspect ratio for latitude / longitude plot.
   LATRATIO(LAT) sets the aspect ratio of the current axis correctly a
   Cartesian plot centered about the latitude LAT, i.e. the x/y aspect
   ratio is set to COS(LAT).
   Equal distances along the x- and y-axes then correspond to the same
   physical distance.
   LAT is measured in degrees.
   LATRATIO(LAT,H) does the same for the axis with handle H.
   LATRATIO with no input arguments sets the aspect ratio of the current
   axis using the midpoint of the y-axis limits.
   AR=LATRATIO(LAT) alternately returns the correct aspect ratio in a
   two-element array AR, without modifying any plots.
   Usage: latratio(lat,h);
          latratio(lat);
          latratio;
          ar=latration(lat);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2013 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
frac FRAC Fraction: FRAC(A,B)=A./B
jdeg2rad JDEG2RAD Converts degrees to radians.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
about_drifters DRIFTERS Global surface drifter dataset from the Global Drifter Program.
about_floats FLOATS Historical dataset of eddy-resolving subsurface floats.
about_jtopo JTOPO One-sixth degree global topography based on Smith and Sandwell.
ellipseplot ELLIPSEPLOT Plot ellipses.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
makefigs_topoplot
patchcontourf PATCHCONTOURF Generate filled contours using patches, with specified colors.
readtopo READTOPO Read one-minute topography data from Smith and Sandwell.
regionplot REGIONPLOT Plots a simple box indicating a latitude / longitude region.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.