Description of letterlabels
Home > jlab > letterlabels.m
letterlabels
LETTERLABELS    For automatically putting letter labels on subplots.
   LETTERLABELS puts letter labels '(a)','(b)','(c)' etc., on the
   subplots of the current figure, in the upper left-hand corner of
   each subplot window.
   LETTERLABELS(I) specifies the labelling position, clockwise from
   top left:
        I=1    Top left
        I=2    Top right
        I=3    Bottom right
        I=4    Bottom left
   LETTERLABELS(H,I), where H is a vector of handles to subplots,
   puts labels on the subplots indicated by H.
   LETTERLABELS(H,I,'d'), begins the labelling with letter 'd'.
   LETTERLABELS will not put the letters on the right subplots if you
   click on them before hand (because this changes the order of the
   subplot handles).  Also if you want to label the subplots in a
   nonstandard order, do this by reordering H.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000, 2004 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
wigdist WIGDIST Wigner distribtion (alias-free algorithm).