Description of linestyle
Home > jlab > linestyle.m
linestyle
LINESTYLE  Rapidly set color, style, and width properties of lines.
   LINESTYLE provides an efficient way to set common properties of large
   groups of lines, and allows the user to quickly apply predefined sets
   of line colors, styles, and widths designed for different purposes.
   'LINESTYLE 1k-- 2.5g- m-.' sets the first line to width 1, color black,
   and dashed style; the second to width 2.5, color green, and solid
   style; and the third to width 1, color magenta, and dash-dotted style.
   LINESTYLE's color options supports grayscale colors, denoted by capital
   letters A--F, with A being white and K being black.
   In general the format is
       LINESTYLE STR1 STR2 STR3 ...
   where each of the STRs may contain a number, specifying the width of
   the Ith line; a letter, for the color; and a style string.  Any two of
   these are optional, with a unit width solid black line as the default.
   By default, styles are looped if the number of STRs input is less than
   the number of lines in the current plot. The input
       LINESTYLE STR1 STR2 ... STRN +++
   causes the last style input, STRN, to be repeated instead.
   Note that LINESTYLE will set styles for both lines as well as patch
   edges.  This is usually the desired behavior, as contours from CONTOUR
   are actually patches.  If this is not what is desired, call LINESTYLE
   with the explicit handle specification below, or else add contour plots
   to the current plot after calling LINESTYLE.
   _________________________________________________________________
   Locking and unlocking
   LINESYTLE LOCK and LINESTYLE UNLOCK lock and unlock all axes in the
   current figure.  When LOCK is on, calls to LINESTYLE or LINERING are
   applied to all lines in the current figure.
   _________________________________________________________________
   Handle specification
   LINESTYLE -H HAN STR1 STR2 .... applies the formatting only to the line
   handles contained in handle array HAN.
   LINESTYLE(HAN,STR) also works.
   HAN may also be the handle to a group of contours.
   _________________________________________________________________
   Customization
   LINESTYLE permits the use of user-defined colors, such as grayscale
   (capital letters A--K in order of increasing darkness). See
   JLAB_SETTINGS for more details.
   LINESTYLE(NAME) or LINESTYLE NAME applies the style set NAME, specified
   in the file JLAB_SETTINGS.  This allows one to predefine useful
   combinations of colors, styles, and widths.
   Type LINESTYLE with no arguments to see a list of current style sets.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
axeshandles AXESHANDLES Returns handles to all axes children.
linehandles LINEHANDLES Finds all line and patch handles from a given set of axes.
linering LINERING Moves lines through the current line style order.
to_grab_from_caller TO_GRAB_FROM_CALLER Returns a string to grab variable values from caller.
This function is called by:
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
divgeom DIVGEOM Geometric decomposition of eddy vorticity flux divergence.
dlines DLINES Add diagonal lines to a plot.
doublen DOUBLEN Interpolates a time series to double its length.
ecconv ECCONV Converts between eccentricity measures.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellipseplot ELLIPSEPLOT Plot ellipses.
ellvel ELLVEL Average and instantaneous ellipse velocities.
hlines HLINES Add horizontal lines to a plot.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
linering LINERING Moves lines through the current line style order.
maternfun MATERNFUN Returns the Matern function.
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
mspec MSPEC Multitaper power and cross spectra.
regionplot REGIONPLOT Plots a simple box indicating a latitude / longitude region.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
topoplot TOPOPLOT Plot regional or global topography at one-sixth degree resolution.
uvplot UVPLOT Plots the real and imaginary parts of a signal on the same axis.
vlines VLINES Add vertical lines to a plot.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).