Description of linehandles
Home > jlab > linehandles.m
linehandles
LINEHANDLES  Finds all line and patch handles from a given set of axes.
   H=LINEHANDLES returns handles to all lines associated with the current
   axes.
   H=LINEHANDLES(AX) returns handles to all lines associated with the set
   of axes whose handle is AX.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
jgraph jGraph: Plotting tools and refinements for making high-quality figures
linering LINERING Moves lines through the current line style order.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
xoffset XOFFSET Offsets lines in the x-direction after plotting.
yoffset YOFFSET Offsets lines in the y-direction after plotting.