Description of linering
Home > jlab > linering.m
linering
LINERING  Moves lines through the current line style order.
   LINERING works like a moveable highlighter, picking out a group of
   lines from the current plot.  This is accomplished by moving the
   line handles by a specified amount with respect to the current
   line style, color, and width order.
   Different subplots in the current figure may be locked together,
   highlighting comparable groups of lines.
   LINERING(N), where N is a *real* integer, moves all line handles
   in the current axes N steps forward (or backward for N<0) with
   respect to the current style order.  When N is an *imaginary*
   integer, LINERING moves the imag(N)th line to the first position
   with respect to the current style order.
   LINERING N also works, where N is an number (not a variable whose
   value is a number).
   LINERING with no arguments is the same as LINERING(1), and returns
   the lines to their original styles.
   LINERING LOCK and LINERING UNLOCK lock and unlock all axes in the
   current figure.  When LOCK is on, calls to LINERING or LINESTYLE
   are applied to all lines in the current figure.
   See also LINESTYLE.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
axeshandles AXESHANDLES Returns handles to all axes children.
linehandles LINEHANDLES Finds all line and patch handles from a given set of axes.
linering LINERING Moves lines through the current line style order.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
This function is called by:
jgraph jGraph: Plotting tools and refinements for making high-quality figures
linering LINERING Moves lines through the current line style order.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.