Description of linecolor
Home > jlab > linecolor.m
linecolor
LINECOLOR  Set line colors based on a property value within a colormap.
   LINECOLOR(H,C) set the lines with handles H to the colors C, determined
   by looking up the values of C within the 'jet' colormap.
   H and C should be arrays of the same size.
   LINECOLOR(H,C,CMIN,CMAX) uses the values CMIN and CMAX as the lower and
   uppermost values in the colormap, respectively.  The default behavior
   is to set CMIN and CMAX to the minimum and maximum values within C.
   LINECOLOR(...,MAP) alternately uses the colormap with the name MAP.
   'linecolor --t' runs a test.
   Usage: linecolor(h,c);
          linecolor(h,c,map);
          linecolor(h,c,cmin,cmax);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
frac FRAC Fraction: FRAC(A,B)=A./B
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
minmin MINMIN(X)=MIN(X(ISFINITE(X)))
This function is called by:
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.