Description of lnsd
Home > jlab > lnsd.m
lnsd
 LNSD  Last non-singleton dimension of an array.
   LNSD(X) returns the number of the last non-singleton dimension of X.
   This provides a useful definition of the dimensionality of X.  Unlike
   Matlab's NDIMS, which thinks that a column vector and a scalar both
   have dimension 2, LNSD defines the dimension of a scalar to be zero and
   that of a column vector to be one, while a row vector has an LNSD of 2.
   Note that LNSD(X) changes if X is permuted.
   [N1,N2,...NM]=LNSD(X1,X2,...XM) returns the dimensions of multiple
   input arguments.  If zero or one output arguments are given, a single
   row array [N1 N2 ...NM] is output.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2002--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
lnsd LNSD Last non-singleton dimension of an array.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
instmom INSTMOM Univariate and multivariate instantaneous moments.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
lnsd LNSD Last non-singleton dimension of an array.
matinv MATINV Fast inversion of arrays of small matrices.