Description of lonshift
Home > jlab > lonshift.m
lonshift
LONSHIFT  Shifts longitude origin for plotting purposes.
   LON=LONSHIFT(LONO,LON) shifts the array LON such that its first
   point its just greater than LONO. This is used for controlling
   where the longitude break occurs on a map of the earth.
   LON may be given either on the interval [-180,+180] or on [0,360],
   and LONO may take on any value, e.g. -340, 20, 380, etc.
   [LON,X1,X2,...XN]=LONSHIFT(LONO,LON,X1,X2,...XN) also shifts the
   N matrices X1...XN.  These matrices must be oriented such that
   their number of columns is the same as the length of LON.
   Upon output, LON will increase from a minimum value of LONO.
   'lonshift --t' runs a test.
   Usage:  lon=lonshift(lono,lon);
           [lon,x1,x2,x3]=lonshift(lono,lon,x1,x2,x3);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2013 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
deg360 DEG360 Converts degrees to the range [0, 360].
frac FRAC Fraction: FRAC(A,B)=A./B
lonshift LONSHIFT Shifts longitude origin for plotting purposes.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
minmin MINMIN(X)=MIN(X(ISFINITE(X)))
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
This function is called by:
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
lonshift LONSHIFT Shifts longitude origin for plotting purposes.
topoplot TOPOPLOT Plot regional or global topography at one-sixth degree resolution.