Description of makefigs_topoplot
Home > jlab > makefigs_topoplot.m
makefigs_topoplot
This function calls:
boxon BOXON Sets 'box' property to 'on'.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
crop CROP Gets rid of whitespace around an image. [by A. Bliss]
flipmap FLIPMAP Flips the current colormap upside-down.
fontsize FONTSIZE Rapidly set title, axes, label, and text fontsizes.
hlines HLINES Add horizontal lines to a plot.
latratio LATRATIO Set plot aspect ratio for latitude / longitude plot.
topoplot TOPOPLOT Plot regional or global topography at one-sixth degree resolution.
use USE Copies structure fields into named variables in workspace.
whichdir WHICHDIR Returns directory name containing file in search path.
This function is called by:
topoplot TOPOPLOT Plot regional or global topography at one-sixth degree resolution.