Description of make
Home > jlab > make.m
make
MAKE  Create a structure containing named variables as fields.
   MAKE NAME V1 V2 ... VN where the VI are names of variables, creates
   a structure NAME with fields
       NAME.V1, NAME.V2, ... NAME.VN
   The original variables are not deleted.
   MAKE(CELL), where CELL is a cell array of strings such that
   CELL{1}=NAME, CELL{2}=V1, ... CELL{N}=VN, also works.
   This is useful for handling multiple datasets with the same variable
   names.  The structures can be then kept in memory and 'mapped' into
   variables as needed using USE.
   See also USE, MATSAVE.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
about_floats FLOATS Historical dataset of eddy-resolving subsurface floats.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
matsave MATSAVE Create and save structure of variables as a mat-file.