Description of mat2col
Home > jlab > mat2col.m
mat2col
MAT2COL  Compress NAN-padded matrix data into long columns.
   C=MAT2COL(M), where the columns of matrix M are data vectors of
   nonuniform length with NANs filling out the gaps in each column,
   appends together all the columns into a vector C in which isolated
   NANs mark the transitions between columns.
   [C1,C2,...]=MAT2COL(M1,M2,...) also works for multiple input
   matrices of the same size.  In this case the locations of NANs in
   M1 are used as the key for appending all the MI into columns.
   MAT2COL, COL2MAT, and COLBREAKS together form a system for moving
   data with segments of nonuniform length rapidly back and forth
   between a column format and a padded-matrix format. CTD or float
   data, for instance, can be stored in the (usually much smaller)
   column format and converted into the matrix format upon loading.
   MAT2COL(M1,M2,...); with no output arguments overwrites the
   original input variables.
   See also COL2MAT, COLBREAKS, COL2CELL, CELL2COL
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2013 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
This function is called by:
about_drifters DRIFTERS Global surface drifter dataset from the Global Drifter Program.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.