Description of maternspec
Home > jlab > maternspec.m
maternspec
MATERNSPEC  Fourier spectrum of the Matern random process.
   [F,S]=MATERNSPEC(N,SIG,ALPHA,H) returns the spectrum S of a length N
   complex-valued Matern random process having variance SIG^2, slope
   parameter ALPHA, and range or damping parameter H.
   F is an array of one-sided (positive) Fourier frequencies for a time
   series of length N, F=FOURIER(N).  Note that F is a *radian* frequency.
   For simplicity, the sample interval is taken to be unity.
   The lengths of the output variables F and S are N/2+1 for even N, and
   (N+1)/2 for odd N.
   S is the postive rotary spectrum given by
        S(F) = SIG^2 / (F^2 + H^2)^ALPHA * D(ALPHA,H)
   where D(ALPHA,H)= 2 * H^(2*ALPHA-1)./MATERNC(ALPHA) is a normalizing
   function, with MATERNC being a function of the slope parameter ALPHA.
   Note that the positive and negative rotary spectra are identical for
   the standard Matern process.
   The input parameters SIG, ALPHA, and H, may all either be scalars or
   arrays of the same length M.  If the latter, then the output spectrum
   S will be a matrix with LENGTH(F) rows and M columns.
   The sample interval is taken to be unity.  The damping parameter H is
   understood to have units of the inverse of the sample interval.
   For further details, see Sykulski, Olhede, Lilly, and Danioux (2015),
   "Lagrangian time series models for ocean surface drifter trajectories."
   __________________________________________________________________
   Sample interval
   MATERNSPEC(DT,N,SIG,ALPHA,H) uses DT as the sample interval, instead of
   the default DT=1.  H is understood to have the same units as 1/DT.
   __________________________________________________________________
   Oscillatory Matern
   [F,SPP,SNN]=MATERNSPEC(N,SIG,ALPHA,C), with C complex, uses H=REAL(C)
   for the damping, and also sets a rotation frequency to OMEGA=-IMAG(C).
   SPP and SNN are now the postive rotary and negative rotary spectra,
        SPP(F) = SIG^2 / [(F-OMEGA)^2 + H^2]^ALPHA    * D(ALPHA,H)
        SPP(F) = SIG^2 / [(-F-OMEGA)^2 + H^2]^ALPHA   * D(ALPHA,H)
   with the spectrum for positive frequencies +F returned in SPP, and for
   negative frequencies -F in SNN.
   The associated oscillatory process undergoes rotations at frequency
   OMEGA in addition to the damping at timescale 1/H.
   Note that OMEGA has units of radians per sample interval.  If DT is
   input, then OMEGA is understood to ahve the same units as 1/DT.
   __________________________________________________________________
   Special cases
   The generalized Matern family contains several other families of
   random processes as special cases:
     OMEGA=0           - The complex-valued Matern process
     OMEGA=0 and H=0   - Complex-valued fractional Brownian motion
     ALPHA=1           - The complex Ornstein-Uhlenbeck process
     ALPHA=1, OMEGA=0  - Z=X+iY where X and Y are real-valued OU processes
   See Sykulski, Olhede, Lilly, and Danioux (2015) for more discussion.
   __________________________________________________________________
   See also MATERNCOV, MATERNOISE, MATERNPROPS, MATERNFIT, BLURSPEC.
   'maternspec --f' generates some sample figures.
   Usage:      [f,s]=maternspec(N,sig,alpha,h);
               [f,spp,snn]=maternspec(dt,N,sig,alpha,h);
               [f,spp,snn]=maternspec(N,sig,alpha,c);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
arrayify ARRAYIFY Converts a set of scalars or arrays into column arrays.
fontsize FONTSIZE Rapidly set title, axes, label, and text fontsizes.
fourier FOURIER The one-sided Fourier frequencies for a given length time series.
frac FRAC Fraction: FRAC(A,B)=A./B
letterlabels LETTERLABELS For automatically putting letter labels on subplots.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
maternc MATERNC Returns the normalization function C_ALPHA for a Matern process.
materncov MATERNCOV Autocovariance function of the Matern random process.
maternimp MATERNIMP Impulse response function for the Matern random process.
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
packfig PACKFIG Squeeze together rows and/or columns of the current figure.
uvplot UVPLOT Plots the real and imaginary parts of a signal on the same axis.
vlines VLINES Add vertical lines to a plot.
vrep VREP Replicates an array along a specified dimension.
ytick YTICK Sets locations of y-axis tick marks.
This function is called by:
blurspec BLURSPEC Returns the blurred and aliased spectrum given the autocovariance.
jmatern jMatern: Parametric spectral analysis based on the Matern process
materncov MATERNCOV Autocovariance function of the Matern random process.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
maternspec MATERNSPEC Fourier spectrum of the Matern random process.