Description of maternedge
Home > jlab > maternedge.m
maternedge
MATERNEDGE  Long-time cutoff edge for the Matern impulse response function.
   TE=MATERNEDGE(ALPHA,H,EPSILON) determines a long-time cutoff for the
   Green's function of a Matern process characterized by slope parameter
   ALPHA and range parameter H.
   TE is the (approximately) the first time at which the ratio of the
   time-integrated magnitude of the Green's function, to the value it
   obtains at infinity, has risen to within EPSILON of unity.
   TE is approximate because of discretization of time.  It will always be
   greater than the actual time at which the EPSILON level is reached.
   See Sykulski, Lilly, Olhede, and Danioux (2013) for details.
   MATERNEDGE is a low-level function that is called by MATERNOISE.
   See also MATERNSPEC, MATERNCOV, MATERNIMP, MATERNOISE, MATERNPROPS.
   'maternedge --t' runs some tests.
   Usage: te=maternedge(alpha,h,epsilon);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
arrayify ARRAYIFY Converts a set of scalars or arrays into column arrays.
frac FRAC Fraction: FRAC(A,B)=A./B
maternc MATERNC Returns the normalization function C_ALPHA for a Matern process.
maternedge MATERNEDGE Long-time cutoff edge for the Matern impulse response function.
maternimp MATERNIMP Impulse response function for the Matern random process.
oprod OPROD Outer product: OPROD(X,Y)=X*CONJ(Y')
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vcolon VCOLON Condenses its arguments, like X(:).
This function is called by:
jmatern jMatern: Parametric spectral analysis based on the Matern process
maternedge MATERNEDGE Long-time cutoff edge for the Matern impulse response function.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]