Description of maternfun
Home > jlab > maternfun.m
maternfun
MATERNFUN  Returns the Matern function.
   MATERNFUN is a low-level function called by MATERNCOV.
   XI=MATERNFUN(ALPHA,R) returns the value of the Matern function of order
   ALPHA at location R.  THe Matern function is defined as
      XI(R)=1/(GAMMA(ALPHA)*2^(ALPHA-1)) * R^ALPHA K_ALPHA(R)
   where K_ALPHA is the modified Bessel function of the second kind of
   order ALPHA. This definition implies XI(0)=1.
   ALPHA and R can either be scalars or 1D arrays.  XI will be an array of
   size LENGTH(R) x LENGTH(ALPHA).
   [XI,XI1,XI2]=MATERNFUN(ALPHA,R) also returns its first two derivatives.
   'maternfun --t' runs some tests.
   'maternfun --f' generates a sample figure.
   See also MATERNRAD.
   Usage:  xi=maternfun(alpha,r);
          [xi,xi1,xi2]=maternfun(alpha,r);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
maternfun MATERNFUN Returns the Matern function.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vdiff VDIFF Length-preserving first central difference.
This function is called by:
jmatern jMatern: Parametric spectral analysis based on the Matern process
materncov MATERNCOV Autocovariance function of the Matern random process.
maternfun MATERNFUN Returns the Matern function.