Description of materncov
Home > jlab > materncov.m
materncov
MATERNCOV  Autocovariance function of the Matern random process.
   [TAU,R]=MATERNCOV(N,SIG,ALPHA,H) gives the theoretical autocovariance
   function for a length N complex-valued Matern process with variance
   SIG^2, slope parameter ALPHA, and damping or range parameter H.
   TAU is an array of time lags at which R is computed, and is given by
   TAU=[0,1,...,N-1].
   By definition, R is one-sided theoretical autocovariance at
   non-negative time lags.  See below for the relationship between this
   and the full, length (2N-1) theoretical autocovariance function.
   The sample interval is taken to be unity.  The damping parameter H is
   understood to have units of the inverse of the sample interval.
   Note that for H=0, the case of fractional Brownian motion, R will
   contain only INFs because the autocovariance function is unbounded.
   The input parameters SIG, ALPHA, and H, may all either be scalars or
   arrays of the same length M.  If the latter, then the output
   autocovariance function R will be a matrix with N rows and M columns.
   See MATERNSPEC for a more thorough discussion of the Matern process.
   For further details, see Sykulski, Olhede, Lilly, and Danioux (2015),
   "Lagrangian time series models for ocean surface drifter trajectories."
   __________________________________________________________________
   Relationship to full autocovariance
   For a time series of length N, the full autocovariance function RF is
   length 2N-1, defined at time lags -N+1,-N+2...,-1,0,1,...,N-2,N-1.
   The one-sided autocovariance R contains the full autocovariance RF at
   positive time lags. Negative lags are given by Hermitian symmetry.
   [TAUF,RF]=MATERNCOV(...,'full') returns the full (two-sided)
   autocovariance RF and the corresponding two-sided time array TAUF.
   RF is constructed from R as RF=[FLIPUD(CONJ(R(2:end,:));R].
   __________________________________________________________________
   Oscillatory Matern
   MATERNCOV(N,SIG,ALPHA,C), where C is complex, uses H=REAL(C) for the
   damping parameter and also sets a rotation frequency to OMEGA=-IMAG(C).
   The associated oscillatory process undergoes rotations at frequency
   OMEGA in addition to the damping at timescale 1/H.
   __________________________________________________________________
   Specified times
   R=MATERNCOV(TAU,SIG,ALPHA,H) where the first argument is an *array*
   rather than a scalar, will alternately return the autocovariance at
   the specified time lags TAU.  TAU is not output again in this case.
   __________________________________________________________________
   See also MATERNSPEC, MATERNIMP, MATERNOISE, MATERNPROPS, MATERNFIT.
   'materncov --t' runs some tests.
   Usage:    [tau,R]=materncov(N,sig,alpha,h);
             R=materncov(tau,sig,alpha,h);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013--2015  J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
arrayify ARRAYIFY Converts a set of scalars or arrays into column arrays.
materncov MATERNCOV Autocovariance function of the Matern random process.
maternfun MATERNFUN Returns the Matern function.
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
blurspec BLURSPEC Returns the blurred and aliased spectrum given the autocovariance.
jmatern jMatern: Parametric spectral analysis based on the Matern process
maternchol MATERNCHOL Cholesky decomposition of the Matern covariance matrix.
materncov MATERNCOV Autocovariance function of the Matern random process.
maternimp MATERNIMP Impulse response function for the Matern random process.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
maternspec MATERNSPEC Fourier spectrum of the Matern random process.