Description of maternoise
Home > jlab > maternoise.m
maternoise
MATERNOISE  Generates realizations of the Matern random process.  [with A. Sykulski]
   Z=MATERNOISE(N,SIG,ALPHA,H) simulates a length N complex-valued Matern
   random process Z having variance SIG^2, slope parameter ALPHA, and
   range or damping parameter H.
   Z=MATERNOISE([N,M],SIG,ALPHA,H) generate M realizations of this
   process, so that Z is of size N x M.
   The sample interval is taken to be unity.  The damping parameter H is
   understood to have units of the inverse of the sample interval.
   See MATERNSPEC for details on the input arguments.
   Note that the process Z is explicitly set to have zero temporal mean.
   For further details, see Sykulski, Olhede, Lilly, and Danioux (2015),
   "Lagrangian time series models for ocean surface drifter trajectories."
   __________________________________________________________________
   Sample interval
   MATERNOISE(DT,N,SIG,ALPHA,H) uses DT as the sample interval, instead of
   the default DT=1. H is understood to have the same units as 1/DT.
   Note that the spectra of MATERNOISE(N,SIG,ALPHA,H) with a unit sample
   rate, and MATERNOISE(DT,N,SIG,ALPHA,H./DT), with a new sample rate DT,
   will have the same spectral shape.
   For values of H greater than about 1/DT, the process becomes
   essentially white noise.  Thus typical values will have H<(1/DT).
   __________________________________________________________________
   Multiple parameter values
   The input arguments SIG, ALPHA, and H may all be either scalars, or
   arrays of the same length, say K.
   Z=MATERNOISE(N,SIG,ALPHA,H), with at least one of SIG, ALPHA, and H
   being an array of length K, returns a matrix Z that is N x K.
   Z=MATERNOISE([N M],SIG,ALPHA,H) then returns Z of size N x M x K.
   __________________________________________________________________
   Algorithm
   MATERNOISE uses a Cholesky matrix decomposition method which makes the
   autocovariance matrix of the generated process Z have exactly the form
   of a sampled Matern autocovariance function, for nonzero H, or of
   fractional Brownian motion for H=0.
   Note that since the Cholesky decomposition requires O(N^3) operations,
   generating very long time series (>2000 points or so) may be slow.
   __________________________________________________________________
   Oscillatory Matern
   MATERNOISE(N,SIG,ALPHA,C), where C=H-i*OMEGA is complex-valued, uses
   H=REAL(C) for the damping parameter and also sets a rotation frequency
   to OMEGA=-IMAG(C).
   The associated oscillatory process undergoes rotations at frequency
   OMEGA in addition to the damping at timescale 1/H.
   Note that OMEGA has units of radians per sample interval.  If DT is
   input, then OMEGA is understood to ahve the same units as 1/DT.
   __________________________________________________________________
   Fast algorithm
   MATERNOISE(...,'fast') uses a fast, highly accurate approximate
   generation algorithm.  This method works by making use of the known
   analytic form for the Matern impulse response function.
   In the fast algorithm, oversampling is used to ensure that the
   structure of the Green's function is accurately resolved.  Note that
   the fast algorithm is only accurate for ALPHA>=1.
   [Z,ERR]=MATERNOISE(...,'fast') also returns the error ERR involved in
   the fast algorithm's approximation of the autocovariance sequence.
   See the sample figures for a test of the fast algorithm.
   __________________________________________________________________
   See also MATERNSPEC, MATERNCOV, MATERNIMP, MATERNPROPS.
   'maternoise --t' runs some tests.
   'maternoise --f' generates some sample figures.
   Usage: z=maternoise(N,sig,alpha,h);
          z=maternoise([N,M],sig,alpha,h);
          z=maternoise(dt,[N,M],sig,alpha,h);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013--2015  A.M. Sykulski and J.M. Lilly
                                 --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
anyany ANYANY(X)=ANY(X(:))
arrayify ARRAYIFY Converts a set of scalars or arrays into column arrays.
frac FRAC Fraction: FRAC(A,B)=A./B
maternc MATERNC Returns the normalization function C_ALPHA for a Matern process.
maternchol MATERNCHOL Cholesky decomposition of the Matern covariance matrix.
materncov MATERNCOV Autocovariance function of the Matern random process.
maternedge MATERNEDGE Long-time cutoff edge for the Matern impulse response function.
maternimp MATERNIMP Impulse response function for the Matern random process.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
mspec MSPEC Multitaper power and cross spectra.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
sleptap SLEPTAP Calculate Slepian tapers.
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
vcolon VCOLON Condenses its arguments, like X(:).
vempty VEMPTY Initializes multiple variables to empty sets or empty cell arrays.
vrep VREP Replicates an array along a specified dimension.
vstd VSTD Standard deviation over finite elements along a specfied dimension.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
xlog XLOG Sets x-axis scale to logarithmic.
ylog YLOG Sets y-axis scale to log.
This function is called by:
jmatern jMatern: Parametric spectral analysis based on the Matern process
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]