Description of maternchol
Home > jlab > maternchol.m
maternchol
MATERNCHOL  Cholesky decomposition of the Matern covariance matrix.
   MATERNCHOL is a low-level function called by MATERNOISE.
   T=MATERNCHOL(N,ALPHA,H) returns the Cholesky decomposition of the N x N
   autocovariance matrix of a unit variance complex-valued Matern process
   with slope parameter ALPHA and damping or range parameter H.
   Note that H=0 case also works.  This corresponds to fractional Brownian
   motion, whereas a Matern process is formally defined for H > 0.  In
   this case, variance is undefined, and autovariance matrix is for a
   unit spectral amplitude process rather than a unit variance process.
   See MATERNSPEC for a more thorough discussion of the Matern process.
   For further details, see Sykulski, Olhede, Lilly, and Danioux (2015),
   "Lagrangian time series models for ocean surface drifter trajectories."
   __________________________________________________________________
   Oscillatory Matern
   MATERNCHOL(N,ALPHA,C), where C is complex, uses H=REAL(C) for the
   damping parameter and also sets a rotation frequency to OMEGA=-IMAG(C).
   The associated oscillatory process undergoes rotations at frequency
   OMEGA in addition to the damping at timescale 1/H.
   __________________________________________________________________
   'maternchol --t' runs a test.
   Usage: T=maternchol(N,alpha,h);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013--2015  A.M. Sykulski and J.M. Lilly
                                 --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
maternchol MATERNCHOL Cholesky decomposition of the Matern covariance matrix.
materncov MATERNCOV Autocovariance function of the Matern random process.
maternimp MATERNIMP Impulse response function for the Matern random process.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
vrep VREP Replicates an array along a specified dimension.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
This function is called by:
jmatern jMatern: Parametric spectral analysis based on the Matern process
maternchol MATERNCHOL Cholesky decomposition of the Matern covariance matrix.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]