Description of maternimp
Home > jlab > maternimp.m
maternimp
MATERNIMP  Impulse response function for the Matern random process.
   [T,G]=MATERNIMP(N,ALPHA,H) returns first N points for the impulse
   response function G for a unit-variance complex-valued Matern process
   with slope parameter ALPHA and damping or range parameter H.
   The impulse response function is also known as the Green's function.
   T is an array of times T=[ESILON 1:1:N] where the first point is set to
   a very small number, set to EPSILON=1e-6 to avoid the potential for
   infinite values at T=0 for some parameter settings.
   The sample interval is taken to be unity.  The damping parameter H is
   understood to have units of the inverse of the sample interval.
   Note that for H=0, the case of fractional Brownian motion, G is
   formally defined but is not useful because it does not decay.
   The input parameters ALPHA and H may either be scalars or arrays of the
   same length M.  If the latter, then the output autocovariance function
   R will be a matrix with N rows and M columns.
   See MATERNSPEC for a more thorough discussion of the Matern process.
   For further details, see Sykulski, Olhede, Lilly, and Danioux (2015),
   "Lagrangian time series models for ocean surface drifter trajectories."
   __________________________________________________________________
   Oscillatory Matern
   MATERNIMP(N,ALPHA,C), where C is complex, uses H=REAL(C) for the
   damping parameter and also sets a rotation frequency to OMEGA=-IMAG(C).
   The associated oscillatory process undergoes rotations at frequency
   OMEGA in addition to the damping at timescale 1/H.
   __________________________________________________________________
   Specified times
   G=MATERNIMP(T,ALPHA,H) where the first argument is an *array*
   rather than a scalar, will alternately return the impulse response at
   the specified times T.  Note T is not output again in this case.
   __________________________________________________________________
   See also MATERNSPEC, MATERNCOV, MATERNOISE, MATERNPROPS, MATERNFIT.
   'maternimp --t' runs some tests.
   Usage:    [t,G]=maternimp(N,alpha,h);
             G=maternimp(t,alpha,h);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013--2015  J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
arrayify ARRAYIFY Converts a set of scalars or arrays into column arrays.
frac FRAC Fraction: FRAC(A,B)=A./B
maternc MATERNC Returns the normalization function C_ALPHA for a Matern process.
materncov MATERNCOV Autocovariance function of the Matern random process.
maternimp MATERNIMP Impulse response function for the Matern random process.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
vcolon VCOLON Condenses its arguments, like X(:).
vrep VREP Replicates an array along a specified dimension.
This function is called by:
jmatern jMatern: Parametric spectral analysis based on the Matern process
maternchol MATERNCHOL Cholesky decomposition of the Matern covariance matrix.
maternedge MATERNEDGE Long-time cutoff edge for the Matern impulse response function.
maternimp MATERNIMP Impulse response function for the Matern random process.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
maternspec MATERNSPEC Fourier spectrum of the Matern random process.