Description of maternc
Home > jlab > maternc.m
maternc
MATERNC  Returns the normalization function C_ALPHA for a Matern process.
   MATERNC is a low-level function used in the JMATERN package.
   MATERNC(ALPHA) returns (1/PI)*GAMMA(ALPHA-1/2)/GAMMA(ALPHA) where GAMMA
   is the usual gamma function.
   Usage: c=maternc(alpha);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
frac FRAC Fraction: FRAC(A,B)=A./B
This function is called by:
blurspec BLURSPEC Returns the blurred and aliased spectrum given the autocovariance.
jmatern jMatern: Parametric spectral analysis based on the Matern process
maternedge MATERNEDGE Long-time cutoff edge for the Matern impulse response function.
maternimp MATERNIMP Impulse response function for the Matern random process.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
maternspec MATERNSPEC Fourier spectrum of the Matern random process.