Description of matmult
Home > jlab > matmult.m
matmult
MATMULT  Matrix multiplication for arrays of matrices.
   Often we wish to form the matrix product A*B for two matrices A and B.
   MATMULT performs matrix multiplication for arrays of such matrices.
   Let A be an array of K different M x N matrices, and similarly
   let B be an array of K different N x P matrices.
   C=MATMULT(A,B,DIM) returns an array of the K products CK=AK*BK, where
   DIM gives the dimension in A on which the M x N matrix begins.
   Thus A, B, and C have the following dimensions
                               DIM
                                |
         A --   K1 x K2 x ... x M x N x ... x KN
         B --   K1 x K2 x ... x N x P x ... x KN
         C --   K1 x K2 x ... x M x P x ... x KN
   The usual matrix multiplication is then C=MATMULT(A,B,1).
   A and B can have any dimensionality so long as the dimensions
   containing the matrices are adjacent to each other.
   See also VECTMULT.
   'matmult --t' runs some tests.
   Usage: matc=matmult(mata,matb,dim);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
matmult MATMULT Matrix multiplication for arrays of matrices.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vindex VINDEX Indexes an N-D array along a specified dimension.
This function is called by:
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
matinv MATINV Fast inversion of arrays of small matrices.
matmult MATMULT Matrix multiplication for arrays of matrices.
mspec MSPEC Multitaper power and cross spectra.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.