Description of maxmax
Home > jlab > maxmax.m
maxmax
MAXMAX(X)=MAX(X(ISFINITE(X)))
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2012 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
aresame ARESAME Test whether two N-D arrays are the same.
bindata BINDATA Rapidly sort data into adjacent bins.
cellmax CELLMAX Maximum of each element in a cell array.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
curveinterp CURVEINTERP Interpolate a field or its gradient onto a set of curves.
dawsonderiv DAWSONDERIV Derivatives of the Dawson function.
ellipseplot ELLIPSEPLOT Plot ellipses.
ellvel ELLVEL Average and instantaneous ellipse velocities.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
linecolor LINECOLOR Set line colors based on a property value within a colormap.
lonshift LONSHIFT Shifts longitude origin for plotting purposes.
materncov MATERNCOV Autocovariance function of the Matern random process.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
morlfreq MORLFREQ Compute Morlet wavelet carrier frequency given peak frequency.
morlwave MORLWAVE Morlet wavelet.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
msvd MSVD Singular value decomposition for polarization analysis.
orbitbreaks ORBITBREAKS Separate orbit into passes based on turning points.
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
ridgechains RIDGECHAINS Forms ridge curves by connecting transform ridge points.
sampletimes SAMPLETIMES Computes mean sampling intervals and their statistics.
sleptap SLEPTAP Calculate Slepian tapers.
spherecurl SPHERECURL Curl of a vector field on the surface of a sphere.
spherediv SPHEREDIV Divergence of a vector field on the surface of a sphere.
spheregrad SPHEREGRAD Gradient of a field on the surface of a sphere.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
twodsort TWODSORT Distances from data points to nearby grid points.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
twospecplot TWOSPECPLOT Plots a pair of rotary or Cartesian spectra.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.
wavetrans WAVETRANS Continuous wavelet transform.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).