Description of minmin
Home > jlab > minmin.m
minmin
MINMIN(X)=MIN(X(ISFINITE(X)))
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2012 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
bindata BINDATA Rapidly sort data into adjacent bins.
cellmin CELLMIN Minimum of each element in a cell array.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curveinterp CURVEINTERP Interpolate a field or its gradient onto a set of curves.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
linecolor LINECOLOR Set line colors based on a property value within a colormap.
lonshift LONSHIFT Shifts longitude origin for plotting purposes.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
patchcontourf PATCHCONTOURF Generate filled contours using patches, with specified colors.
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
twospecplot TWOSPECPLOT Plots a pair of rotary or Cartesian spectra.