Description of mom2cum
Home > jlab > mom2cum.m
mom2cum
MOM2CUM  Convert moments to cumulants.
   [K0,K1,...KN]=MOM2CUM(M0,M1,...MN) converts the first N moments
   M0,M1,...MN into the first N cumulants K0,K1,...KN.
   The MN and KN are all scalars or arrays of the same size.
   Note for a probability density function, M0=1 and K0=0.
   KCELL=MOM2CUM(MCELL), where MCELL is a cell array whose (N+1)th
   is the Nth moment, returns a similar cell array of cumulants.
   MOM2CUM is inverted by CUM2MOM.
   See also CUM2MOM, BELLPOLY.
   'mom2cum --t' runs a test.
   Usage: [k0,k1,k2]=mom2cum(m0,m1,m2);
          kcell=mom2cum(mcell);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
choose CHOOSE Binomial coefficient: CHOOSE(N,K) = "N choose K"
cum2mom CUM2MOM Convert cumulants to moments.
frac FRAC Fraction: FRAC(A,B)=A./B
mom2cum MOM2CUM Convert moments to cumulants.
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
mom2cum MOM2CUM Convert moments to cumulants.
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.