Description of morlwave
Home > jlab > morlwave.m
morlwave
MORLWAVE  Morlet wavelet.
   The Morlet wavelet is not recommended.  Instead use a generalized Morse
   wavelet with GAMMA set to 3.  This function is included for testing and
   comparison purposes.  See Lilly and Olhede (2009, 2012) for details.
   PSI=MORLWAVE(N,FMAX,F) returns the complex-valued Morlet wavelet of
   length N, with a peak in the frequency domain at *radian* F, based on a
   mother wavelet having a peak frequency FMAX>1.
   If F is a scalar, PSI is a column vector of length M.  If F is an
   array, PSI is a matrix of size M x LENGTH(F), with the columns in order
   of decreasing frequency.
   The peak frequency FMAX should be greater than one.  As FMAX increases
   from unity, the number of oscillations in the wavelet increases.
   Note that the wavelets are centered at the midpoint in time, row
   number ROUND(SIZE(PSI,1)/2).
   [PSI,PSIF]=MORLWAVE(N,FMAX,F) also returns a size SIZE(PSI) matrix
   PSIF which is the frequency-domain version of the wavelets.
   For further details on this representation of the Morlet wavelet, see
   Appendix A of
       Lilly and Olhede (2009).  Higher-order properties of analytic
           wavelets.  IEEE Trans. Sig. Proc., 57 (1), 146--160.
   _________________________________________________________________
   Normalization
   MORLWAVE supports two kinds of normalization for the wavelets.
   MORLWAVE(..., 'bandpass') uses "bandpass normalization", the
   default.  See Lilly and Gascard (2006).  This implies that the
   FFT of wavelet has a maximum value of 2.
   MORLWAVE(..., 'energy') uses the unit energy normlization.  The
   time-domain wavelet energy SUM(ABS(PSI).^2) is then unity.
   Note MORLWAVE now uses bandpass-normalization by default.
   _________________________________________________________________
   See also MORLFREQ, MORLPROPS, MORSEWAVE.
   Usage: psi=morlwave(n,fmax,f);
          [psi,psif]=morlwave(n,fmax,f);
   'morlwave --t' run a test.
   'morlwave --f' generates a sample figure.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 F. Rekibi and J. M. Lilly
                         --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
morlfreq MORLFREQ Compute Morlet wavelet carrier frequency given peak frequency.
morlwave MORLWAVE Morlet wavelet.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
uvplot UVPLOT Plots the real and imaginary parts of a signal on the same axis.
vlines VLINES Add vertical lines to a plot.
This function is called by:
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
morlwave MORLWAVE Morlet wavelet.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
wigdist WIGDIST Wigner distribtion (alias-free algorithm).