Description of morlfreq
Home > jlab > morlfreq.m
morlfreq
MORLFREQ  Compute Morlet wavelet carrier frequency given peak frequency.
   FNU=MORLFREQ(FMAX), where FMAX is the desired peak frequency of the a
   Morlet wavelet, returns the appropriate carrier wave frequency FNU.
   The Morlet wavelet carrier wave and peak frequency differ on account
   of the correction term which ensures zero mean.
   Note that FMAX and FNU are both *radian* as in cos(omega t) and not
   cyclic as in in cos(2 pi f t).
   [FNU,FMIN]=MORLFREQ(FMAX) also returns the (radian) frequency at which
   the Morlet wavelet obtains a minimum, which occurs for FMIN<0.
   For details see Appendix A of
       Lilly and Olhede (2009).  Higher-order properties of analytic
          wavelets.  IEEE Trans. Sig. Proc., 57 (1), 146--160.
   'morlfreq --t' runs a test.
   'morlfreq --f' generates a sample figure.
   Usage: fnu=morlfreq(fmax);
          [fnu,fmin]=morlfreq(fmax);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008--2013 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
dlines DLINES Add diagonal lines to a plot.
frac FRAC Fraction: FRAC(A,B)=A./B
hlines HLINES Add horizontal lines to a plot.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
morlfreq MORLFREQ Compute Morlet wavelet carrier frequency given peak frequency.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
This function is called by:
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
morlfreq MORLFREQ Compute Morlet wavelet carrier frequency given peak frequency.
morlwave MORLWAVE Morlet wavelet.