Description of morsearea
Home > jlab > morsearea.m
morsearea
MORSEAREA  Time-frequency concentration area of Morse wavelets. [with F. Rekibi]
   A=MORSEAREA(C,GAMMA,BETA) calculates the area of time/frequency
   concentration region for the generalized Morse wavelets specified by
   parameters C, GAMMA, and BETA.
   The input parameters may either be arrays of the same size, or some
   may be arrays and the others scalars.
   MORSEAREA uses the area formula of Olhede and Walden (2002),
   "Generalized Morse Wavelets", at the bottom right of page 2664,
   multiplied by a factor of 1/2 to obtain the "one-sided" area.
   See also MORSECFUN, MORSEREGION.
   'morsearea --f' generates a sample figure.
   Usage: A = morsearea(C,ga,be);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 F. Rekibi and J. M. Lilly
                         --- type 'help jlab_license' for details
This function calls:
morsearea MORSEAREA Time-frequency concentration area of Morse wavelets. [with F. Rekibi]
xlog XLOG Sets x-axis scale to logarithmic.
This function is called by:
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
morsearea MORSEAREA Time-frequency concentration area of Morse wavelets. [with F. Rekibi]