Description of morseprops
Home > jlab > morseprops.m
morseprops
MORSEPROPS  Properties of the demodulated generalized Morse wavelets.
   [P,SKEW,KURT]=MORSEPROPS(GAMMA,BETA) returns properties of the
   demodulated generalized Morse wavelet specified by GAMMA and BETA.
   P is the dimensionless time-domain window width.
   SKEW is the imaginary part of normalized third moment of the
   time-domain demodulate, or 'demodulate skewness'.
   KURT is the normalized fourth moment of the time-domain demodulate,
   or 'demodulate kurtosis'.
   See Lilly and Olhede (2008b) for details.
   See also MORSEFREQ, MORSEBOX, MORSEWAVE.
   'morseprops --t' runs a test.
   Usage: [p,skew,kurt]=morseprops(ga,be);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morseprops MORSEPROPS Properties of the demodulated generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
This function is called by:
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
morseprops MORSEPROPS Properties of the demodulated generalized Morse wavelets.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.