Description of morsefreq
Home > jlab > morsefreq.m
morsefreq
MORSEFREQ  Frequency measures for generalized Morse wavelets. [with F. Rekibi]
   [FM,FE,FI]=MORSEFREQ(GAMMA,BETA) calculates three different measures of
   the frequency of the lowest-order generalized Morse wavelet specified
   by parameters GAMMA and BETA.
   FM is the modal or peak, FE is the "energy" frequency, and FI is the
   instantaneous frequency at the wavelet center.
   [FM,FE,FI,CF]=MORSEFREQ(GAMMA,BETA) also computes the curvature CF of
   the instantaneous frequency at the wavelet center.
   Note that all frequency quantities here are *radian* as in cos(omega t)
   and not cyclic as in cos(2 pi f t).
   The input parameters must either be matrices of the same size,
   or some may be matrices and the others scalars.
   For BETA=0, the "wavelet" becomes an analytic lowpass filter, and FM
   is not defined in the usual way.  Instead the 1/2 power point of the
   analytic bandpass filter is returned for FM.
   For details see
       Lilly and Olhede (2009).  Higher-order properties of analytic
           wavelets.  IEEE Trans. Sig. Proc., 57 (1), 146--160.
   See also MORSEBOX, MORSEPROPS, MORSEWAVE.
   Usage: fm = morsefreq(ga,be);
          [fm,fe,fi] = morsefreq(ga,be);
          [fm,fe,fi,cf] = morsefreq(ga,be);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J. M. Lilly and F. Rekibi
                         --- type 'help jlab_license' for details
This function calls:
fixlabels FIXLABELS Specify precision of axes labels.
frac FRAC Fraction: FRAC(A,B)=A./B
hlines HLINES Add horizontal lines to a plot.
imlog IMLOG Imaginary part of log: IMLOG(X)=UNWRAP(IMAG(LOG(X)))
letterlabels LETTERLABELS For automatically putting letter labels on subplots.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
morlwave MORLWAVE Morlet wavelet.
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
vdiff VDIFF Length-preserving first central difference.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
xtick XTICK Sets locations of x-axis tick marks.
ytick YTICK Sets locations of y-axis tick marks.
This function is called by:
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
morsea MORSEA Returns the generalized Morse wavelet amplitude "a".
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsederiv MORSEDERIV Frequency-domain derivatives of generalized Morse wavelets.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
morseproj MORSEPROJ Projection coefficient for two generalized Morse wavelets.
morseprops MORSEPROPS Properties of the demodulated generalized Morse wavelets.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
morsexpand MORSEXPAND Generalized Morse wavelets via time-domain Taylor series.
ridgeinterp RIDGEINTERP Interpolate quantity values onto ridge locations.