Description of morsemom
Home > jlab > morsemom.m
morsemom
MORSEMOM  Frequency-domain moments of generalized Morse wavelets.
   MORSEMOM is a low-level function called by several other Morse wavelet
   functions.
   [MP,NP]=MORSEMOM(P,GAMMA,BETA) computes the Pth order frequency-
   domain moment M and energy moment N of the lower-order generalized
   Morse wavelet specified by parameters GAMMA and BETA.
   The Pth moment and energy moment are defined as
           mp = 1/(2 pi) int omega^p  psi(omega)     d omega
           np = 1/(2 pi) int omega^p |psi(omega)|.^2 d omega
   respectively, where omega is the radian frequency.  These are
   evaluated using the normalization that max(abs(psi(omega)))=2.
   The input parameters must either be matrices of the same size, or
   some may be matrices and the others scalars.
   [MP,NP,KP,LP]=MORSEMOM(...) also returns the Pth order cumulant KP and
   the Pth order energy cumulant LP.
   For details see
       Lilly and Olhede (2009).  Higher-order properties of analytic
           wavelets.  IEEE Trans. Sig. Proc., 57 (1), 146--160.
   See also MORSEWAVE, MORSEDERIV, MOM2CUM.
   'morsemom --t' runs some tests.
   Usage:  mp=morsemom(p,ga,be);
           [mp,np]=morsemom(p,ga,be);
           [mp,np,kp,lp]=morsemom(p,ga,be);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
mom2cum MOM2CUM Convert moments to cumulants.
morsea MORSEA Returns the generalized Morse wavelet amplitude "a".
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
vsum VSUM Sum over finite elements along a specified dimension.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
This function is called by:
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
mom2cum MOM2CUM Convert moments to cumulants.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
morsexpand MORSEXPAND Generalized Morse wavelets via time-domain Taylor series.