Description of morsederiv
Home > jlab > morsederiv.m
morsederiv
MORSEDERIV  Frequency-domain derivatives of generalized Morse wavelets.
   DCELL=MORSEDERIV(N,GAMMA,BETA,OMEGA) returns the first N normalized
   frequency derivatives of the lowest-order generalized Morse wavelet
   specified by parameters GAMMA and BETA, at the radian frequency OMEGA.
   DCELL is a cell array with DCELL{N} containing the Nth derivative.
   This derivative is defined as
           dn = ( omega^n / psi ) * ( d^n psi / d omega^n )
   where omega is the radian frequency and psi is the wavelet.
   N must be a scalar. The other input parameters must either be matrices
   of the same size, or some may be matrices and the others scalars.
   DCELL=MORSEDERIV(N,GAMMA,BETA) evaluates the derivative at the peak
   frequency by default.
   For details see
       Lilly and Olhede (2009).  Higher-order properties of analytic
           wavelets.  IEEE Trans. Sig. Proc., 57 (1), 146--160.
   See also MORSEWAVE, MORSEMOM, BELLPOLY.
   'morsewave --t' runs a test.
   Usage: dcell=morsederiv(4,gamma,beta,omega);
          dcell=morsederiv(4,gamma,beta);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2009 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
cum2mom CUM2MOM Convert cumulants to moments.
morsederiv MORSEDERIV Frequency-domain derivatives of generalized Morse wavelets.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
This function is called by:
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
morsederiv MORSEDERIV Frequency-domain derivatives of generalized Morse wavelets.