Description of morsebox
Home > jlab > morsebox.m
morsebox
MORSEBOX  Heisenberg time-frequency box for generalized Morse wavelets.
   A=MORSEBOX(GAMMA,BETA) returns the time-bandwidth product of the
   a generalized Morse wavelet, that is, the area of its Heisenberg box.
   [A,SIGT,SIGO,SKEW]=MORSEBOX(GAMMA,BETA) also returns the box width in
   time SIGT and in frequency SIGO, with A=SIGT*SIGO, as well as the
   frequency-domain skewness SKEW.
   Both SIGT and SIGO are non-dimensionalized with respect to the (radian)
   peak frequency MORSEFREQ, as in Lilly and Olhede (2009) given below.
   Not for all values of BETA and GAMMA are these standard derivations
   defined as real-valued quantities.  For locations where these would
   be imaginary, their values are set to NAN.
   For details see
       Lilly and Olhede (2009).  Higher-order properties of analytic
           wavelets.  IEEE Trans. Sig. Proc., 57 (1), 146--160.
   In this calculation, care is taken to avoid potential problems caused
   by large arguments to the gamma function, by utilizing GAMMALN.  This
   lets the Heisenberg area be computed for small values of GAMMA/BETA.
   See also MORSEFREQ, MORSEPROPS, MORSEWAVE.
   'morsebox --t' runs a test.
   'morsebox --f' generates a sample figure.
   Usage: a=morsebox(ga,be);
          [a,sigt,sigo]=morsebox(ga,be);
          [a,sigt,sigo,skew]=morsebox(ga,be);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
flipmap FLIPMAP Flips the current colormap upside-down.
frac FRAC Fraction: FRAC(A,B)=A./B
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vlines VLINES Add vertical lines to a plot.
xtick XTICK Sets locations of x-axis tick marks.
ytick YTICK Sets locations of y-axis tick marks.
This function is called by:
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).