Description of morseproj
Home > jlab > morseproj.m
morseproj
MORSEPROJ  Projection coefficient for two generalized Morse wavelets.
   MORSEPROJ is a low-level function called by MORSEWAVE.
   B=MORSEPROJ(GA,BE1,BE2) returns the projection coefficient B for the
   projection of one generalized Morse wavelet onto another.
   The first generalized Morse has parameters GA and BE1, and the second
   has parameters GA and BE2.
   'morseproj --t' runs a test.
   Usage: b=morseproj(ga,be1,be2);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
morsea MORSEA Returns the generalized Morse wavelet amplitude "a".
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morseproj MORSEPROJ Projection coefficient for two generalized Morse wavelets.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vrep VREP Replicates an array along a specified dimension.
vsum VSUM Sum over finite elements along a specified dimension.
This function is called by:
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
morseproj MORSEPROJ Projection coefficient for two generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).