Description of morsexpand
Home > jlab > morsexpand.m
morsexpand
MORSEXPAND  Generalized Morse wavelets via time-domain Taylor series.
   PSI=MORSEXPAND(T,GAMMA,BETA,FS) computes the lowest-order generalized
   Morse wavelet specified by parameters GAMMA and BETA, and having a peak
   frequency at *radian* frequency FS, using a time-domain Taylor series.
   Normally one would use MORSEWAVE to compute the wavelets in the
   frequency domain, but it is sometimes useful to have an explicit
   time-domain representation.
   There are no contraints on the size of T nor its ordering.
   All input parameters other than T should be scalars.
   __________________________________________________________________
   Algorithms
   MORSEXPAND can use one of two different algorithms.
   MORSEXPAND(,...,'moment'), the default behavior,  Taylor-expands the
   time-domain wavelet directly.
   MORSEXPAND(,...,'cumulant') expands the logarithm of the time-domain
   wavelet and then takes the exponential.
   MORSEXPAND(N,...) specifies the number of terms to include in the
   Taylor expansion.  N defaults to 10 in the 'cumulant' case and 100 in
   the 'moment' case.
   These algorithms implement equations (30) and (31) of Lilly and
   Olhede (2009).
   For details see
       Lilly and Olhede (2009).  Higher-order properties of analytic
           wavelets.  IEEE Trans. Sig. Proc., 57 (1), 146--160.
   __________________________________________________________________
   See also MORSEWAVE, WAVETRANS.
   'morsexpand --t' runs a test.
   Usage: psi=morsexpand(t,gamma,beta,fs);
          psi=morsexpand(n,t,gamma,beta,fs);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
frac FRAC Fraction: FRAC(A,B)=A./B
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
morsexpand MORSEXPAND Generalized Morse wavelets via time-domain Taylor series.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vdiff VDIFF Length-preserving first central difference.
vsum VSUM Sum over finite elements along a specified dimension.
This function is called by:
instmom INSTMOM Univariate and multivariate instantaneous moments.
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
morsexpand MORSEXPAND Generalized Morse wavelets via time-domain Taylor series.