Description of morsewave
Home > jlab > morsewave.m
morsewave
 MORSEWAVE  Generalized Morse wavelets of Olhede and Walden (2002).
   PSI=MORSEWAVE(N,GAMMA,BETA,FS) returns an  N x LENGTH(FS) array PSI
   which contains time-domain versions of the generalized Morse wavelet
   specified by GAMMA and BETA, concentrated at frequencies FS.
   The vector FS specifically denote the *radian* frequencies at which
   the Fourier transform of the wavelets reach their maximum amplitudes.
   A set of frequencies appropriate for analyzing a given length time
   series can be easily chosen using MORSESPACE.
   Note that the wavelets are centered at the midpoint in time, that is,
   row number ROUND(SIZE(PSI,1)/2).  FS assumes a unit sample rate.
   [PSI,PSIF]=MORSEWAVE(...) optionally returns a frequency-domain version
   PSIF of the wavelets.  PSIF is the same size as PSI.
   _________________________________________________________________
   Normalization
   MORSEWAVE supports two kinds of normalization for the wavelets.
   MORSEWAVE(...,'bandpass') uses "bandpass normalization", meaning that
   the FFT of the wavelet has a peak value of 2 for all frequencies FS.
   MORSEWAVE(...,'energy') uses the unit energy normlization.  The time-
   domain wavelet energy SUM(ABS(PSI).^2,1) is then always unity.
   The bandpass normalization corresponds to having 1/S in the time-domain
   wavelet transform defintion, where S is the scale, while the unit
   energy normalization corresponds to 1/SQRT(S).
   MORSEWAVE uses bandpass normalization by default.
   _________________________________________________________________
   Multiple orthogonal wavelets
   MORSEWAVE can compute multiple orthogonal versions of the generalized
   Morse wavelets, characterized by the order K.
   PSI=MORSEWAVE(N,K,GAMMA,BETA,FS) with a fifth numerical argument K
   returns an N x LENGTH(FS) x K array PSI which contains time-domain
   versions of the first K orthogonal generalized Morse wavelets.
   These K different orthogonal wavelets have been employed in
   multiwavelet polarization analysis, see Olhede and Walden (2003a,b).
   Again either bandpass or energy normalization can be applied.  With
   bandpass normalization, all wavelets are divided by a constant, setting
   the peak value of the first frequency-domain wavelet equal to 2.
   _________________________________________________________________
   Background
   For further details on generalized Morse wavelets, see the following
   publications.
     Lilly and Olhede (2012), Generalized Morse wavelets as a superfamily
        of analytic wavelets. IEEE Trans. Sig. Proc., 60 (11), 6036--6041.
     Lilly and Olhede (2009),  Higher-order properties of analytic
         wavelets.  IEEE Trans. Sig. Proc., 57 (1), 146--160.
     Olhede and Walden (2002),  Generalized Morse Wavelets. IEEE Trans.
         Sig. Proc., 50 (11), 2661--2670.
   _________________________________________________________________
   'morsewave --t' runs a test
   'morsewave --f' generates a sample figure
   Usage: psi=morsewave(N,ga,be,fs);
          [psi,psif]=morsewave(N,ga,be,fs,'bandpass');
          [psi,psif]=morsewave(N,K,ga,be,fs,'energy');
          [psi,psif]=morsewave(N,K,ga,be,fs,'bandpass');
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J.M. Lilly and F. Rekibi
                         --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
dawson DAWSON The Dawson function. [By P.J. Acklam]
dawsonderiv DAWSONDERIV Derivatives of the Dawson function.
frac FRAC Fraction: FRAC(A,B)=A./B
hermpoly HERMPOLY Hermite polynomials. [with F. Rekibi]
hlines HLINES Add horizontal lines to a plot.
iseven ISEVEN True for even integer values; false otherwise.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
minmin MINMIN(X)=MIN(X(ISFINITE(X)))
morsea MORSEA Returns the generalized Morse wavelet amplitude "a".
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morseproj MORSEPROJ Projection coefficient for two generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
oprod OPROD Outer product: OPROD(X,Y)=X*CONJ(Y')
packfig PACKFIG Squeeze together rows and/or columns of the current figure.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
uvplot UVPLOT Plots the real and imaginary parts of a signal on the same axis.
vcolon VCOLON Condenses its arguments, like X(:).
vlines VLINES Add vertical lines to a plot.
vrep VREP Replicates an array along a specified dimension.
vsum VSUM Sum over finite elements along a specified dimension.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
This function is called by:
instmom INSTMOM Univariate and multivariate instantaneous moments.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morseprops MORSEPROPS Properties of the demodulated generalized Morse wavelets.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
morsexpand MORSEXPAND Generalized Morse wavelets via time-domain Taylor series.
msvd MSVD Singular value decomposition for polarization analysis.
wavetrans WAVETRANS Continuous wavelet transform.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).