Description of msvd
Home > jlab > msvd.m
msvd
MSVD  Singular value decomposition for polarization analysis.
   MSVD computes the singular value decomposition for multiple-
   transform polarization analysis at all or selected frequencies.
   [D,U1,V1]=MSVD(W) computes the singular value decomposition of
   sub-matrices of the eigentransform W.
   The input matrix W is an J x N x K matrix where
          J is the number of transforms (frequencies or scales)
          N is the number of dataset components
          K is the number of eigentransforms (tapers or wavelets)
   The output is
           D  --  J x MIN(K,N) matrix of singular values
          U1  --  J x N matrix of first left singular vectors
          V1  --  J x K matrix of first right singular vectors
   The left singular vectors U1 are the eigenvectors of the spectral
   matrix, while the right singular vectors V1 are the eigenvectors of
   the "structure matrix".
   W may optionally be of size M x J x N x K, in which case the
   output arguments are all three-dimensional matrices with sizes
           D  --  M x J x MIN(K,N) matrix of singular values
          U1  --  M x J x N matrix of first left singular vectors
          V1  --  M x J x K matrix of first right singular vectors
   [D,U1,V1]=MSVD(W,INDEX) for three-dimensional W optionally
   performs the SVD only at the rows of MMAT indicated by INDEX.  The
   output arguments then all have LENGTH(INDEX) rows rather than M.
   [D,U1,V1,TR]=MSVD optionally outputs TR, the trace of the spectral
   matrix, which is of size J (for 3-D W) or M x J (for 4-D W).
   MSVD(..., 'quiet') suppresses a progress report.
   Usage:  [d,u1,v1]=msvd(w);
           [d,u1,v1]=msvd(w,index);
           [d,u1,v1,tr]=msvd(w,index);
   'msvd --t' runs a test.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 1993--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
anatrans ANATRANS Analytic part of signal.
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
msvd MSVD Singular value decomposition for polarization analysis.
oprod OPROD Outer product: OPROD(X,Y)=X*CONJ(Y')
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
vrep VREP Replicates an array along a specified dimension.
vsum VSUM Sum over finite elements along a specified dimension.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.
wavetrans WAVETRANS Continuous wavelet transform.
This function is called by:
jspectral jSpectral: Multitaper spectral analysis, and other time series tools
msvd MSVD Singular value decomposition for polarization analysis.