Description of nocontours
Home > jlab > nocontours.m
nocontours
NOCONTOURS  Removes contours from a CONTOURF plot.
   NOCONTOURS(H) where H is an array of handles to lines, output by
   CONTOURF, sets the linestyle for all the lines to 'none'.  This
   removes the contours from the CONTOURF plot.
   NOCONTOURS with no input arguments sets the linestyle of all patch
   objects (for Matlab versions < 2014b) or all contour objects (for
   versions 2014b and later) in the current axes to 'none'.
   H=NOCONTOURS also returns the handles to the objects.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2009--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
topoplot TOPOPLOT Plot regional or global topography at one-sixth degree resolution.