Description of nonnan
Home > jlab > nonnan.m
nonnan
NONNAN  Return all non-NAN elements of an array.
   NONNAN(X) is equivalent to X(FIND(~ISNAN(X))).
   The empty set is returned if all elements of X are NANS.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2007 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
cellchunk CELLCHUNK Converts cell array data into uniform length 'chunks'.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
ridgechains RIDGECHAINS Forms ridge curves by connecting transform ridge points.
ridgeinterp RIDGEINTERP Interpolate quantity values onto ridge locations.
twodmed TWODMED Median value of a function of two variables.