Description of noxlabels
Home > jlab > noxlabels.m
noxlabels
NOXLABELS   Remove some or all x-axis tick mark labels.
   NOXLABELS by itself removes all tick mark labels on the current x-axis.
   NOXLABELS MAX removes only the label of the maximum x-tick mark.
   NOXLABELS MIN removes only the label of the minimum x-tick mark.
   NOXLABELS ALL is the same as the default.
   See also NOYLABELS.
   Usage:  noxlabels
           noxlabels xmin
           noxlabels ymin
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2008 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
packfig PACKFIG Squeeze together rows and/or columns of the current figure.