Description of noylabels
Home > jlab > noylabels.m
noylabels
NOYLABELS   Remove some or all y-axis tick mark labels.
   NOYLABELS by itself removes all tick mark labels on the current y-axis.
   NOYLABELS MAX removes only the label of the maximum y-tick mark.
   NOYLABELS MIN removes only the label of the minimum y-tick mark.
   NOYLABELS ALL is the same as the default.
   See also NOXLABELS.
   Usage:  noylabels
           noylabels xmin
           noylabels ymin
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2008 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
packfig PACKFIG Squeeze together rows and/or columns of the current figure.