Description of oprod
Home > jlab > oprod.m
oprod
OPROD  Outer product:  OPROD(X,Y)=X*CONJ(Y')
   OPROD(X,Y) calculates the outer product of two column vectors X and Y.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2003--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
maternedge MATERNEDGE Long-time cutoff edge for the Matern impulse response function.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
msvd MSVD Singular value decomposition for polarization analysis.
slidetrans SLIDETRANS Sliding-window ('moving-window') Fourier transform.
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.
wavetrans WAVETRANS Continuous wavelet transform.