Description of orbitbreaks
Home > jlab > orbitbreaks.m
orbitbreaks
ORBITBREAKS  Separate orbit into passes based on turning points.
   ORBITBREAKS is a level function called by ABOUT_ALONGTRACK.
   [LAT,LON]=ORBITBREAKS(LAT,LON), where LAT and LON are column vectors
   representing a satellite orbital groundtrack, is used to separate
   different passes based on the turning points in latitude.
   NANs are inserted into both LAT and LON wherever LAT has a turning
   point.  Note that no data is removed.
   All latitudes and lontidues are in degrees.  The output longitude has
   range [-180, 180].
   Calling COL2MAT(LAT,LON) will then reshape LAT and LON into matrices,
   with each orbital pass in its own column.
   [LAT,LON,X1,X2,... XN]=ORBITBREAKS(LAT,LON,X1,X2,... XN) will insert
   NANs into the other arguments in the same locations as for LAT and LON.
   The input arguments should contain no NANs.  For missing data, use INFs
   instead.
   ORBITBREAKS(LAT,LON, ...) with no output arguments overwrites the
   original variables.
   See also COLBREAKS, COL2MAT.
   'orbitbreak --t' runs a test.
   Usage: [lat,lon]=orbitbreaks(lat,lon);
          [lat,lon,x1,x2,x3]=orbitbreaks(lat,lon,x1,x2,x3);
          orbitbreaks(lat,lon);
          orbitbreaks(lat,lon,x1,x2,x3);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2006--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
anyany ANYANY(X)=ANY(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
colbreaks COLBREAKS Insert NANs into discontinuties in a vector.
deg180 DEG180 Converts degrees to the range [-180,180].
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
orbitbreaks ORBITBREAKS Separate orbit into passes based on turning points.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
joceans jOceans: Oceanography-specific data and model analysis tools
orbitbreaks ORBITBREAKS Separate orbit into passes based on turning points.