Description of packfig
Home > jlab > packfig.m
packfig
PACKFIG  Squeeze together rows and/or columns of the current figure.
   PACKFIG(M,N) squeezes together all rows and columns in the current
   figure, which has M rows and N columns generated with SUBPLOT. This is
   used when all subplots in a given column share common x- and y-axes.
   PACKFIG(M,N,'columns') only packs the columns, and not the rows.
   PACKFIG(M,N,'rows') only packs the rows, and not the columns.
   When the columns are packed, the Y-axis tick labels for the interior
   subplots are removed.  Similarly, when the rows are packed, the X-axis
   tick labels for the interior subplots are removed.
   H=PACKFIG(M,N) returns a vector of handles H into the subplots.
   PACKFIG(H,M,N) also works, where H is a vector of handles.
   After calling PACKFIG, do not call SUBPLOT again, as this will destroy
   the subplots; instead, access the subplots through AXES(H(I)) where I
   is an integer.
   _________________________________________________________________
   Use with AXIS EQUAL
   PACKFIG, PACKROWS, and PACKCOLS may not work when AXIS EQUAL and
   AXIS([A B C D]) are used together because of the way Matlab constricts
   the figure with AXIS EQUAL. Consider altering the aspect ratio with
       set(gcf,'paperposition',[ left, bottom, width, height])
   or
       set(gcf,'position',[ left, bottom, width, height])
   in order to obtain the desired result.
   [Thanks to JLAB user Rodrigo Duran for this note.]
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
boxoff BOXON Sets 'box' property to 'off'.
frac FRAC Fraction: FRAC(A,B)=A./B
noxlabels NOXLABELS Remove some or all x-axis tick mark labels.
noylabels NOYLABELS Remove some or all y-axis tick mark labels.
This function is called by:
divgeom DIVGEOM Geometric decomposition of eddy vorticity flux divergence.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
twospecplot TWOSPECPLOT Plots a pair of rotary or Cartesian spectra.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).