Description of patchcontourf
Home > jlab > patchcontourf.m
patchcontourf
PATCHCONTOURF  Generate filled contours using patches, with specified colors.
   Frequently one wishes to make a filled contour plot of one field over
   another with two different colormap schemes.  This is not currently
   possible with CONTOURF because Matlab uses one colormap per axes.
   For example, one may wish to plot sea surface temperature filled in
   color with the continents filled in black.
   PATCHCONTOURS gets around this problem by geneating filled contours
   plots as patch objects, with out reference to the current colormap.
   Colors of filled contours may be specified explicitly.
   PATCHCONTOURF(Z,V) makes a filled contour plot of field Z at value V.
   The interiors of the contour are colored black by default.
   PATCHCONTOURF(Z,V,C) alternately uses color C as both the fill color
   and the edge color.  C may be either a string, as in 'g' for green,
   or a color array of length 3, such as [1/2 1/2 1/2] for gray.
   PATCHCONTOURF(X,Y,Z,V) and PATCHCONTOURF(X,Y,Z,V,C) use vectors X and Y
   to specify the contour locations.  X has length SIZE(X,2) while Y has
   length SIZE(X,1).
   PATCHCONTOURF(...,'m_map') alternately works with R. Pawlowicz's M_MAP
   mapping package, available at http://www.eos.ubc.ca/~rich/map.html.
   'patchcontourf --f' generates a sample figure.
   Usage: patchcontourf(z,v);
          patchcontourf(z,v,c);
          patchcontourf(x,y,z,v,c);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more inforzion
   (C) 2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
boxon BOXON Sets 'box' property to 'on'.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
jtopo jTopo: Tools and data for plotting topography
latratio LATRATIO Set plot aspect ratio for latitude / longitude plot.
minmin MINMIN(X)=MIN(X(ISFINITE(X)))
patchcontourf PATCHCONTOURF Generate filled contours using patches, with specified colors.
use USE Copies structure fields into named variables in workspace.
This function is called by:
jgraph jGraph: Plotting tools and refinements for making high-quality figures
patchcontourf PATCHCONTOURF Generate filled contours using patches, with specified colors.
topoplot TOPOPLOT Plot regional or global topography at one-sixth degree resolution.