Description of pdfprops
Home > jlab > pdfprops.m
pdfprops
PDFPROPS  Mean and variance associated with a probability distribution.
   [MU,SIGMA]=PDFPROPS(X,FX), given a probability distribution function FX
   over values X, returns the mean MU and the standard deviation SIGMA.
   The statistics are computed using a trapezoidal integration.  FX is
   multiplied by a constant so that it integrates to one.
   [MU,SIGMA,SKEW,KURT]=PDFPROPS(X,FX) also retuns the skewness and the
   kurtosis, which are the third and fourth central moments, respectively
   normalized by the third and fourth powers of the standard deviation.
   PDFPROPS(X,FX,DIM) alternately computes moments along dimension DIM.
   By default, DIM=1, so the moments are computed along rows.
   'pdfprops --t' runs a test.
   Usage:  [mu,sigma]=pdfprops(x,fx);
           [mu,sigma,skew,kurt]=pdfprops(x,fx);
           [mu,sigma,skew,kurt]=pdfprops(x,fx,dim);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2001--2013 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
simplepdf SIMPLEPDF Gaussian, uniform, Cauchy, and exponential pdfs.
vindex VINDEX Indexes an N-D array along a specified dimension.
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
vrep VREP Replicates an array along a specified dimension.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
vsum VSUM Sum over finite elements along a specified dimension.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
This function is called by:
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morseprops MORSEPROPS Properties of the demodulated generalized Morse wavelets.
pdfprops PDFPROPS Mean and variance associated with a probability distribution.