Description of periodize
Home > jlab > periodize.m
periodize
PERIODIZE  Returns a doubly periodic version of an input array.
   [XP,YP,FP]=PERIODIZE(X,Y,F) takes the matrix F and forms a doubly-
   periodic version FP, which will be 3*SIZE(F).
   XP and YP are the new X and Y axes extended based on the delta-X and
   delta-Y values within X and Y.  X and Y must both have uniform spacing.
   [XE,YE,FP]=PERIODIZE(N,X,Y,F) only extends F periodically by N points,
   so that FP is SIZE(F,1)+2*N by SIZE(F,2)+2*N.
   [XE,YE,FP]=PERIODIZE(N,M,X,Y,F) extends F periodically by N points in
   the X-direction, corresponding to the *columns* of F, and by M points
   in the Y-direction, corresponding to the *rows* of F.
   Thus in this case FP will be SIZE(F,1)+2*M by SIZE(F,2)+2*N.
   F may have multiple higher dimensions, for example a third dimension
   corresponding to time.  Only the first two dimensions are periodized.
   For singly periodic versions, use PERIODIZE(0,M,F) or PERIODIZE(N,0,F).
   [XP,YP,F1P,F2P,...,FKP]=PERIODIZE(...,X,Y,F1,F2,...,FK) also works,
   and returns periodized versions of all the K arrays F1, F2,...,FK.
   'periodize --t' runs a test.
   'periodize --f' generates a sample figure.
   Usage: [xp,yp,fp]=periodize(x,y,f);
          [xp,yp,fp]=periodize(N,x,y,f);
          [xp,yp,fp]=periodize(N,M,x,y,f);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
anyany ANYANY(X)=ANY(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
hlines HLINES Add horizontal lines to a plot.
periodize PERIODIZE Returns a doubly periodic version of an input array.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vdiff VDIFF Length-preserving first central difference.
vlines VLINES Add vertical lines to a plot.
vstd VSTD Standard deviation over finite elements along a specfied dimension.
xtick XTICK Sets locations of x-axis tick marks.
ytick YTICK Sets locations of y-axis tick marks.
This function is called by:
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
joceans jOceans: Oceanography-specific data and model analysis tools
periodize PERIODIZE Returns a doubly periodic version of an input array.