Description of polparams
Home > jlab > polparams.m
polparams
 POLPARAM  Spectral matrix polarization parameters.
   [E,P,ALPHA,BETA]=POLPARAMS(S) where S is a 2x2 spectral matrix returns
   the energy E and the polarization paramters P, ALPHA, and BETA.
   If S is a 2 x 2 x M matrix, then all output variables are Mx1 column
   vectors.  More generally, if S is 2 x 2 x M x ... N, then all output
   variables are M x ... N.
   [...]=POLPARAMS(SXX,SXY,SXY) also works. In this case all input
   variables are matrices of the same size.
   [E,P,ALPHA,BETA,PREAL,GAMMA]=POLPARAMS(S) also optionally retuns the
   polarization ratio of the real part of S and the coherence GAMMA.
   See also SPECDIAG.
   Usage:  [E,p,alpha,beta]=polparams(s);
           [E,p,alpha,beta,preal,gamma]=polparams(s);
           [E,p,alpha,beta,preal,gamma]=polparams(sxx,syy,sxy);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2012 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
frac FRAC Fraction: FRAC(A,B)=A./B
This function is called by:
jspectral jSpectral: Multitaper spectral analysis, and other time series tools
specdiag SPECDIAG Diagonalize a 2 x 2 spectral matrix.