Description of polysmooth
Home > jlab > polysmooth.m
polysmooth
POLYSMOOTH  Smoothing scattered 2D data with local polynomial fitting.
   POLYSMOOTH generates a map from scattered data in two dimensions---
   either on the plane or on the sphere---using a local least squares fit
   to a polynomial.
   A numerically efficient algorithm is used that avoids explicit loops.
   Also, the data are pre-sorted so that different mapping parameters can
   be tried out at little computational expense.
   A reference paper for this function is currently in preparation.  In
   the meantime, for more details see the following book:
      Fan and Gijbels, 1996.  Local polynomial modelling and its
          applications. Chapman and Hall.
   __________________________________________________________________
   Smoothing on the plane
   Let's say we have an array Z of data is at locations X,Y, where X,Y,
   and Z are all arrays of the same size.  The problem is to obtain a
   mapped field ZHAT on some regular grid specified by arrays XO and YO.
   Calling POLYSMOOTH is a two-step process:
       [DS,XS,YS,ZS]=TWODSORT(X,Y,Z,XO,YO,CUTOFF);
       ZHAT=POLYSMOOTH(DS,XS,YS,ZS,B,P);
   Firstly, TWODSORT which returns ZS, a 3D array of data values at each
   grid point, sorted by increasing distance DS, and the corresponding
   positions XS and YS. Here XO and YO are arrays specifying the bin
   center locations of the grid.  See TWODSORT for more details.
   Here CUTOFF determines the maximum distance included in the sorting
   and should be chosen to be greater than B.
   Secondly, POLYSMOOTH fits a Pth order polynomial at each gridpoint
   within a neighborhood specified by the "bandwidth" B.
   Data and grid point locations are presumed to have the same units as
   the bandwidth B (e.g., kilometers).
   P may be chosen as P=0 (fit to a constant), P=1 (fit to a plane), or
   else P=2 (fit to a parabolic surface).
   POLYSMOOTH can also be used for data on the sphere, as described next.
   __________________________________________________________________
   Smoothing on the sphere
   POLYSMOOTH supports a local polynomial fit on the sphere.  As before
   this is a two-step process:
       [DS,XS,YS,ZS]=SPHERESORT(LAT,LON,Z,LATO,LONO,CUTOFF);
       ZHAT=POLYSMOOTH(DS,XS,YS,ZS,B,P,'sphere')
   Firstly one calls SPHERESORT, which is the analogue of TWODSORT for the
   sphere.  LATO and LONO are arrays specifying the bin center locations
   of the grid.  See SPHERESORT for more details.
   Secondly, POLYSMOOTH fits a Pth order polynomial at each gridpoint
   within a neighborhood specified by the "bandwidth" B.  The bandwidth
   here should have units of kilometers.
   Note that SPHERESORT and POLYSMOOTH both assume the sphere to be the
   radius of the earth, as specified by the function RADEARTH.
   __________________________________________________________________
   Additional options
   A number of different options are possible, as descibed below.  These
   are specified with trailing string arguments, which can be given in any
   order provided they are after the numeric arguments.
   __________________________________________________________________
   Weighting function
   POLYSMOOTH weights the data points in the vicinity of each grid point
   according to some decaying function of distance.
   1) Parabolic weighting
   POLYSMOOTH(...,'epa'), the default behavior, uses the Epanechnikov
   kernel --- a fancy name for a parabolic weighting function.  This
   function vanishes outside a radius of the bandwidth B.
   The Epanechnikov kernel has the numerical advantage that distances from
   far away points do not have to be computed, and is therefore preferred.
   2) Gaussian weighting:
   POLYSMOOTH(...,'gau') uses a Gaussian weighting function instead, with
   a standard deviation of B and truncated, for numerical reasons, at a
   radius of 3B.
   When using the Gaussian weighting function you'll need to call TWODSORT
   or SPHERESORT with a cutoff distance of at least 3B.
   __________________________________________________________________
   Algorithms
   POLYSMOOTH has two algorithm choices for optimal performance, both of
   which give identical answers.
   1) Speed optimization
   The default algorithm is optimized for speed but uses a great deal of
   memory.  It solves the least squares problem for all grid points
   simultaneously (by directly solving matrix inversions---see MATINV.)
   This can be greater than an order of magnitude faster than the obvious
   approach of looping over the grid points.
   2) Memory optimization
   If the data is so large that memory becomes a limiting factor, use
       ZHAT=POLYSMOOTH(DS,XS,YS,ZS,B,P,'memory');
   which performs an explicit loop.
   __________________________________________________________________
   Weighted data points
   POLYSMOOTH can also incorporate a weighting factor on the data points.
   Let W be an array of positive values the same size as the data array Z.
   Each data point is then treated as if it were W data points.
   To use weighted data points, call TWODSORT or SPHERESORT with W added:
       [DS,XS,YS,ZS,WS]=TWODSORT(X,Y,Z,W,XO,YO,CUTOFF);
    or [DS,XS,YS,ZS,WS]=SPHERESORT(LAT,LON,Z,W,LATO,LONO,CUTOFF);
   followed by    ZHAT=POLYSMOOTH(DS,XS,YS,ZS,WS,B,P);
            or    ZHAT=POLYSMOOTH(DS,XS,YS,ZS,WS,B,P,'sphere');
   for data distributed on the plane or on the sphere, respectively.
   For very large datasets, this is useful in first condensing the data
   into a manageable size.
   __________________________________________________________________
   Additional output arguments
   [ZHAT,WEIGHT]=POLYSMOOTH(...) also returns the total weight used in
   the computation at each grid point.  WEIGHT is the same size as ZHAT.
   Small weights mean that only few or far away data points contributed
   to the calculation; therefore, the values of ZHAT at these points
   are less reliable than at points where the total weight is large.
   [ZHAT,WEIGHT,BETA]=POLYSMOOTH(...) additionally returns the matrix
   of the estimated first P derivatives.  BETA is 3D and is the same
   size as ZHAT and WEIGHT along its first two dimensions.
   BETA(:,:,1) is the estimated zeroth derivative, i.e. the surface, so
   this is the same as ZHAT.
   __________________________________________________________________
   Variable bandwidth
   ZHAT=POLYSMOOTH(...,N,P,'variable') uses the parameter N instead of a
   fixed bandwidth.  The bandwidth now varies over the grid such that N
   points fall within one bandwidth distance from every grid point.
   [ZHAT,WEIGHT,BETA,B]=POLYSMOOTH(...,N,P,'variable') returns the
   bandwidth B at each grid point, which is the same size as ZHAT.
   The variable bandwidth algorithm can give good results when the data
   spacing is highly uneven, particularly when used with a higher-order
   (P=1 or P=2) fit.
   When using the variable bandwidth method, be aware that the bandwidth
   necessary to include N points may turn out to be larger than CUTOFF,
   the maximum distance value given to TWODSORT or SPHERESORT.
   __________________________________________________________________
   'polysmooth --t' runs some tests.
   'polysmooth --f' generates some sample figures.
   Usage:  [ds,xs,ys,zs]=twodsort(x,y,z,xo,yo,cutoff);
           [zhat,weight,beta]=polysmooth(ds,xs,ys,zs,b,p);
   --or--
           [ds,xs,ys,zs]=spheresort(lat,lon,z,w,lato,lono,cutoff);
           [zhat,weight,beta]=polysmooth(ds,xs,ys,zs,b,p,'sphere');
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
hlines HLINES Add horizontal lines to a plot.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
matinv MATINV Fast inversion of arrays of small matrices.
matmult MATMULT Matrix multiplication for arrays of matrices.
nocontours NOCONTOURS Removes contours from a CONTOURF plot.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
radearth RADEARTH The radius of the earth in kilometers.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
twodsort TWODSORT Distances from data points to nearby grid points.
vindex VINDEX Indexes an N-D array along a specified dimension.
vlines VLINES Add vertical lines to a plot.
vrep VREP Replicates an array along a specified dimension.
vsize VSIZE Returns the sizes of multiple arguments.
vsqueeze VSQUEEZE Squeezes multiple input arguments simultaneously.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
xtick XTICK Sets locations of x-axis tick marks.
ytick YTICK Sets locations of y-axis tick marks.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
jmap jMap: Mapping scattered data using local polynomial fitting
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.