Description of radearth
Home > jlab > radearth.m
radearth
RADEARTH  The radius of the earth in kilometers.
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2006 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
ellipseplot ELLIPSEPLOT Plot ellipses.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
latlon2xyz LATLON2XYZ Converts latitude and longitude into 3D Cartesian coordinates.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
sig2latlon SIG2LATLON Converts an oscillatory signal to lat/lon displacements.
spherecurl SPHERECURL Curl of a vector field on the surface of a sphere.
spheredist SPHEREDIST Computes great circle distances on a sphere.
spherediv SPHEREDIV Divergence of a vector field on the surface of a sphere.
spheregrad SPHEREGRAD Gradient of a field on the surface of a sphere.
spherelap SPHERELAP Laplacian of a field on the surface of a sphere.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
trajfill TRAJFILL Fills float or drifter trajectories with linear interpolation.
xy2latlon XY2LATLON Converts local Cartesian coordinates into latitude and longitude.