Description of regionplot
Home > jlab > regionplot.m
regionplot
REGIONPLOT  Plots a simple box indicating a latitude / longitude region.
   REGIONPLOT(REGION) draws a latitude / longitue box indicated by REGION
   on the current axes.
   REGION is an array with the format [WEST EAST SOUTH NORTH]. Longitudes
   may either be specified on the interval [-180, 180] or on [0, 360].
   By default, longitudes will be converted to [-180,180] unless the
   region overlaps the dateline, in which case [0,360] will be used.
   The current axes will be held as the box is plotted, then returned to
   its previous HOLD state.
   REGION can also be a cell array of N arrays, each with the format
   REGION{N}=[WEST EAST SOUTH NORTH].  All N regions will then be plotted.
   REGIONPLOT is compatible with the M_MAP toolbox, as described below.
   H=REGIONPLOT outputs the line handle H to the plotted box.
   __________________________________________________________________
   Additional options
   H=REGIONPLOT returns the graphics handle to the plotted box.
   REGIONPLOT(REGION,STY) uses style string STY, in the LINESTYLE format,
   with a default value of STY='k'.
   REGIONPLOT(REGION,'M_MAP') will work with Rich Pawlowicz's M_MAP
   package by calling M_PLOT.
   The additional input parameters can be input together in either order,
   i.e. REGIONPLOT(REGION,STY,'M_MAP') or REGIONPLOT(REGION,'M_MAP',STY).
   __________________________________________________________________
   See also INREGION, FLOATREGION, TOPOPLOT.
   'regionplot --f' generates some sample figures.
   Usage: regionplot(region);
          h=regionplot(region,'m_map');
          h=regionplot(region,'m_map','2k');
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2013--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
boxon BOXON Sets 'box' property to 'on'.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
deg180 DEG180 Converts degrees to the range [-180,180].
deg360 DEG360 Converts degrees to the range [0, 360].
fontsize FONTSIZE Rapidly set title, axes, label, and text fontsizes.
latratio LATRATIO Set plot aspect ratio for latitude / longitude plot.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
regionplot REGIONPLOT Plots a simple box indicating a latitude / longitude region.
use USE Copies structure fields into named variables in workspace.
This function is called by:
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
regionplot REGIONPLOT Plots a simple box indicating a latitude / longitude region.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.