Description of reporttest
Home > jlab > reporttest.m
reporttest
REPORTTEST  Reports the result of an m-file function auto-test.
   Called by JLAB_RUNTESTS.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2003--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
ab2kl AB2KL Converts A and B to ellipse parameters Kappa and Lambda.
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
anatrans ANATRANS Analytic part of signal.
aresame ARESAME Test whether two N-D arrays are the same.
arrayify ARRAYIFY Converts a set of scalars or arrays into column arrays.
bellpoly BELLPOLY Complete Bell polynomials.
bindata BINDATA Rapidly sort data into adjacent bins.
blocklen BLOCKLEN Counts the lengths of 'blocks' in an array.
blocknum BLOCKNUM Numbers the contiguous blocks of an array.
blurspec BLURSPEC Returns the blurred and aliased spectrum given the autocovariance.
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
cellchunk CELLCHUNK Converts cell array data into uniform length 'chunks'.
cellength CELLENGTH Length of each element in a cell array.
cellsize CELLSIZE Size of each element in a cell array along specified dimension.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
col2cell COL2CELL Converts 'column-appended' data into cell arrays of column vectors.
corfreq CORFREQ Coriolis frequency in radians per hour.
curveinterp CURVEINTERP Interpolate a field or its gradient onto a set of curves.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
dawson DAWSON The Dawson function. [By P.J. Acklam]
dawsonderiv DAWSONDERIV Derivatives of the Dawson function.
deg180 DEG180 Converts degrees to the range [-180,180].
deg360 DEG360 Converts degrees to the range [0, 360].
divgeom DIVGEOM Geometric decomposition of eddy vorticity flux divergence.
doublen DOUBLEN Interpolates a time series to double its length.
ecconv ECCONV Converts between eccentricity measures.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
elldiff ELLDIFF Differentiation of modulated elliptical signals.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
fillbad FILLBAD Linearly interpolate over bad data points.
findfiles FINDFILES Returns all files in a directory with a specified extension.
fourier FOURIER The one-sided Fourier frequencies for a given length time series.
hermpoly HERMPOLY Hermite polynomials. [with F. Rekibi]
inregion INREGION Tests whether lat/lon points lie within a specified box.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jdeg2rad JDEG2RAD Converts degrees to radians.
jrad2deg JRAD2DEG Converts radians to degrees.
kl2ab KL2AB Converts ellipse parameters Kappa and Lambda to A and B.
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
latlon2xyz LATLON2XYZ Converts latitude and longitude into 3D Cartesian coordinates.
lininterp LININTERP Fast linear interpolation for arbitrary-sized arrays.
lnsd LNSD Last non-singleton dimension of an array.
lonshift LONSHIFT Shifts longitude origin for plotting purposes.
maternchol MATERNCHOL Cholesky decomposition of the Matern covariance matrix.
materncov MATERNCOV Autocovariance function of the Matern random process.
maternedge MATERNEDGE Long-time cutoff edge for the Matern impulse response function.
maternfun MATERNFUN Returns the Matern function.
maternimp MATERNIMP Impulse response function for the Matern random process.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
matinv MATINV Fast inversion of arrays of small matrices.
matmult MATMULT Matrix multiplication for arrays of matrices.
mom2cum MOM2CUM Convert moments to cumulants.
morlfreq MORLFREQ Compute Morlet wavelet carrier frequency given peak frequency.
morlwave MORLWAVE Morlet wavelet.
morsea MORSEA Returns the generalized Morse wavelet amplitude "a".
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsederiv MORSEDERIV Frequency-domain derivatives of generalized Morse wavelets.
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
morseproj MORSEPROJ Projection coefficient for two generalized Morse wavelets.
morseprops MORSEPROPS Properties of the demodulated generalized Morse wavelets.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
morsexpand MORSEXPAND Generalized Morse wavelets via time-domain Taylor series.
mspec MSPEC Multitaper power and cross spectra.
msvd MSVD Singular value decomposition for polarization analysis.
orbitbreaks ORBITBREAKS Separate orbit into passes based on turning points.
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
periodize PERIODIZE Returns a doubly periodic version of an input array.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
quadinterp QUADINTERP Fast quadratic interpolation for arbitrary-sized arrays.
readtopo READTOPO Read one-minute topography data from Smith and Sandwell.
ridgelen RIDGELEN Wavelet ridge length expressed as number of full cycles.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
sleptap SLEPTAP Calculate Slepian tapers.
slidetrans SLIDETRANS Sliding-window ('moving-window') Fourier transform.
specdiag SPECDIAG Diagonalize a 2 x 2 spectral matrix.
sphere2uvw SPHERE2UVW Converts a 3D spherical vector to a 3D Cartesian vector.
spherecurl SPHERECURL Curl of a vector field on the surface of a sphere.
spheredist SPHEREDIST Computes great circle distances on a sphere.
spherediv SPHEREDIV Divergence of a vector field on the surface of a sphere.
spheregrad SPHEREGRAD Gradient of a field on the surface of a sphere.
spherelap SPHERELAP Laplacian of a field on the surface of a sphere.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
timeseries_boundary TIMESERIES_BOUNDARY Apply boundary conditions to data before transform.
trajchunk TRAJCHUNK Converts Lagrangian trajectories into chunks based on the Coriolis period.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.
trajwrap TRAJWRAP Wraps Lagrangian trajectories to fit within a periodic domain.
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
twodsort TWODSORT Distances from data points to nearby grid points.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
use USE Copies structure fields into named variables in workspace.
uv2latlon UV2LATLON Integrates horizontal velocity to give latitude and longitude.
vcolon VCOLON Condenses its arguments, like X(:).
vdiff VDIFF Length-preserving first central difference.
vectmult VECTMULT Matrix multiplication for arrays of vectors.
vempty VEMPTY Initializes multiple variables to empty sets or empty cell arrays.
vfilt VFILT Filtering along rows without change in length.
vindex VINDEX Indexes an N-D array along a specified dimension.
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
vmean VMEAN Mean over finite elements along a specified dimension.
vmedian VMEDIAN Median over finite elements along a specified dimension.
vmoment VMOMENT Central moment over finite elements along a specfied dimension.
vrep VREP Replicates an array along a specified dimension.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
vsize VSIZE Returns the sizes of multiple arguments.
vsqueeze VSQUEEZE Squeezes multiple input arguments simultaneously.
vstd VSTD Standard deviation over finite elements along a specfied dimension.
vsum VSUM Sum over finite elements along a specified dimension.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
wavetrans WAVETRANS Continuous wavelet transform.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).
xyz2latlon XYZ2LATLON Converts 3D Cartesian coordinates into latitude and longitude.