Description of res
Home > jlab > res.m
res
RES    Residual after flooring:  RES(X)=X-FLOOR(X)
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 1999--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
anatrans ANATRANS Analytic part of signal.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
trajchunk TRAJCHUNK Converts Lagrangian trajectories into chunks based on the Coriolis period.