Description of ridgemap
Home > jlab > ridgemap.m
ridgemap
RIDGEMAP  Maps ridge quantities back onto the time series.
   X=RIDGEMAP(N,XR,IR) where IR is a ridge index and XR is a quantity
   along the ridge, maps the values of XR to their correct row locations
   in a time series of length N, and returns the result in the array X.
   If IR and XR contain L ridges in L separate cells, as output by
   RIDGEWALK, then X is N x L with the values of XR from each ridge in a
   separate column. Values not specified by the IR are left as INFs.
   [X1,X2,...,XM]=RIDGEMAP(N,X1R,X2R,...,XPR,IR) also works for any P
   different ridge quantities X1R--XPR.
   The XR and IR quantities are assumed to have been created by RIDGEWALK.
   __________________________________________________________________
   Collapsing
   X=RIDGEMAP(...'collapse') combines values from all the ridges using
   a power-weighted mean.  Then X is a column vector of size N x 1.
   __________________________________________________________________
   Ridge multiplicity
   [...,MULT]=RIDGEMAP returns the ridge multiplicity MULT after all the
   expected output quantities.  MULT is a column vector with size N x 1.
   The ridge multiplicity is the number of ridges present at each time.
   __________________________________________________________________
   See also RIDGEWALK.
   Usage:   x=ridgemap(N,xr,ir);
            [x,f]=ridgemap(N,xr,fr,ir);
            [x,f]=ridgemap(N,xr,fr,ir,'collapse');
            [x,mult]=ridgemap(N,xr,ir);
            [x,f,mult]=ridgemap(N,xr,fr,ir);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2009--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
col2mat COL2MAT Expands 'column-appended' data into a matrix.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
tmat TMAT 2x2 complex grouping matrix. TMAT = [1 i; 1 -i] / SQRT(2)
use USE Copies structure fields into named variables in workspace.
vectmult VECTMULT Matrix multiplication for arrays of vectors.
vmean VMEAN Mean over finite elements along a specified dimension.
vsum VSUM Sum over finite elements along a specified dimension.
wavetrans WAVETRANS Continuous wavelet transform.
This function is called by:
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jridges jRidges: Wavelet ridge analysis of modulated oscillatory signals
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.