Description of ridgeinterp
Home > jlab > ridgeinterp.m
ridgeinterp
 RIDGEINTERP  Interpolate quantity values onto ridge locations.
   RIDGEINTERP is a low-level function called by RIDGEWALK.
   XI=RIDGEINTERP(FS,RQ,IR,JR,X) where RQ is a "ridge quantity" at
   *radian* frequencies FS, and IR and JR are time and scale indices of
   ridges, interpolates quantity X along the ridge locations to give XI.
   IR and JR give indices into the first two dimensions of X.  The output
   XI has the the same number of rows and columns as IR and JR, that is,
   SIZE(XI,1)=SIZE(IR,1) and SIZE(XI,2)=SIZE(IR,2).  The locations of
   NANs in IR and JR are duplicated in XI.
   NOTE:  IR and JR are now 1-D so the commenting here is not all correct.
   X may have more than one 'page' along its third dimension, in which
   case each page is interpolated separately, and SIZE(XI,3)=SIZE(X,3).
   RQ is output by RIDGEQUANTITY based on a wavelet transform output by
   WAVETRANS, and IR and JR are output by RIDGEWALK.
   RIDGEINTERP interpolates transform values between discrete frequency
   levels to find a more precise value of the transform along the ridges
   than simply looking up the values of X at rows IR and columns JR.
   XI=RIDGEINTERP(FS,RQ,IR,JR,MU,X) interprets the ridges as belonging
   to the MU-th derivative of the signal to which the quantity X belongs
   and applies an appropriate correction factor.
   [XI1,XI2,...,XIN]=RIDGEINTERP(FS,RQ,IR,JR,X1,X2,...,XN) also
   interpolates the quantities X1,X2,...,XN, all the same size.
   RIDGEINTERP uses fast quadratic interpolation via QUADINTERP.  In rare
   cases, quadratic interpolation fails for an individual point and
   therefore linear interpolation is used instead.
   __________________________________________________________________
   RIDGEINTERP is a low-level function called by RIDGEWALK.
   See also RIDGEWALK, RIDGEQUANTITY, QUADINTERP.
   Usage:  xi=ridgeinterp(fs,rq,ir,jr,x);
           [xi1,xi2,xi3]=ridgeinterp(fs,rq,ir,jr,x1,x2,x3);
           [xi1,xi2,xi3]=ridgeinterp(dt,fs,rq,ir,jr,x1,x2,x3);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2005--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
frac FRAC Fraction: FRAC(A,B)=A./B
lininterp LININTERP Fast linear interpolation for arbitrary-sized arrays.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
nonnan NONNAN Return all non-NAN elements of an array.
quadinterp QUADINTERP Fast quadratic interpolation for arbitrary-sized arrays.
vcolon VCOLON Condenses its arguments, like X(:).
vindex VINDEX Indexes an N-D array along a specified dimension.
This function is called by:
jridges jRidges: Wavelet ridge analysis of modulated oscillatory signals
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.