Description of ridgelen
Home > jlab > ridgelen.m
ridgelen
RIDGELEN  Wavelet ridge length expressed as number of full cycles.
   LEN=RIDGELEN(IR,FR) determines the length of the ridges given by the
   ridge parameters IR and FR, with LEN expressed as number of cycles
   completed along the ridge.  FR has units of radians per sample.
   IR is an array of the ridge time indices, while FR is the frequency of
   the wavelet transform value along the ridge, as output by RIDGEWALK.
   LEN is a column vector of the same size as IR and FR.  Each element of
   LEN gives the number of cycles contained in the current ridge.
   IR and FR can also be cell arrays of ridges, in which case the output
   LEN is also a cell array of the same size as the input variables.
   _____________________________________________________________________
   Sample interval
   LEN=RIDGELEN(DT,IR,FR) uses the sample interval DT in calculating the
   ridge length.  DT has the default value DT=1.
   In this case, FR is expected to have units of radians per DT.
   If IR and FR are cell arrays, DT may either be a scalar or an array of
   length LENGTH(IR).
   _______________________________________________________________________
   RIDGELEN internally computes an ID that takes on a single value for all
   points in the same ridge.  If such an ID is already available, calling
   LEN=RIDGELEN(DT,ID,IR,FR) also works.  This form is used by RIDGEWALK.
   _______________________________________________________________________
   'ridgelen --t' runs some tests.
   Usage: lr=ridgelen(ir,fr);
          lr=ridgelen(dt,ir,fr);
          lr=ridgelen(dt,id,ir,fr);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2009--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
blocknum BLOCKNUM Numbers the contiguous blocks of an array.
frac FRAC Fraction: FRAC(A,B)=A./B
reporttest REPORTTEST Reports the result of an m-file function auto-test.
ridgelen RIDGELEN Wavelet ridge length expressed as number of full cycles.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
This function is called by:
jridges jRidges: Wavelet ridge analysis of modulated oscillatory signals
ridgechains RIDGECHAINS Forms ridge curves by connecting transform ridge points.
ridgelen RIDGELEN Wavelet ridge length expressed as number of full cycles.