Description of ridgechains
Home > jlab > ridgechains.m
ridgechains
RIDGECHAINS  Forms ridge curves by connecting transform ridge points.
   RIDGECHAINS is a low-level function called by RIDGEWALK.
   [ID,IR,JR,WR]=RIDGECHAINS(N,BOOL,W) forms chains of ridge points of
   wavelet transform W.
   Ridge points are all points of W for which BOOL, a matrix of the same
   size as W, is true.  Only ridges with at least N periods are returned.
   ID is a unique ID number assigned to each ridge.  IR and JR are the
   time- and scale-indices along the ridges.  WR is the wavelet transform
   along the ridge.
   All output variables are the same size.
   See also RIDGEWALK.
   Usage:  [id,ii,jj,xr]=ridgechains(N,bool,x);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2006--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
blocklen BLOCKLEN Counts the lengths of 'blocks' in an array.
frac FRAC Fraction: FRAC(A,B)=A./B
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
nonnan NONNAN Return all non-NAN elements of an array.
ridgelen RIDGELEN Wavelet ridge length expressed as number of full cycles.
vdiff VDIFF Length-preserving first central difference.
vempty VEMPTY Initializes multiple variables to empty sets or empty cell arrays.
vindex VINDEX Indexes an N-D array along a specified dimension.
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
vrep VREP Replicates an array along a specified dimension.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
This function is called by:
jridges jRidges: Wavelet ridge analysis of modulated oscillatory signals
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.