Description of ridgewalk
Home > jlab > ridgewalk.m
ridgewalk
 RIDGEWALK  Extract wavelet transform ridges, including bias estimates.
   [IR,JR,WR,FR]=RIDGEWALK(W,FS) where W is a wavelet transform matrix
   at frequecies FS, such as that returned by MORSEWAVE, returns the
   wavelet ridges of transform W.
   The columns of W correspond to different frequencies, specified by the
   frequency array FS, at which the wavelet transform was performed.  Note
   that FS assumes a unit sample rate.
   The frequencies FS are expected to be ordered from highest to lowest.
   RIDGEWALK returns the following quantities along ridges
       IR     Ridge indices into rows of W (time)
       JR     Ridge indices into columns of W (scale)
       WR     Wavelet transfrom value along the ridge
       FR     Transform frequency values in radian frequency
   All output variables are cell arrays with one ridge per cell.  To plot
   the ridges, use CELLPLOT(IR,JR).  CELL2COL(IR,JR,WR,FR) turns these
   cell arrays into concatenated column vectors.
   RIDGEWALK(DT,W,FS,...) uses a sample rate DT to compute the ridge
   frequency FR.  The default value of DT is unity.  This does not affect
   the specification of FS, which is given in terms of a unit sample rate.
   _______________________________________________________________________
   Masked-out regions
   RIDGEWALK permits the use to explicitly specify time-frequency regions
   which should be excluded from the ridge analyis.
   RIDGEWALK(...,W,FS,BOOL), where BOOL is a boolean array of the same
   size as W, then those points for which BOOL is false will be excluded
   from the ridge analysis. In addition, ridges are not permitted to cross
   such regions, to prevent spurious chaining between distant frequencies.
   This functionality is useful if we have ancillary information, such as
   a local signal-to-noise estimate, that can help determine a priori
   which time-frequency points appear to be statistically significant.
   _______________________________________________________________________
   Additional options
   RIDGEWALK has other contingencies for rejecting spurious ridge points.
   These tend to occur on the flanks of interesting signals, and
   reflect the wavelet structure rather than the signal structure.
   RIDGEWALK(...,{L,CHI}) specifies options for the ridge computation.
        L  -- Removes all ridges of less than L periods in length
      CHI  -- Removes all small amplitude ridge points having |W|<CHI
   In general, L should be set in proportion to the number of oscillations
   contained in the wavelet.  A recommended setting is L > 2*P/pi, with P
   described shortly. This criterion means that the ridge must be longer
   than the number of oscillations in the central envelope of the wavelet.
   Here P is a quantity that characterizes the number of oscillations in a
   wavelet.  For the generalized Morse wavelets calculated by MORSEWAVE,
   P is given by P=SQRT(BETA*GAMMA), see Lilly and Olhede (2009).
   The options cell may also include some additional parameters for hidden
   options that are used during testing. These should not be required by
   most users, but are documented in the function body for completeness.
   _______________________________________________________________________
   Time-dependent frequency range
   The ridge curves may be limited to a time-varying frequency range.
   RIDGEWALK(DT,...,{FMAX,FMIN,L,CHI}) additionally specifies a maximum
   frequency FMAX and minumum frequency FMIN for the ridges.  Only ridge
   points between these two frequencies are returned.
   FMAX and FMIN are both *radian* frequencies per unit time as specified
   by DT. DT is optional and its default value is unity.  Thus FMAX and
   FMIN are directly comparable to the ridge frequency FR.
   Both FMAX and FMIN are either scalars, or arrays the same length as W.
   _______________________________________________________________________
   Output of bias parameters
   [IR,JR,WR,FR,BR,CR]=RIDGEWALK(...) optionally outputs two additional
   quantities along the ridges.
       BR     Instantaneous bandwidth
       CR     Instantaneous curvature
   When these 'bias parameters' BR and CR are small compared with the
   frequency, i.e. BR/FR << 1 and CR/(FR^2) << 1, then the signal is
   accurately estimated, as discussed in
      Lilly and Olhede (2010), On the analytic wavelet transform.
           IEEE Trans. Info. Theory, 56 (8), 4135--4156.
   For more details, see INSTMOM.
   _______________________________________________________________________
   Joint ridges
   [IR,JR,W1R,W2R,...,WNR,F1R,F2R,...FNR]=RIDGEWALK(W1,W2,...,WN,FS)
   finds the joint ridges of N transforms that all have the same size.
   In this case, there is only one set of ridges but N different values.
   All of the output fields are again cell arrays of the same size.
   [IR,JR,WR,FR]=RIDGEWALK(W1,W2,...,WN,FS,'mat') specifies an alternate,
   'matrix' format for joint ridges.  Now WR and FR are cell arrays, each
   element of which is a matrix with N columns.  The default 'column'
   format splits these N columns into N different output arguments.
   For details on joint ridges, see
      Lilly and Olhede (2012), Analysis of Modulated Multivariate
           Oscillations. IEEE Trans. Sig. Proc., 60 (2), 600--612.
   _______________________________________________________________________
   Bias parameters for joint ridges
   [IR,JR,WR,FR,BR,CR]=RIDGEWALK(W1,W2,...,WN,FS,'mat') for the case of
   joint ridges similarly outputs the two bias parameters along the
   ridges, here organized in matrix format.
   BR and CR are normalized versions of (17) and (18) of Lilly and Olhede
   (2012). Both BR and CR have been normalized by dividing them by the
   modulus of the estimated analytic signal, SQRT(SUM(ABS(WR).^2,2)).
   [...,B1R,B2R,...,BRN,C1R,C2N,...,CNR]=RIDGEWALK(W1,W2,...,WN,FS), the
   default, uses column format instead.  In this case there will be 2+4*N
   total output arguments: IR, JR, and N columns of WR, FR, BR, and CR.
   The bias associated with the estimated signal is small compared to the
   magnitude of the signal when the modulus of XCR is small.
   For more details on the bias parameters for multivariate signals see
   Lilly and Olhede (2012).
   _______________________________________________________________________
   Interscale interpolation
   RIDGEWALK interpolates among discrete scale levels to yield more
   accurate values for the ridge quantities WR and FR using a fast
   quadratic interpolation.
   See the low-level functions RIDGEINTERP and QUADINTERP for details.
   _______________________________________________________________________
   See also WAVETRANS, RIDGEMAP.
   'ridgewalk --t' runs a test.
   'ridgewalk --f' generates a sample figure.
   Usage: [ir,jr,wr,fr]=ridgewalk(w,fs);
          [ir,jr,wr,fr]=ridgewalk(w,fs,{L,CHI});
          [ir,jr,wr,fr]=ridgewalk(dt,w,fs,{L,CHI});
          [ir,jr,wxr,wyr,fxr,fyr]=ridgewalk(dt,wx,wy,fs,{L,CHI});
          [ir,jr,wr,fr,br,cr]=ridgewalk(dt,wx,wy,fs,{L,CHI},'mat');
          [ir,jr,wr,fr]=ridgewalk(dt,w,fs,bool,{L,CHI});
   _______________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
cellength CELLENGTH Length of each element in a cell array.
col2cell COL2CELL Converts 'column-appended' data into cell arrays of column vectors.
colbreaks COLBREAKS Insert NANs into discontinuties in a vector.
fillbad FILLBAD Linearly interpolate over bad data points.
flipmap FLIPMAP Flips the current colormap upside-down.
fontsize FONTSIZE Rapidly set title, axes, label, and text fontsizes.
instmom INSTMOM Univariate and multivariate instantaneous moments.
inticks INTICKS Sets the 'tickdir' property of the current axis to 'in'.
isridgepoint ISRIDGEPOINT Finds wavelet ridge points using one of several criterion.
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
morseprops MORSEPROPS Properties of the demodulated generalized Morse wavelets.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
ridgechains RIDGECHAINS Forms ridge curves by connecting transform ridge points.
ridgeinterp RIDGEINTERP Interpolate quantity values onto ridge locations.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
tmat TMAT 2x2 complex grouping matrix. TMAT = [1 i; 1 -i] / SQRT(2)
use USE Copies structure fields into named variables in workspace.
vdiff VDIFF Length-preserving first central difference.
vectmult VECTMULT Matrix multiplication for arrays of vectors.
vmean VMEAN Mean over finite elements along a specified dimension.
vrep VREP Replicates an array along a specified dimension.
vsum VSUM Sum over finite elements along a specified dimension.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.
wavetrans WAVETRANS Continuous wavelet transform.
This function is called by:
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jridges jRidges: Wavelet ridge analysis of modulated oscillatory signals
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.