Description of rot
Home > jlab > rot.m
rot
 ROT Complex-valued rotation:  ROT(X)=EXP(SQRT(-1)*X)
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2002--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
This function is called by:
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
ecconv ECCONV Converts between eccentricity measures.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
ellvel ELLVEL Average and instantaneous ellipse velocities.
instmom INSTMOM Univariate and multivariate instantaneous moments.
isridgepoint ISRIDGEPOINT Finds wavelet ridge points using one of several criterion.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
morlwave MORLWAVE Morlet wavelet.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morseprops MORSEPROPS Properties of the demodulated generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
msvd MSVD Singular value decomposition for polarization analysis.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
sig2latlon SIG2LATLON Converts an oscillatory signal to lat/lon displacements.
slidetrans SLIDETRANS Sliding-window ('moving-window') Fourier transform.
specdiag SPECDIAG Diagonalize a 2 x 2 spectral matrix.
trajwrap TRAJWRAP Wraps Lagrangian trajectories to fit within a periodic domain.
wavetrans WAVETRANS Continuous wavelet transform.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).
xy2latlon XY2LATLON Converts local Cartesian coordinates into latitude and longitude.