Description of sampletimes
Home > jlab > sampletimes.m
sampletimes
SAMPLETIMES  Computes mean sampling intervals and their statistics.
   DT=SAMPLETIMES(NUM) where NUM is a column vector of times, returns the
   mean interval between sample times DT.
   [DT,SIG,MED,MAX]=SAMPLETIMES(NUM) also returns the standard deviation
   of sample intervals SIG, the median sample interval MED, and the
   maximum sample interval MAX.
   IF NUM is a cell array of numerical arrays, the output of SAMPLETIMES
   will be arrays of size LENGTH(NUM) x 1.
   Usage: dt=sampletimes(num);
          [dt,sig,med,max]=sampletimes(num);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
vmean VMEAN Mean over finite elements along a specified dimension.
vmedian VMEDIAN Median over finite elements along a specified dimension.
vstd VSTD Standard deviation over finite elements along a specfied dimension.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
This function is called by:
jspectral jSpectral: Multitaper spectral analysis, and other time series tools