Description of sig2latlon
Home > jlab > sig2latlon.m
sig2latlon
SIG2LATLON  Converts an oscillatory signal to lat/lon displacements.
   [LATRES,LONRES]=SIG2LATLON(X,Y,LAT,LON) where X and Y are zonal and
   meridional displacements, in kilometers, about some time-varying
   position wiht latitude LAT and longitude LON, returns the residuals
   between the signal and the position curve.
   [LATRES,LONRES,DLAT,DLON]=SIG2LATLON(X,Y,LAT,LON) also returns the
   latitude and longitude displacements associated with X and Y.
   The residuals are output first because this is usually what is desired.
   These are essentially LAT-DLAT and LON-DLON, apart from an unwrapping
   correction for longitude.
   All input arguments are arrays of the same size.
   ____________________________________________________________________
   Cell array input/output
   If SIG2LATLON is given cell array input, it returns cell array output.
   Thus X, Y, LAT, and LON may each be cell arrays of the same size,
   where each element in the cell array is a numerical array. The output
   arguments will then also be cell arrays of this size.
   ____________________________________________________________________
   'sig2latlon --t' runs a test.
   Usage: [latres,lonres]=sig2latlon(x,y,lat,lon);
          [latres,lonres,dlat,dlon]=sig2latlon(x,y,lat,lon);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2014--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
frac FRAC Fraction: FRAC(A,B)=A./B
radearth RADEARTH The radius of the earth in kilometers.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
This function is called by:
jellipse jEllipse: Analysis of modulated elliptical, or bivariate, signals