Description of simplepdf
Home > jlab > simplepdf.m
simplepdf
SIMPLEPDF  Gaussian, uniform, Cauchy, and exponential pdfs.
   F=SIMPLEPDF(X,MU,SIG,'gaussian') computes a Gaussian pdf with mean
   MU and standard deviation SIG.
   F=SIMPLEPDF(X,MU,SIG,'boxcar') computes a uniform pdf with mean MU
   and standard deviation SIG.
   F=SIMPLEPDF(X,XO,ALPHA,'cauchy') computes a Cauchy pdf with location
   parameter XO and scale parameter ALPHA.
   F=SIMPLEPDF(X,BETA,'exponential') computes an exponential pdf with
   scale parameter, hence mean and standard deviation, equal to BETA.
   'simplepdf --f' generates a sample figure
   Usage: f=simplepdf(x,mu,sig,'gaussian');
          f=simplepdf(x,mu,sig,'boxcar');
          f=simplepdf(x,xo,alpha,'cauchy');
          f=simplepdf(x,beta,'exponential');
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2001--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
frac FRAC Fraction: FRAC(A,B)=A./B
simplepdf SIMPLEPDF Gaussian, uniform, Cauchy, and exponential pdfs.
vlines VLINES Add vertical lines to a plot.
vsum VSUM Sum over finite elements along a specified dimension.
This function is called by:
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
simplepdf SIMPLEPDF Gaussian, uniform, Cauchy, and exponential pdfs.