Description of sleptap
Home > jlab > sleptap.m
sleptap
SLEPTAP  Calculate Slepian tapers.
   [PSI,LAMBDA]=SLEPTAP(N,P,K) calculates the K lowest-order Slepian
   tapers PSI of length N and time-bandwidth product P, together with
   their eigenvalues LAMBDA. PSI is N x K and LAMBDA is K x 1.
   K is optional and defaults to 2P-1.
   P is optional and defaults to 4.
   For N<=512, SLEPTAP uses the tridiagonal method described in Percival
   and Walden (1993).  For N>512, it first computes tapers for N=512 and
   then spline-interpolates.
   N may also be an array of lengths.  In this case PSI is a cell array of
   matrices, with PSI{1} being N(1) x K, PSI{2} being N(2) x K, etc.,
   while LAMBDA is K x LENGTH(N).  See 'Cell array input' under MSPEC.
   _____________________________________________________________________
   Normalization
   By default, the tapers are set to have unit energy. Alternatively
   SLEPTAP(...,'bandpass') uses the "bandpass" normalization in which the
   tapers are rescaled so that the maximum value of the Fourier transform
   of the first taper is set to two.
   See WAVETRANS for details on bandpass normalization.
   _____________________________________________________________________
   See also MSPEC, MSVD, TWOSPECPLOT.
   'sleptap --t' runs some tests.
   Usage:  [psi,lambda]=sleptap(n);
           [psi,lambda]=sleptap(n,p,k);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
anyany ANYANY(X)=ANY(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
reporttest REPORTTEST Reports the result of an m-file function auto-test.
sleptap SLEPTAP Calculate Slepian tapers.
vsum VSUM Sum over finite elements along a specified dimension.
This function is called by:
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jspectral jSpectral: Multitaper spectral analysis, and other time series tools
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
mspec MSPEC Multitaper power and cross spectra.
sleptap SLEPTAP Calculate Slepian tapers.