Description of slidetrans
Home > jlab > slidetrans.m
slidetrans
SLIDETRANS  Sliding-window ('moving-window') Fourier transform.
   Y=SLIDETRANS(X,PSI,F) computes the sliding-window Fourier transform of
   the signal X using window PSI at frequencies F. X and W are column
   vectors.  Y is a matrix of size LENGTH(X) by LENGTH(FS).
   The frequencies F are radian frequencies as in COS(F T).
   PSI may also be a matrix, in which case Y is a 3-D array of size
   LENGTH(X) by LENGTH(FS) by SIZE(W,2).
   SLIDETRANS(...,STR) sets the endpoint boundary conditions, with STR
   equal to 'mirror', 'periodic', or 'zeros'.  The default is 'periodic'.
   For more details, see the boundary condition discussion in WAVETRANS.
   A good choice for window is the first "Slepian" taper; see SLEPTAP.
   Hermite functions are also used; see HERMFUN.
   SLIDETRANS follows the same normalization as WAVETRANS when the input
   signal X is complex-valued, so see that function for details.
   _________________________________________________________________
   Definition
   The sliding window transform is defined as
      y(t,f) = int psi^*(u-t) exp[-2 pi i f (u-t)] x(t) du.
   When a sinusoid is transformed at its own frequency, the rate of change
   of the phase of the sliding window transform recovers the frequency of
   the sinusoid.  This is the same as with the wavelet transform.
   This differs from the definition of Mallat (1999), p. 69, by a unit
   amplitude factor of exp[2 pi i f t].  In Mallat's defintion, the
   transform of a sinusoid at the sinusoid's frequency has constant phase.
   Both definitions have the same modulus.
   _________________________________________________________________
   'slidetrans --t' runs a test.
   'slidetrans --f' generates a sample figure.
   Usage: y=slidetrans(x,psi,f);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
hermfun HERMFUN Orthonormal Hermite functions. [with F. Rekibi]
hlines HLINES Add horizontal lines to a plot.
oprod OPROD Outer product: OPROD(X,Y)=X*CONJ(Y')
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
slidetrans SLIDETRANS Sliding-window ('moving-window') Fourier transform.
vdiff VDIFF Length-preserving first central difference.
vrep VREP Replicates an array along a specified dimension.
vsum VSUM Sum over finite elements along a specified dimension.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.
wavetrans WAVETRANS Continuous wavelet transform.
This function is called by:
jspectral jSpectral: Multitaper spectral analysis, and other time series tools
slidetrans SLIDETRANS Sliding-window ('moving-window') Fourier transform.