Description of specdiag
Home > jlab > specdiag.m
specdiag
 SPECDIAG  Diagonalize a 2 x 2 spectral matrix.
   [D1,D2,TH,NU,Z]=SPECDIAG(S) for a 2 x 2 spectral matrix S returns the
   eigenvalues D1 and D2 and the angles TH and NU and eigenvector matrix Z
   which diagonalize S according to the decomposition
          Z = JMAT(TH) *  KMAT(PI/4) * JMAT(NU)
          S = Z [D1 0; 0 D2] Z'
   where JMAT is the two by two rotation matrix and KMAT(PI/4) is a
   diagonal matrix with main diagonal [(1+i) (1-i)]/SQRT(2).
   If S is a 2 x 2 x M matrix, then D1, D2, NU, and TH are all Mx1 column
   vectors, and Z is 2 x 2 x M. More generally, if S is 2 x 2 x M x ... N,
   then D1, D2, NU, and TH are all M x ... N  and Z is 2 x 2 x M x ... N.
   Note that singleton dimensions will be squeezed out.
   [...]=SPECDIAG(S11,S22,S12) also works. In this case all input and output
   variables are matrices of the same size.  Z is not output.
   'SPECDIAG --t' runs some tests.
   Usage: [d1,d2,th,nu,z]=specdiag(s);
          [d1,d2,th,nu]=specdiag(s11,s22,s12);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
jmat JMAT 2x2 rotation matrix through specified angle.
polparams POLPARAM Spectral matrix polarization parameters.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
specdiag SPECDIAG Diagonalize a 2 x 2 spectral matrix.
This function is called by:
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
jspectral jSpectral: Multitaper spectral analysis, and other time series tools
specdiag SPECDIAG Diagonalize a 2 x 2 spectral matrix.