Description of spherediv
Home > jlab > spherediv.m
spherediv
SPHEREDIV  Divergence of a vector field on the surface of a sphere.
   DIV=SPHEREDIV(LAT,LON,U,V) computes the divergence of the vector field
   (U,V) on the surface of the sphere.
   U and V are zonal and meridional velocities in meters per second, and
   DIV is in inverse seconds.
   LAT and LON are vectors specifing an evenly-spaced grid, and U and V
   are arrays of size LENGTH(LON) x LENGTH(LAT) x M, where M is greater
   than or equal to one. LAT and LON are in degrees.
   The radius of the Earth as specified by RADEARTH is used by default.
   SPHEREDIV(...,R) uses a sphere of radius R, in kilometers, instead.
   Derivatives are computed using the first central difference.
   [DIV,UX,VY]=SPHEREDIV(LAT,LON,U,V) optionally returns the zonal and
   meridional contributions UX and VY, such that DIV=UX+VY.
   ___________________________________________________________________
   First and last points
   SPHEREDIV can use different boundary conditions in the numerical
   computation of derivatives for the first and last points.
   SPHEREDIV(...,'periodic') uses a periodic derivative with respect
   to longitude.  This is the default behavior.
   SPHEREDIV(...,'endpoint') uses the forwards / first backwards
   difference at the first and last longitude, respectively.
   For both of these options, the endpoint condition is used for
   differentiation with respect to latitude.
   SPHEREDIV(...,'nans')  fills in the first and last values on all four
   sides of the region with NANs.
   See VDIFF for more information.
   ___________________________________________________________________
   See also SPHEREGRAD, SPHERELAP, SPHERECURL, JSPHERE.
   'spherediv --t' runs a test.
   Usage: div=spherediv(lat,lon,u,v);
          [div,ux,vy]=spherediv(lat,lon,u,v);
          div=spherediv(lat,lon,u,v,R);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2009 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
jdeg2rad JDEG2RAD Converts degrees to radians.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
radearth RADEARTH The radius of the earth in kilometers.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
spherediv SPHEREDIV Divergence of a vector field on the surface of a sphere.
vdiff VDIFF Length-preserving first central difference.
vrep VREP Replicates an array along a specified dimension.
This function is called by:
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
spherediv SPHEREDIV Divergence of a vector field on the surface of a sphere.
spheregrad SPHEREGRAD Gradient of a field on the surface of a sphere.
spherelap SPHERELAP Laplacian of a field on the surface of a sphere.