Description of spheresort
Home > jlab > spheresort.m
spheresort
SPHERESORT  Sorted great circle distances to nearby points on the earth.
   Computing great circle distances on the earth between two sets of
   points --- data points and a fixed grid, say --- is computationally
   expensize.  SPHERESORT speeds this up substantially.
   [DS,XS,YS]=SPHERESORT(LAT,LON,LATO,LONO,CUTOFF) returns the great
   circle distances DS between data points at locations LAT, LON and
   nearby grid points located at LATO, LONO, sorting in order of distance.
   XS and YS are the corresponding positions of the sorted data points
   in a local tangent plane about each grid point.
   SPHERESORT only computes distances for nearby points.  CUTOFF is the
   maximum distance (in kilometers) for which we wish the great circle
   distance to be computed.
   CUTOFF should be less that 1/4 of the circumference of the earth,
   RADEARTH * PI/2, so that (LAT,LON) points lie in the same hemisphere
   as the corresponding grid points.
   LAT and LON are arrays of the same size into data point locations.
   LATO and LONO are arrays of length M and N, say, specifying the
   latitudes and longitudes of an M x N matrix of grid points, i.e.
       LATO =  [LATO_1;    LONO= [LONO_1 LONO_2 ... LONO_N].
                LATO_2;
                  ...
                LATO_M]
   The output arrays are then each M x N x P arrays of column vectors,
   where P is the maximum number of points in the CUTOFF neighborhood at
   any grid point.  Points farther away are filled with NANs.
   DS gives the distances of data points less than CUTOFF kilometers
   from the (m,n)th grid point, sorted in order of increasing distance.
   XS and YS are also M x N x P, and give the coordinates of the
   corresponding data points in a Cartesian expansion about the (m,n)th
   grid point, in kilometers.  See LATLON2XY for details.
   _________________________________________________________________
   Additional input parameters
   Let's say some additional variables Z1, Z2,...,ZK are given at
   the data locations LAT, LON.  Then
   [DS,XS,YS,Z1S,Z2S,...,ZKS]=
                SPHERESORT(LAT,LON,Z1,Z2,...,ZK,LATO,LONO,CUTOFF);
   also returns the sorted values of these variables.
   Z1S, Z2S,...,ZKS are the same size as the other output arguments.
   Z1S then gives the value of Z1 at data points no more than CUTOFF
   kilometers from the (m,n)th grid point, etc.
   To output an index into the data point locations, use
   [DS,XS,YS,INDEX]=SPHERESORT(LAT,LON,1:LENGTH(LAT(:)),LATO,LONO,CUTOFF).
   _________________________________________________________________
   Parellel algorithm
   With Matlab's Parallel Computing Toolbox installed, SPHERESORT can
   take advantage of multiple cores to speed up operations.
   SPHERESORT('parallel',NWORKERS) parallelizes the computation with the
   number of workers set to NWORKERS.  Choose this as the number of
   independent processors on your machine.
   As the additional efficiency is not dramatic, this is typically only an
   advantage for very large datasets.  Due to the nature of the
   calculation we have to use SPMD, which is less efficient than PARFOR.
   As an example, for a dataset with 1 million points, a 12 core Mac Pro
   takes about 44 seconds to complete the sort on a 1x1 degree grid,
   versus 184 seconds for the standard algorithm, a factor of 4 faster.
   _________________________________________________________________
   See also TWODSORT, POLYSMOOTH.
   'spheresort --t' runs a test.
   Usage: ds=spheresort(lat,lon,lato,lono,cutoff);
          ds=spheresort(lat,lon,lato,lono,cutoff,'parallel',Nworkers);
          [ds,xs,ys]=spheresort(lat,lon,lato,lono,cutoff);
          [ds,xs,ys,z1s,z2s]=spheresort(lat,lon,z1,z2,lato,lono,cutoff);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
anyany ANYANY(X)=ANY(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
cellength CELLENGTH Length of each element in a cell array.
frac FRAC Fraction: FRAC(A,B)=A./B
jrad2deg JRAD2DEG Converts radians to degrees.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
latlon2xyz LATLON2XYZ Converts latitude and longitude into 3D Cartesian coordinates.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
radearth RADEARTH The radius of the earth in kilometers.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
spheredist SPHEREDIST Computes great circle distances on a sphere.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
squared SQUARED Squares the modulus of its argument: SQUARED(X)=ABS(X).^2
vcolon VCOLON Condenses its arguments, like X(:).
vindex VINDEX Indexes an N-D array along a specified dimension.
vrep VREP Replicates an array along a specified dimension.
vsum VSUM Sum over finite elements along a specified dimension.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
xyz2latlon XYZ2LATLON Converts 3D Cartesian coordinates into latitude and longitude.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
jmap jMap: Mapping scattered data using local polynomial fitting
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.