Description of spheregrad
Home > jlab > spheregrad.m
spheregrad
SPHEREGRAD  Gradient of a field on the surface of a sphere.
   [FX,FY]=SPHEREGRAD(LAT,LON,F) computes the gradient of the scalar field
   F on the surface of the sphere.
   FX and FY are the components of the gradient of F in the zonal and
   meridional directions, respectively, with units of F per meter.
   LAT and LON are vectors specifing an evenly-spaced grid, and F is an
   array of size LENGTH(LON) x LENGTH(LAT) x M, where M is greater than or
   equal to one.  LAT and LON are in degrees.
   The radius of the Earth as specified by RADEARTH is used by default.
   SPHEREDIV(...,R) uses a sphere of radius R, in kilometers, instead.
   Derivatives are computed using the first central difference.
   FZ=SPHEREGRAD(LAT,LON,F) with one output argument returns the
   complex-valued array FZ=FX+i*FY.
   ___________________________________________________________________
   First and last points
   SPHEREGRAD can use different boundary conditions in the numerical
   computation of derivatives for the first and last points.
   SPHEREGRAD(...,'periodic') uses a periodic derivative with respect to
   longitude.  This is the default behavior.
   SPHEREGRAD(...,'endpoint') uses the forwards / first backwards
   difference at the first and last longitude, respectively.
   For both of these options, the endpoint condition is used for
   differentiation with respect to latitude.
   SPHEREGRAD(...,'nans')  fills in the first and last values on all four
   sides of the region with NANs.
   See VDIFF for more information.
   ___________________________________________________________________
   See also SPHEREDIV, SPHERELAP, SPHERECURL, JSPHERE.
   'spheregrad --t' runs a test.
   Usage: [fx,fy]=spheregrad(lat,lon,f);
          [fx,fy]=spheregrad(lat,lon,f,R);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2009 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
jdeg2rad JDEG2RAD Converts degrees to radians.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
radearth RADEARTH The radius of the earth in kilometers.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
spherediv SPHEREDIV Divergence of a vector field on the surface of a sphere.
spheregrad SPHEREGRAD Gradient of a field on the surface of a sphere.
vdiff VDIFF Length-preserving first central difference.
vrep VREP Replicates an array along a specified dimension.
This function is called by:
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
spherecurl SPHERECURL Curl of a vector field on the surface of a sphere.
spheregrad SPHEREGRAD Gradient of a field on the surface of a sphere.
spherelap SPHERELAP Laplacian of a field on the surface of a sphere.