Description of sphere2uvw
Home > jlab > sphere2uvw.m
sphere2uvw
SPHERE2UVW Converts a 3D spherical vector to a 3D Cartesian vector.
   [U,V,W]=XYZ2SPHERE(LAT,LON,V1,V2,V3) converts a vector in spherical
   coordinates with components V1, V2, and V3 located at point
   (LAT, LON) into a Cartesian 3-vector with components U, V, and W.
   LAT and LON are in degrees.
   The vector in the spherical coordinate system has radial component
   V1, longitudinal component V2, and latitudinal component V3.
   The Cartesian vector [U,V,W] is in a reference frame with the
   X-axis at zero degrees longitude and the Z-axis at the North Pole.
   All input arguments should be arrays of the same size.
   SPHERE2UVW is inverted by UVW2SPHERE.
   See JSPHERE for related functions.
   Usage: [x,y,z]=sphere2uvw(lat,lon,v1,v2,v3);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
jdeg2rad JDEG2RAD Converts degrees to radians.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
sphere2uvw SPHERE2UVW Converts a 3D spherical vector to a 3D Cartesian vector.
This function is called by:
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
sphere2uvw SPHERE2UVW Converts a 3D spherical vector to a 3D Cartesian vector.
uv2latlon UV2LATLON Integrates horizontal velocity to give latitude and longitude.