Description of squared
Home > jlab > squared.m
squared
 SQUARED   Squares the modulus of its argument:  SQUARED(X)=ABS(X).^2
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
ecconv ECCONV Converts between eccentricity measures.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
elldiff ELLDIFF Differentiation of modulated elliptical signals.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
maternchol MATERNCHOL Cholesky decomposition of the Matern covariance matrix.
maternimp MATERNIMP Impulse response function for the Matern random process.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
mspec MSPEC Multitaper power and cross spectra.
msvd MSVD Singular value decomposition for polarization analysis.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
spheredist SPHEREDIST Computes great circle distances on a sphere.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.