Description of timeseries_boundary
Home > jlab > timeseries_boundary.m
timeseries_boundary
TIMESERIES_BOUNDARY  Apply boundary conditions to data before transform.
   TIMESERIES_BOUNDARY is a low-level function called by WAVETRANS and
   ANATRANS.
   TIMESERIES_BOUNDARY applies periodic, zero-padded, or mirror boundary
   conditions to a time series.  See ANATRANS or WAVETRANS.
   This is a low-level function, not meant to be user called by users.
   TIMESERIES_BOUNDARY(X,STR,DETRENDSTR) applies boundary conditions
   specified by STR to time series X.  If DETRENDSTR='detrend', X is first
   detrended.  STR may be 'periodic', 'zeros', 'mirror', or 'reverse':
      'periodic' wraps the beginning around to the end, and vice versa
      'zeros'    extends the time series with zeros at both edges
      'mirror'   reflects the time series about the beginning and the end
      'reverse'  is like mirror, but with a change in sign, and a shift
                   to make the time series be continuous at both edges
   TIMESERIES_BOUNDARY(X,DIM,STR) applies the boundary conditions
   specified by STR along dimension DIM.  By default, DIM=1.  Note that
   no detrending is possible for DIM not equal to one.  Also, 'reverse'
   only works for the default case of DIM=1.
   Usage: y=timeseries_boundary(x,str,detrendstr);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2011--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
timeseries_boundary TIMESERIES_BOUNDARY Apply boundary conditions to data before transform.
use USE Copies structure fields into named variables in workspace.
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
This function is called by:
anatrans ANATRANS Analytic part of signal.
jspectral jSpectral: Multitaper spectral analysis, and other time series tools
timeseries_boundary TIMESERIES_BOUNDARY Apply boundary conditions to data before transform.
wavetrans WAVETRANS Continuous wavelet transform.