Description of tmat
Home > jlab > tmat.m
tmat
TMAT  2x2 complex grouping matrix.  TMAT = [1  i; 1 -i] / SQRT(2)
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
frac FRAC Fraction: FRAC(A,B)=A./B
This function is called by:
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
mspec MSPEC Multitaper power and cross spectra.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.
wavetrans WAVETRANS Continuous wavelet transform.