Description of to_overwrite
Home > jlab > to_overwrite.m
to_overwrite
TO_OVERWRITE Returns a string to overwrite original arguments.
   STR=TO_OVERWRITE(N), when called from within an m-file which has
   VARARGIN for the input variable, returns a string which upon
   EVAL(STR) will cause the first N input variables in the caller
   workspace with the values contained in the first N elements of
   VARARGOUT.
   See also TO_GRAB_FROM_CALLER.
   Usage: eval(to_overwrite(N))
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2001--2006 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
arrayify ARRAYIFY Converts a set of scalars or arrays into column arrays.
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
cellchunk CELLCHUNK Converts cell array data into uniform length 'chunks'.
cellmean CELLMEAN Mean value of each element a cell array or set of cell arrays.
col2cell COL2CELL Converts 'column-appended' data into cell arrays of column vectors.
col2mat COL2MAT Expands 'column-appended' data into a matrix.
colbreaks COLBREAKS Insert NANs into discontinuties in a vector.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
mat2col MAT2COL Compress NAN-padded matrix data into long columns.
orbitbreaks ORBITBREAKS Separate orbit into passes based on turning points.
trajchunk TRAJCHUNK Converts Lagrangian trajectories into chunks based on the Coriolis period.
trajunwrap TRAJUNWRAP Unwraps Lagrangian trajectories from a periodic domain.
trajwrap TRAJWRAP Wraps Lagrangian trajectories to fit within a periodic domain.
vcolon VCOLON Condenses its arguments, like X(:).
vdiff VDIFF Length-preserving first central difference.
vfilt VFILT Filtering along rows without change in length.
vindex VINDEX Indexes an N-D array along a specified dimension.
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
vmean VMEAN Mean over finite elements along a specified dimension.
vmedian VMEDIAN Median over finite elements along a specified dimension.
vmoment VMOMENT Central moment over finite elements along a specfied dimension.
vrep VREP Replicates an array along a specified dimension.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
vsqueeze VSQUEEZE Squeezes multiple input arguments simultaneously.
vstd VSTD Standard deviation over finite elements along a specfied dimension.
vsum VSUM Sum over finite elements along a specified dimension.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
vtranspose VTRANSPOSE Transpose multiple input arguments simultaneously.