Description of trajfill
Home > jlab > trajfill.m
trajfill
TRAJFILL  Fills float or drifter trajectories with linear interpolation.
   [LAT,LON]=TRAJFILL(LAT,LON) fills any gaps in the input vectors LAT
   and LON, as indicated by INF values, using linear interpolation.
   [LAT,LON,FILLED]=TRAJFILL(LAT,LON) also returns a boolean array
   FILLED of the same size as LAT and LON.  FILLED is true if that data
   point has been filled, and false otherwise.
   TRAJFILL also works if the input LAT and LON are cell arrays of
   numeric arrays, as in the dataset FLOATS.MAT.  In this case the
   output fields are all cell arrays of the same size as the input.
   Specifically TRAJFILL works by converting latitude and longitude
   values to 3-vectors representing a position on the surface of the
   earth, interpolating, and then converting back.
   Usage: [lat,lon]=trajfill(lat,lon);
          [lat,lon,filled]=trajfill(lat,lon);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2014--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
fillbad FILLBAD Linearly interpolate over bad data points.
latlon2xyz LATLON2XYZ Converts latitude and longitude into 3D Cartesian coordinates.
radearth RADEARTH The radius of the earth in kilometers.
xyz2latlon XYZ2LATLON Converts 3D Cartesian coordinates into latitude and longitude.
This function is called by:
about_drifters DRIFTERS Global surface drifter dataset from the Global Drifter Program.
joceans jOceans: Oceanography-specific data and model analysis tools