Description of trajextract
Home > jlab > trajextract.m
trajextract
TRAJEXTRACT  Extracts Lagrangian trajectory segments within given region.
   [LAT,LON]=TRAJEXTRACT(REGION,LAT,LON) where the input LAT and LON are
   cell arrays of columns vectors of latitude and longitude, outputs new
   cell arrays with LAT and LON of the segments contained within REGION.
   This format for LAT and LON is used by two Lagrangian datasets
   distributed with JLAB, FLOATS.MAT and DRIFTERS.MAT.  Type 'help floats'
   or 'help drifters' for more details.
   REGION is an array with the format [WEST EAST SOUTH NORTH]. Longitudes
   may either be specified on the interval [-180, 180] or on [0, 360].
   The region may overlap the prime meridian (LON=0) or the dateline
   (LON=180).  Region boundaries are interpreted to exclude the poles.
   REGION is passed directly to the function INREGION.  Thus, REGION can
   also be a cell array built up from serveral region boxes.  See INREGION
   for more details on this option.
   If an input LAT and LON record contains more than one segment passing
   through REGION, these are split into separate entries in the output.
   [LAT,LON,X1,X2,...,XN]=TRAJEXTRACT(REGION,LAT,LON,X1,X2,...,XN) also
   returns the portions of the cell array variables X1,X2,...,XN within
   the region.  The input XN are the same size as the input LAT and LON.
   [LAT,LON,...]=TRAJEXTRACT(LMIN,REGION,LAT,LON,...) only returns those
   segments containing LMIN or more points. The default is LMIN=2.
   See also INREGION, REGIONPLOT.
   'trajextract --t' runs a test.
   'trajextract --f' generates a sample figure.
   Usage: [lat,lon]=trajextract(region,lat,lon);
          [lat,lon,num,id]=trajextract(region,lat,lon,num,id);
          [lat,lon,num,id]=trajextract(200,region,lat,lon,num,id);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2014--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
boxon BOXON Sets 'box' property to 'on'.
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
celladd CELLADD Addition acting on each element in a cell array.
cellength CELLENGTH Length of each element in a cell array.
cellindex CELLINDEX Applies a cell array of indices to a cell array of column vectors.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
col2cell COL2CELL Converts 'column-appended' data into cell arrays of column vectors.
col2mat COL2MAT Expands 'column-appended' data into a matrix.
deg180 DEG180 Converts degrees to the range [-180,180].
fontsize FONTSIZE Rapidly set title, axes, label, and text fontsizes.
inregion INREGION Tests whether lat/lon points lie within a specified box.
latratio LATRATIO Set plot aspect ratio for latitude / longitude plot.
mat2col MAT2COL Compress NAN-padded matrix data into long columns.
regionplot REGIONPLOT Plots a simple box indicating a latitude / longitude region.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.
use USE Copies structure fields into named variables in workspace.
vindex VINDEX Indexes an N-D array along a specified dimension.
This function is called by:
joceans jOceans: Oceanography-specific data and model analysis tools
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.