Description of twodmed
Home > jlab > twodmed.m
twodmed
TWODMED  Median value of a function of two variables.
   __________________________________________________________________
   __________________________________________________________________
   MED=TWODMED(X,Y,Z,XBIN,YBIN) where X, Y and Z are arrays of the same
   length, forms the median of Z over the XY plane.
   If XBIN and YBIN are length N and M, respectively, then MED is of
   size M-1 x N-1.  Bins with no data are assigned a value of NAN.
   XBIN and YBIN must be monotonically increasing.
   MED=TWODMED(X,Y,Z,N) uses N bins in the X and Y directions, linearly
   spaced between the minimum and maximum values.  MED is N-1 x N-1.
   MED=TWODMED(X,Y,Z,[XMIN XMAX],[YMIN YMAX],N) uses N bins, linearly
   spaced between the designated X and Y values.  MED is N-1 x N-1.
   [MED,XMID,YMID]=TWODMED(...) optionally returns the midpoints XMID
   and YMID of the bins.
   X, Y, and Z can also be cell arrays of numerical arrays, in which case
   all data values are concatented prior to finding the histogram.
   TWODMED, TWODSTATS, and TWODHIST are three related functions for
   computing statistics as a function two variables using very fast
   algorithms that avoid any loops through efficient use of indexing.
   __________________________________________________________________
   Algorithms
   TWODMED uses a fast (exact) algorithm which is particularly efficient
   for large arrays.
   The values of Z are sorted into bins according to the associated (X,Y)
   value, with bin edges specified by XBIN and YBIN, and the median of
   finite values of Z in each bin is computed looplessly using indexing.
   TWODMED(...,'slow') uses a slow algorithm which uses less memory.
   By default, TWODMED uses a fast but memory-intensive algorithm.
   Use this flag if you get an out-of-memory error.
   __________________________________________________________________
   See also TWODHIST, TWODSTATS.
   'twodmed --f' generates the sample figure shown above.
   'twodmed --t' runs a test.
   Usage: med=twodmed(x,y,z,N);
          med=twodmed(x,y,z,[xmin xmax],[xmin xmax],N);
          med=twodmed(x,y,z,xbin,ybin);
          [med,xmid,ymid]=twodmed(x,y,z,xbin,ybin);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2007--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
bindata BINDATA Rapidly sort data into adjacent bins.
blocklen BLOCKLEN Counts the lengths of 'blocks' in an array.
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
cellabs CELLABS Absolute value of each element in a cell array.
col2mat COL2MAT Expands 'column-appended' data into a matrix.
colbreaks COLBREAKS Insert NANs into discontinuties in a vector.
crop CROP Gets rid of whitespace around an image. [by A. Bliss]
iseven ISEVEN True for even integer values; false otherwise.
isodd ISODD True for odd integer values; false otherwise.
jpcolor JPCOLOR Modified version of PCOLOR appropriate for cell-centered grids.
latratio LATRATIO Set plot aspect ratio for latitude / longitude plot.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
minmin MINMIN(X)=MIN(X(ISFINITE(X)))
nonnan NONNAN Return all non-NAN elements of an array.
oprod OPROD Outer product: OPROD(X,Y)=X*CONJ(Y')
reporttest REPORTTEST Reports the result of an m-file function auto-test.
topoplot TOPOPLOT Plot regional or global topography at one-sixth degree resolution.
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
use USE Copies structure fields into named variables in workspace.
vcolon VCOLON Condenses its arguments, like X(:).
vindex VINDEX Indexes an N-D array along a specified dimension.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
whichdir WHICHDIR Returns directory name containing file in search path.
This function is called by:
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jstats jStats: Fast statistical analysis of large datasets in two dimensions
twodmed TWODMED Median value of a function of two variables.