Description of twospecplot
Home > jlab > twospecplot.m
twospecplot
TWOSPECPLOT  Plots a pair of rotary or Cartesian spectra.
   TWOSPECPLOT(F,SPP,SNN) plots the rotary spectra SPP and SNN with log-
   log axes.  SNN is on the left, with a reversed x-axis.
   TWOSPECPLOT(F,SXX,SYY,'cartesian') left the same, but now labels the
   and right axes as the zonal and meridional spectra, respectively.
   TWOSPECPLOT(...,'tides') marks the major tidal with dotted lines.  F is
   assumed to be in units of *radians* per hour.
   TWOSPECPLOT(LAT,F,SPP,SNN) also marks the Coriolis frequency at
   latitude LAT, using a red line, on both sides of the spectrum.
   H=TWOSPECPLOT(...) also returns the handle to the subplots.
   The input quantities F, SPP, and SNN or F, SXX, and SYY may be cell
   arrays.  See 'Cell array input / output' under MSPEC for details.
   See also MSPEC, SLEPTAP.
   Usage: twospecplot(f,spp,snn)
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2012--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
boxon BOXON Sets 'box' property to 'on'.
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
cellplot CELLPLOT Rapidly plot all elements of a cell array of numeric arrays.
corfreq CORFREQ Coriolis frequency in radians per hour.
flipx FLIPX Flips the direction of the x-axis
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
minmin MINMIN(X)=MIN(X(ISFINITE(X)))
packfig PACKFIG Squeeze together rows and/or columns of the current figure.
tidefreq TIDEFREQ Frequencies of the eight major tidal components.
vlines VLINES Add vertical lines to a plot.
xlog XLOG Sets x-axis scale to logarithmic.
ylog YLOG Sets y-axis scale to log.
This function is called by:
jspectral jSpectral: Multitaper spectral analysis, and other time series tools
mspec MSPEC Multitaper power and cross spectra.