Description of use
Home > jlab > use.m
use
USE  Copies structure fields into named variables in workspace.
   USE STRUCT, where STRUCT is a structure, copies all fields of the form
   STRUCT.X into variables named X.
   This is useful for handling multiple datasets with the same variable
   names.  The structures can be then kept in memory and 'mapped' into
   variables as needed.
   See also MAKE, MATSAVE.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
use USE Copies structure fields into named variables in workspace.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
about_drifters DRIFTERS Global surface drifter dataset from the Global Drifter Program.
about_floats FLOATS Historical dataset of eddy-resolving subsurface floats.
about_jtopo JTOPO One-sixth degree global topography based on Smith and Sandwell.
anatrans ANATRANS Analytic part of signal.
cellchunk CELLCHUNK Converts cell array data into uniform length 'chunks'.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
divgeom DIVGEOM Geometric decomposition of eddy vorticity flux divergence.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
inregion INREGION Tests whether lat/lon points lie within a specified box.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
makefigs_topoplot
mspec MSPEC Multitaper power and cross spectra.
patchcontourf PATCHCONTOURF Generate filled contours using patches, with specified colors.
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
regionplot REGIONPLOT Plots a simple box indicating a latitude / longitude region.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
timeseries_boundary TIMESERIES_BOUNDARY Apply boundary conditions to data before transform.
topoplot TOPOPLOT Plot regional or global topography at one-sixth degree resolution.
trajchunk TRAJCHUNK Converts Lagrangian trajectories into chunks based on the Coriolis period.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.
trajwrap TRAJWRAP Wraps Lagrangian trajectories to fit within a periodic domain.
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
use USE Copies structure fields into named variables in workspace.
uv2latlon UV2LATLON Integrates horizontal velocity to give latitude and longitude.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.
wavetrans WAVETRANS Continuous wavelet transform.