Description of uvplot
Home > jlab > uvplot.m
uvplot
UVPLOT  Plots the real and imaginary parts of a signal on the same axis.
   UVPLOT(T,CV) plots the real and imaginary components of the
   complex-valued data CV=U+iV versus time T.  Here T is a column
   vector and CV is a matrix with LENGTH(T) rows.
   UVPLOT(T,CV,STY1,STY2) optionally plots the real components of CV,
   U, using style STY1, and the imaginary components V using STY2.
   STY1 and STY2 are strings following the format in LINESTYLE.
   UVPLOT(T,CV,STY) uses STY for the linestyles of both lines.
   UVPLOT(T,U,V,...), where U and V are real matrices, also works.
   [H1,H2]=UVPLOT(...) returns handles to the line plots of U and V.
   As an example,
        load bravo94
        cv=vfilt(bravo.rcm.cv(:,3),24);
        num=yf2num(bravo.rcm.yearf)-datenum(1994,1,1);
        uvplot(num,cv,'2b','r-.'),xlim([120 340])
   returns a color version of Fig.4b of Lilly and Rhines JPO 2001.
   Usage:  uvplot(t,cv);
           uvplot(t,cv,sty1,sty2);
           uvplot(t,cv,sty1,sty2,dy);
           uvplot(t,u,v,sty1,sty2,dy);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2012 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
This function is called by:
instmom INSTMOM Univariate and multivariate instantaneous moments.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
morlwave MORLWAVE Morlet wavelet.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.