Description of vcolon
Home > jlab > vcolon.m
vcolon
VCOLON  Condenses its arguments, like X(:).
   [Y1,Y2, ... YN]=VCOLON(X1,X2, ... XN) is equivalent to
      Y1=X1(:); Y2=X2(:); ... YN=XN(:);
   VCOLON(X1,X2,...XN) with no output arguments overwrites the
   original input variables.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000, 2004 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vcolon VCOLON Condenses its arguments, like X(:).
This function is called by:
cellmean CELLMEAN Mean value of each element a cell array or set of cell arrays.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellipseplot ELLIPSEPLOT Plot ellipses.
hodograph HODOGRAPH Generate hodograph plots (simple and fancy).
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
maternedge MATERNEDGE Long-time cutoff edge for the Matern impulse response function.
maternimp MATERNIMP Impulse response function for the Matern random process.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
provec PROVEC Generate progressive vector diagrams (simple and fancy).
ridgeinterp RIDGEINTERP Interpolate quantity values onto ridge locations.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
twodsort TWODSORT Distances from data points to nearby grid points.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
vcolon VCOLON Condenses its arguments, like X(:).