Description of vdiff
Home > jlab > vdiff.m
vdiff
VDIFF    Length-preserving first central difference.
   DX=VDIFF(X,DIM) differentiates X along dimension DIM using the first
   central difference; DX is the same size as X.
   [D1,D2,...,DN]=VDIFF(X1,X2,...,XN,DIM) for multiple input variables
   also works.
   VDIFF(X1,X2,...,DIM); with no output arguments overwrites the
   original input variables.
   DXDT=VDIFF(DT,...) optionally uses scalar timestep DT to approximate
   a time derivative, i.e. DXDT equals DX divided by DT.
   _____________________________________________________________________
   First and last points
   The first and last points must be treated differently, as the central
   difference is not defined there.  Three different methods can be used.
   VDIFF(...,STR) specifies which method to use.
        'endpoint'  uses the first forwards / first backwards difference
                    at the first and last point, respectively.
        'periodic'  treats the array as being periodic along dimension DIM,
                    so that the central difference is defined at endpoints.
        'nans'      fills in the first and last values with NANs.
   The default behavior is 'endpoint'.
   _____________________________________________________________________
   'vdiff --t' runs some tests.
   Usage:  x=vdiff(x,dim);
           x=vdiff(dt,x,dim);
           x=vdiff(dt,x,dim,'periodic');
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
iseven ISEVEN True for even integer values; false otherwise.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vdiff VDIFF Length-preserving first central difference.
vindex VINDEX Indexes an N-D array along a specified dimension.
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
This function is called by:
dawsonderiv DAWSONDERIV Derivatives of the Dawson function.
divgeom DIVGEOM Geometric decomposition of eddy vorticity flux divergence.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
elldiff ELLDIFF Differentiation of modulated elliptical signals.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellvel ELLVEL Average and instantaneous ellipse velocities.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
maternfun MATERNFUN Returns the Matern function.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morsexpand MORSEXPAND Generalized Morse wavelets via time-domain Taylor series.
periodize PERIODIZE Returns a doubly periodic version of an input array.
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
ridgechains RIDGECHAINS Forms ridge curves by connecting transform ridge points.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
slidetrans SLIDETRANS Sliding-window ('moving-window') Fourier transform.
spherecurl SPHERECURL Curl of a vector field on the surface of a sphere.
spherediv SPHEREDIV Divergence of a vector field on the surface of a sphere.
spheregrad SPHEREGRAD Gradient of a field on the surface of a sphere.
spherelap SPHERELAP Laplacian of a field on the surface of a sphere.
trajwrap TRAJWRAP Wraps Lagrangian trajectories to fit within a periodic domain.
vdiff VDIFF Length-preserving first central difference.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).