Description of vectmult
Home > jlab > vectmult.m
vectmult
VECTMULT  Matrix multiplication for arrays of vectors.
   [Y1,Y2,...,YM]=VECTMULT(A,X1,X2,...,XN) is equivalent to the usual
   multiplication of a matrix by a vector,
           Y = A * X
   where A is an M x N matrix, X is an N-vector, and Y is an M-vector.
   X1--XN and Y1--YM are the components of X and Y respectively.
   Often however one has arrays of vectors.  Here we group the N
   components of X into N arrays, X1,X2,...,XN, which can be of any size
   provided they are all the same size.
   VECTMULT then returns the components of the output vector Y as the M
   arrays Y1,Y2,...,YM.
   The matrix A may be a M x N matrix, or alternatively, it may be an
   array of size M x N x SIZE(XN).
   See also MATMULT.
   Usage: [y1,y2]=vectmult(a,x1,x2);
          [y1,y2,y3]=vectmult(a,x1,x2,y3);
   'vectmult --t' runs a test.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
jmat JMAT 2x2 rotation matrix through specified angle.
jmat3 JMAT3 3x3 rotation matrix through specified angle.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vectmult VECTMULT Matrix multiplication for arrays of vectors.
This function is called by:
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellsig ELLSIG Creates a modulated elliptical signal in two or three dimensions.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
vectmult VECTMULT Matrix multiplication for arrays of vectors.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.
wavetrans WAVETRANS Continuous wavelet transform.