Description of vempty
Home > jlab > vempty.m
vempty
VEMPTY   Initializes multiple variables to empty sets or empty cell arrays.
   [X1,X2, ... XN]=VEMPTY  is equivalent to
      X1=[]; X2=[]; .... XN=[];
   thus initializing all the output variables to empty sets.
   [X1,X2, ... XN]=VEMPTY('cell') instead initializes the output variables
   to empty cell arrays.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2013 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vempty VEMPTY Initializes multiple variables to empty sets or empty cell arrays.
This function is called by:
curveinterp CURVEINTERP Interpolate a field or its gradient onto a set of curves.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellipseplot ELLIPSEPLOT Plot ellipses.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
ridgechains RIDGECHAINS Forms ridge curves by connecting transform ridge points.
vempty VEMPTY Initializes multiple variables to empty sets or empty cell arrays.