Description of vindex
Home > jlab > vindex.m
vindex
VINDEX  Indexes an N-D array along a specified dimension.
   Y=VINDEX(X,INDEX,DIM) indexes the multidimensional array X along
   dimension DIM. This is equivalent to
            1 2       DIM     DIMS(X)
            | |        |         |
        Y=X(:,:, ... INDEX, ..., :);
   where the location of INDEX is specified by DIM.
   VINDEX is defined to return an empty array if INDEX is empty.
   Note that VINDEX does not index along singleton dimensions, thus
   when X is a column vector, VINDEX(X,INDEX,2) returns X.
   [Y1,Y2,...YN]=VINDEX(X1,X2,...XN,INDEX,DIM) also works.
   VINDEX(X1,X2,...XN,INDEX,DIM); with no output arguments overwrites
   the original input variables.
   VINDEX also supports logical indexing with INDEX a boolean array
   of the same size as the dimension being indexed.
   See also VINDEXINTO, SQUEEZE, DIMS, PERMUTE, SHIFTDIM.
   'vindex --t' runs a test.
   Usage:  y=vindex(x,index,dim);
           [y1,y2,y3]=vindex(x1,x2,x3,index,dim);
           vindex(x1,x2,x3,index,dim);
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2001--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vindex VINDEX Indexes an N-D array along a specified dimension.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
about_drifters DRIFTERS Global surface drifter dataset from the Global Drifter Program.
about_floats FLOATS Historical dataset of eddy-resolving subsurface floats.
anatrans ANATRANS Analytic part of signal.
cellchunk CELLCHUNK Converts cell array data into uniform length 'chunks'.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellipseplot ELLIPSEPLOT Plot ellipses.
ellparams ELLPARAMS Ellipse parameters of a modulated bivariate or trivariate oscillation.
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
matinv MATINV Fast inversion of arrays of small matrices.
matmult MATMULT Matrix multiplication for arrays of matrices.
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
ridgechains RIDGECHAINS Forms ridge curves by connecting transform ridge points.
ridgeinterp RIDGEINTERP Interpolate quantity values onto ridge locations.
spheredist SPHEREDIST Computes great circle distances on a sphere.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
stickvect STICKVECT Plots "stick vectors" for multicomponent velocity time series.
trajextract TRAJEXTRACT Extracts Lagrangian trajectory segments within given region.
twodmed TWODMED Median value of a function of two variables.
twodsort TWODSORT Distances from data points to nearby grid points.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
uv2latlon UV2LATLON Integrates horizontal velocity to give latitude and longitude.
vdiff VDIFF Length-preserving first central difference.
vindex VINDEX Indexes an N-D array along a specified dimension.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
vsqueeze VSQUEEZE Squeezes multiple input arguments simultaneously.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.
wavetrans WAVETRANS Continuous wavelet transform.