Description of vindexinto
Home > jlab > vindexinto.m
vindexinto
VINDEXINTO  Indexes into N-D array along a specified dimension.
   Y=VINDEXINTO(Y,X,INDEX,DIM) indexes the array X into the multi-
   dimensional array Y along dimension DIM. This is equivalent to
            1 2       DIM     DIMS(X)
            | |        |         |
          Y(:,:, ... INDEX, ..., :)=X;
   where the location of INDEX is specified by DIM.  X must have the
   exact same size as the block it replaces, or be a scalar.
   VINDEXINTO is defined leave Y unchanged if INDEX is empty, and to
   ignore NANs and INFs in INDEX.
   VINDEXINTO(Y,X,INDEX,0) with DIM=0 is equivalent to Y(INDEX)=X;
   [Y1,Y2,...YN]=VINDEXINTO(Y1,Y2,...YN,X1,X2,...XN,INDEX,DIM) also
   works.
   VINDEXINTO(Y1,Y2,...YN,X1,X2,...XN,INDEX,DIM); with no output
   arguments overwrites the original input variables ,Y2,...YN.
   See also VINDEX, SQUEEZE, DIMS, PERMUTE, SHIFTDIM
   'vindexinto --t' runs a test.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2005--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
iseven ISEVEN True for even integer values; false otherwise.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
vrep VREP Replicates an array along a specified dimension.
This function is called by:
anatrans ANATRANS Analytic part of signal.
ecconv ECCONV Converts between eccentricity measures.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
matinv MATINV Fast inversion of arrays of small matrices.
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
ridgechains RIDGECHAINS Forms ridge curves by connecting transform ridge points.
timeseries_boundary TIMESERIES_BOUNDARY Apply boundary conditions to data before transform.
vdiff VDIFF Length-preserving first central difference.
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
vshift VSHIFT Cycles the elements of an array along a specified dimension.