Description of vlines
Home > jlab > vlines.m
vlines
VLINES   Add vertical lines to a plot.
   VLINES(X,STYLE) puts vertical lines at locations X having style
   described by the string STYLE.  VLINES draws the lines to fit the
   current axis.
   The SYTLE strings follow the format specified in LINESTYLE.  Thus
   STYLE='2b--' draws blue dotted lines of width 2.
   VLINES(X) uses the default STYLE='g--', a green dashed line.
   H=VLINES(...) returns an array of handles H to the lines.
   See also HLINES, DLINES.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2008 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
ellvel ELLVEL Average and instantaneous ellipse velocities.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
morlwave MORLWAVE Morlet wavelet.
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
mspec MSPEC Multitaper power and cross spectra.
periodize PERIODIZE Returns a doubly periodic version of an input array.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
simplepdf SIMPLEPDF Gaussian, uniform, Cauchy, and exponential pdfs.
trajwrap TRAJWRAP Wraps Lagrangian trajectories to fit within a periodic domain.
twospecplot TWOSPECPLOT Plots a pair of rotary or Cartesian spectra.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).