Description of vmean
Home > jlab > vmean.m
vmean
VMEAN  Mean over finite elements along a specified dimension.
   Y=VMEAN(X,DIM) takes the mean of all finite elements of X along
   dimension DIM.
   [Y,NUM]=VMEAN(X,DIM) also outputs the number of good data points NUM,
   which has the same dimension as X.
   [Y1,Y2,...YN]=VMEAN(X1,X2,...XN,DIM) or also works, where all the XN
   are the same size.
   VMEAN(X1,X2,...XN,DIM);  with no output arguments overwrites the
   original input variables.
   __________________________________________________________________
   Weighted means
   VMEAN can also form a weighted mean.
   Y=VMEAN(X,DIM,W) forms the weighted mean of X using weights W, an array
   of the same size as X.
   In this case [Y,NUM]=VMEAN(X,DIM,W) returns total weight using in
   forming the mean at each point, rather than the number of data points.
   Thus VMEAN(X,DIM,W) is the same as VMEAN(X.*W,DIM)./VMEAN(W,DIM).
   [Y1,Y2,...YN]=VMEAN(X1,X2,...XN,DIM,W) also works.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2001--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
frac FRAC Fraction: FRAC(A,B)=A./B
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vmean VMEAN Mean over finite elements along a specified dimension.
vsum VSUM Sum over finite elements along a specified dimension.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
about_jtopo JTOPO One-sixth degree global topography based on Smith and Sandwell.
anatrans ANATRANS Analytic part of signal.
cellmean CELLMEAN Mean value of each element a cell array or set of cell arrays.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellrossby ELLROSSBY Ellipse Rossby number, for oceanographic applications.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
mspec MSPEC Multitaper power and cross spectra.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
sampletimes SAMPLETIMES Computes mean sampling intervals and their statistics.
trajchunk TRAJCHUNK Converts Lagrangian trajectories into chunks based on the Coriolis period.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
vmean VMEAN Mean over finite elements along a specified dimension.
vmoment VMOMENT Central moment over finite elements along a specfied dimension.