Description of vmedian
Home > jlab > vmedian.m
vmedian
VMEDIAN  Median over finite elements along a specified dimension.
   Y=VMEDIAN(X,DIM) takes the median of all finite elements of X along
   dimension DIM.
   [Y1,Y2,...YN]=VMEDIAN(X1,X2,...XN,DIM) also works.
   VMEDIAN(X1,X2,...XN,DIM); with no output arguments overwrites the
   original input variables.
   VMEDIAN, like MATLAB's MEDIAN, defines the median over an even
   number of values to be the average of the two middle elements.
   VMEDIAN uses a fast algorithm which can be several times faster
   than MEDIAN, but unlike MEDIAN, excludes INFs and NANs.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
isodd ISODD True for odd integer values; false otherwise.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vmedian VMEDIAN Median over finite elements along a specified dimension.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
This function is called by:
about_floats FLOATS Historical dataset of eddy-resolving subsurface floats.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
sampletimes SAMPLETIMES Computes mean sampling intervals and their statistics.
vfilt VFILT Filtering along rows without change in length.
vmedian VMEDIAN Median over finite elements along a specified dimension.