Description of vrep
Home > jlab > vrep.m
vrep
VREP  Replicates an array along a specified dimension.
   Y=VREP(X,N,DIM) replicates the array by N times along dimension
   dimension DIM.  For instance:
        VREP([1:4]',3,2)=[ [1:4]' [1:4]' [1:4]' ]
   This is often useful in array algebra.
   IF N and DIM are arrays of length M, then X is replicated along each of
   the M different dimensions: N(1) times along dimensions DIM(1), etc.
   [Y1,Y2,...,YP]=VREP(X1,X2,...,XP,N,DIM) also works.
   See also VINDEX, DIM.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2001--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vrep VREP Replicates an array along a specified dimension.
This function is called by:
anatrans ANATRANS Analytic part of signal.
blurspec BLURSPEC Returns the blurred and aliased spectrum given the autocovariance.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellipseplot ELLIPSEPLOT Plot ellipses.
inellipse INELLIPSE Locates points on the interior of ellipses.
instmom INSTMOM Univariate and multivariate instantaneous moments.
isridgepoint ISRIDGEPOINT Finds wavelet ridge points using one of several criterion.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.
maternchol MATERNCHOL Cholesky decomposition of the Matern covariance matrix.
maternimp MATERNIMP Impulse response function for the Matern random process.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
maternspec MATERNSPEC Fourier spectrum of the Matern random process.
morsea MORSEA Returns the generalized Morse wavelet amplitude "a".
morseproj MORSEPROJ Projection coefficient for two generalized Morse wavelets.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
mspec MSPEC Multitaper power and cross spectra.
msvd MSVD Singular value decomposition for polarization analysis.
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
ridgechains RIDGECHAINS Forms ridge curves by connecting transform ridge points.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
slidetrans SLIDETRANS Sliding-window ('moving-window') Fourier transform.
spherecurl SPHERECURL Curl of a vector field on the surface of a sphere.
spherediv SPHEREDIV Divergence of a vector field on the surface of a sphere.
spheregrad SPHEREGRAD Gradient of a field on the surface of a sphere.
spherelap SPHERELAP Laplacian of a field on the surface of a sphere.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
twodsort TWODSORT Distances from data points to nearby grid points.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
vfilt VFILT Filtering along rows without change in length.
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
vmoment VMOMENT Central moment over finite elements along a specfied dimension.
vrep VREP Replicates an array along a specified dimension.
wavetrans WAVETRANS Continuous wavelet transform.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).