Description of vshift
Home > jlab > vshift.m
vshift
 VSHIFT  Cycles the elements of an array along a specified dimension.
   Y=VSHIFT(X,N,DIM) cycles the elements of X N places along dimension DIM.
   Example: x=[1 2 3 4 5];
            vshift(x,+1,2)=[2 3 4 5 1]
            vshift(x,-1,2)=[5 1 2 3 4]
   Note shifting by N and then by -N recovers the original array.
   [Y1,Y2,...YN]=VSHIFT(X1,X2,...XN,N,DIM) also works.
   VSHIFT(X1,X2,...XN,N,DIM); with no arguments overwrite the original
   input variables.
   Note that VSHIFT is similar to Matlab's CIRCSHIFT, but has the opposite
   convection for positive and negative shifts.
   ------------------------------------------------------------------
   Y=VSHIFT(X,N,DIM,INDEX,DIM2) applies this shift selectively, only to
   that subset of X obtained by indexing X with INDEX along DIM2, i.e.
            1 2      DIM2     DIMS(X)
            | |        |         |
          X(:,:, ... INDEX, ..., :)
   is cycled N places along dimension DIM, but the remainder of X is not.
   DIM and DIM2 cannot be the same.  The above extensions to multiple
   output varibles work in this case as well.
   ------------------------------------------------------------------
   See also: VINDEX, CIRCSHIFT.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2001--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vindex VINDEX Indexes an N-D array along a specified dimension.
vindexinto VINDEXINTO Indexes into N-D array along a specified dimension.
vshift VSHIFT Cycles the elements of an array along a specified dimension.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
bindata BINDATA Rapidly sort data into adjacent bins.
commentlines COMMENTLINES Returns the comment lines from m-files.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
divgeom DIVGEOM Geometric decomposition of eddy vorticity flux divergence.
fixlabels FIXLABELS Specify precision of axes labels.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
latlon2uv LATLON2UV Converts latitude and longitude to horizontal velocity.
lonshift LONSHIFT Shifts longitude origin for plotting purposes.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
orbitbreaks ORBITBREAKS Separate orbit into passes based on turning points.
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
trajwrap TRAJWRAP Wraps Lagrangian trajectories to fit within a periodic domain.
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
vdiff VDIFF Length-preserving first central difference.
vfilt VFILT Filtering along rows without change in length.
vshift VSHIFT Cycles the elements of an array along a specified dimension.