Description of vsize
Home > jlab > vsize.m
vsize
VSIZE  Returns the sizes of multiple arguments.
   VSIZE(X1,X2,... XN) returns the sizes of the input variables.
   These are organized in a matrix of size M x N where M is the number
   of input variables and M is the maximum number of dimensions.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2001--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vsize VSIZE Returns the sizes of multiple arguments.
This function is called by:
inellipse INELLIPSE Locates points on the interior of ellipses.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
vsize VSIZE Returns the sizes of multiple arguments.