Description of vsqueeze
Home > jlab > vsqueeze.m
vsqueeze
VSQUEEZE   Squeezes multiple input arguments simultaneously.
   [Y1,Y2, ... YN]=VSQUEEZE(X1,X2, ... XN) is equivalent to
      Y1=SQUEEZE(X1); Y2=SQUEEZE(X2); ... YN=SQUEEZE(XN);
   VSQUEEZE(X1,X2,...XN) with no output arguments overwrites the
   original input variables.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vindex VINDEX Indexes an N-D array along a specified dimension.
vsqueeze VSQUEEZE Squeezes multiple input arguments simultaneously.
This function is called by:
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
vsqueeze VSQUEEZE Squeezes multiple input arguments simultaneously.