Description of vstd
Home > jlab > vstd.m
vstd
VSTD Standard deviation over finite elements along a specfied dimension.
   Y=VSTD(X,DIM) takes the standard deviation of all finite elements of X
   along dimension DIM.
   [Y,NUM]=VSTD(X,DIM) also outputs the number of good data points NUM,
   which is the same size as X.
   VSTD uses the "1/N" normalization, where N is the number of data points,
   rather than the "1/(N-1)" normalization.
   [Y1,Y2,...YN]=VSTD(X1,X2,...XN,DIM) also works.
   VSTD(X1,X2,...XN,DIM);  with no arguments overwrites the original
   input variables.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2001--2012 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vmoment VMOMENT Central moment over finite elements along a specfied dimension.
vstd VSTD Standard deviation over finite elements along a specfied dimension.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
mspec MSPEC Multitaper power and cross spectra.
periodize PERIODIZE Returns a doubly periodic version of an input array.
sampletimes SAMPLETIMES Computes mean sampling intervals and their statistics.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
vstd VSTD Standard deviation over finite elements along a specfied dimension.