Description of vsum
Home > jlab > vsum.m
vsum
VSUM  Sum over finite elements along a specified dimension.
   Y=VSUM(X,DIM) takes the sum of all finite elements of X along
   dimension DIM.
   [Y,NUM]=VSUM(X,DIM) also outputs the number of good data points NUM,
   which has the same dimension as Y.
   [Y1,Y2,...YN]=VSUM(X1,X2,...XN,DIM) also works.
   VSUM(X1,X2,...XN,DIM);  with no output arguments overwrites the
   original input variables.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2001--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vsum VSUM Sum over finite elements along a specified dimension.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
anatrans ANATRANS Analytic part of signal.
blurspec BLURSPEC Returns the blurred and aliased spectrum given the autocovariance.
curveinterp CURVEINTERP Interpolate a field or its gradient onto a set of curves.
dawson DAWSON The Dawson function. [By P.J. Acklam]
dawsonderiv DAWSONDERIV Derivatives of the Dawson function.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jlab_runtests JLAB_RUNTESTS Runs a test suite for JLAB package.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
morsea MORSEA Returns the generalized Morse wavelet amplitude "a".
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
morseproj MORSEPROJ Projection coefficient for two generalized Morse wavelets.
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
morsexpand MORSEXPAND Generalized Morse wavelets via time-domain Taylor series.
mspec MSPEC Multitaper power and cross spectra.
msvd MSVD Singular value decomposition for polarization analysis.
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
ridgemap RIDGEMAP Maps ridge quantities back onto the time series.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
simplepdf SIMPLEPDF Gaussian, uniform, Cauchy, and exponential pdfs.
sleptap SLEPTAP Calculate Slepian tapers.
slidetrans SLIDETRANS Sliding-window ('moving-window') Fourier transform.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
vmean VMEAN Mean over finite elements along a specified dimension.
vsum VSUM Sum over finite elements along a specified dimension.