Description of vswap
Home > jlab > vswap.m
vswap
VSWAP  VSWAP(X,A,B) replaces A with B in numeric array X.
   VSWAP(X,A,B) replaces A with B in numeric array X.  A and B may be
   numbers, NAN, +/- INF, NAN+SQRT(-1)*NAN, or INF+SQRT(-1)*INF.
   [Y1,Y2,...YN]=VSWAP(X1,X2,...XN,A,B) also works.
   VSWAP(X1,X2,...XN,A,B); with no output arguments overwrites the
   original input variables.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2001--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
allall ALLALL(X)=ALL(X(:))
aresame ARESAME Test whether two N-D arrays are the same.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
This function is called by:
about_drifters DRIFTERS Global surface drifter dataset from the Global Drifter Program.
bindata BINDATA Rapidly sort data into adjacent bins.
cell2col CELL2COL Converts cell arrays of column vectors into 'column-appended' data.
col2mat COL2MAT Expands 'column-appended' data into a matrix.
elldiff ELLDIFF Differentiation of modulated elliptical signals.
ellipseplot ELLIPSEPLOT Plot ellipses.
ellvel ELLVEL Average and instantaneous ellipse velocities.
hodograph HODOGRAPH Generate hodograph plots (simple and fancy).
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jpcolor JPCOLOR Modified version of PCOLOR appropriate for cell-centered grids.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
mspec MSPEC Multitaper power and cross spectra.
orbitbreaks ORBITBREAKS Separate orbit into passes based on turning points.
pdfprops PDFPROPS Mean and variance associated with a probability distribution.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
provec PROVEC Generate progressive vector diagrams (simple and fancy).
ridgelen RIDGELEN Wavelet ridge length expressed as number of full cycles.
timeseries_boundary TIMESERIES_BOUNDARY Apply boundary conditions to data before transform.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
vmean VMEAN Mean over finite elements along a specified dimension.
vmedian VMEDIAN Median over finite elements along a specified dimension.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.