Description of vtranspose
Home > jlab > vtranspose.m
vtranspose
VTRANSPOSE  Transpose multiple input arguments simultaneously.
   [Y1,Y2, ... YN]=VTRANSPOSE(X1,X2, ... XN) is equivalent to
       Y1=CONJ(X1'); Y2=CONJ(X2'); ... YN=CONJ(XN');
   for matrix arguments X1,X2, ... XN.  This is the matrix transpose.
   Recall X1' is the conjugate transpose of X1 in Matlab's notation.
   VTRANSPOSE(X1,X2,...XN);  with no output arguments overwrites the
   original input variables.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
to_overwrite TO_OVERWRITE Returns a string to overwrite original arguments.
This function is called by:
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.