Description of vzeros
Home > jlab > vzeros.m
vzeros
VZEROS   Initializes multiple variables to arrays of zeros or nans.
   [X1,X2, ... XN]=VZEROS(M,N)  is equivalent to
      X1=ZEROS(M,N); X2=ZEROS(M,N); .... XN=ZEROS(M,N);
   thus initializing all the output variables to arrays of zeros.
   [X1,X2, ... XN]=VZEROS(M,N,NAN) initializes to NANs instead.
   [X1,X2, ... XN]=VZEROS(M,N,INF) initializes to INFs instead.
   [X1,X2, ... XN]=VZEROS(M,N,K,... P) similiarly initializes the Xi
   to N-D arrays of zeros having size M x N x K x ... P.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information (C)
   2004--2010 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
reporttest REPORTTEST Reports the result of an m-file function auto-test.
vswap VSWAP VSWAP(X,A,B) replaces A with B in numeric array X.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
about_drifters DRIFTERS Global surface drifter dataset from the Global Drifter Program.
blurspec BLURSPEC Returns the blurred and aliased spectrum given the autocovariance.
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
divgeom DIVGEOM Geometric decomposition of eddy vorticity flux divergence.
dlines DLINES Add diagonal lines to a plot.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jvarfun jVarfun: Perform common operations on multiple variables simultaneously.
maternchol MATERNCHOL Cholesky decomposition of the Matern covariance matrix.
maternoise MATERNOISE Generates realizations of the Matern random process. [with A. Sykulski]
morsederiv MORSEDERIV Frequency-domain derivatives of generalized Morse wavelets.
morsemom MORSEMOM Frequency-domain moments of generalized Morse wavelets.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
ridgechains RIDGECHAINS Forms ridge curves by connecting transform ridge points.
sampletimes SAMPLETIMES Computes mean sampling intervals and their statistics.
spheredist SPHEREDIST Computes great circle distances on a sphere.
spheresort SPHERESORT Sorted great circle distances to nearby points on the earth.
twodmed TWODMED Median value of a function of two variables.
twodsort TWODSORT Distances from data points to nearby grid points.
twodstats TWODSTATS Mean, variance, and covariance of functions of two variables.
uv2latlon UV2LATLON Integrates horizontal velocity to give latitude and longitude.
vmedian VMEDIAN Median over finite elements along a specified dimension.
vzeros VZEROS Initializes multiple variables to arrays of zeros or nans.