Description of wavespecplot
Home > jlab > wavespecplot.m
wavespecplot
WAVESPECPLOT  Plot of wavelet spectra together with time series.
   WAVESPECPLOT(T,X,P,W) where T is the time, X is a time series, and W is
   the wavelet transform at periods P, makes a two-component plot.  The
   upper subplot has the time series X plotted against its time axis T.
   The lower subplot has the transform W, or its modulus ABS(W) if W is
   complex-valued, plotted versus the time axis T and the periods P.
   WAVESPECPLOT(T,X,P,W,R) optionally plots ABS(W).^R instead of W.
   WAVESPECPLOT(T,X,P,W,R,CI) makes a filled contour plot with contour
   intervals CI.  If CI is not input, then the spectrum is plotted using
   PCOLOR, which is faster to render but slow to print. For making final
   figures, it is better to use the contouring option.
   WAVESPECPLOT(T,X,P,W1,W2,...WN,...) makes an N+1 component plot, with
   W1 in the second subplot, W2 in the third, etc.
   After plotting, all subplots are packed together using PACKROWS.
   H=WAVESPECPLOT(...) returns the handles to the subplots.
   [H,HL]=WAVESPECPLOT(...) also returns the handles to the lines plotted
   in the first panel.
   If X is complex-valued, both the real and imaginary parts are plotted
   in the uppermost subplot.
   Usage: h=wavespecplot(t,x,p,w);
          h=wavespecplot(t,x,p,w,r);
          [h,hl]=wavespecplot(t,x,p,w,r,ci);
   'wavespecplot --f' generates a sample figure.
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
flipy FLIPY Flips the direction of the y-axis
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
morsespace MORSESPACE Logarithmically-spaced frequencies for generalized Morse wavelets.
oprod OPROD Outer product: OPROD(X,Y)=X*CONJ(Y')
packfig PACKFIG Squeeze together rows and/or columns of the current figure.
tmat TMAT 2x2 complex grouping matrix. TMAT = [1 i; 1 -i] / SQRT(2)
use USE Copies structure fields into named variables in workspace.
uvplot UVPLOT Plots the real and imaginary parts of a signal on the same axis.
vectmult VECTMULT Matrix multiplication for arrays of vectors.
vindex VINDEX Indexes an N-D array along a specified dimension.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.
wavetrans WAVETRANS Continuous wavelet transform.
ylog YLOG Sets y-axis scale to log.
This function is called by:
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jwavelet jWavelet: Continuous wavelet analysis using generalized Morse wavelets
msvd MSVD Singular value decomposition for polarization analysis.
ridgewalk RIDGEWALK Extract wavelet transform ridges, including bias estimates.
slidetrans SLIDETRANS Sliding-window ('moving-window') Fourier transform.
wavespecplot WAVESPECPLOT Plot of wavelet spectra together with time series.