Description of whichdir
Home > jlab > whichdir.m
whichdir
   WHICHDIR  Returns directory name containing file in search path.
   WHICHDIR NAME returns the directory containing a file called NAME,
   i.e. the full path of the file excluding NAME and the trailing '/'.
   If more than one directory contains a file called NAME, then
   WHICHDIR returns a cell array of directories names.
   If NAME does not include an extension, then it is interpreted as
   the name of an m-file, i.e. having extension '.m' .
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2006--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
about_alongtrack ALONGTRACK Sea surface height anomalies from the Beckley merged dataset.
findfiles FINDFILES Returns all files in a directory with a specified extension.
jcommon jCommon: Useful general-purpose functions, common to other JLAB modules
jhelp JHELP Opens linked JLAB help files in Matlab's internal web browser.
jlab_runtests JLAB_RUNTESTS Runs a test suite for JLAB package.
makefigs_topoplot
mspec MSPEC Multitaper power and cross spectra.
readtopo READTOPO Read one-minute topography data from Smith and Sandwell.
twodhist TWODHIST Two-dimensional histogram.
twodmed TWODMED Median value of a function of two variables.