Description of wigdist
Home > jlab > wigdist.m
wigdist
 WIGDIST  Wigner distribtion (alias-free algorithm).
   D=WIGDIST(X,NMIN,NMAX) returns the Wigner distrution of column vector X
   at Fourier frequencies [NMIN/N:1/N:NMAX/N] where N equals LENGTH(X).
   The output D is a matrix of dimension LENGTH(X) x [NMAX-NMIN+1].
   Note that negative frequencies are permitted.
   D=WIGDIST(X,NMIN,NMAX,M) first zero-pads the data to length M, where
   M>LENGTH(X). The Wigner distrution is then computed at frequencies
   [NMIN/M:1/M:NMAX/M].  This is to give higher frequency resolution.
   WIGDIST uses the alias-free Wigner distribution algorithm given in
   Matllat (1999), second edition, section 4.5.4.
   The Wigner distribution is computed using a fast algoorithm that is an
   order of magnitude faster than the obvious algorithm.  The difference
   between the two is at the level of numerical noise.  To force use of
   the slow algorithm, use WIGDIST(X,NMIN,NMAX,M,1).
   'wigdist --t' runs a test using the two different algorithms.
   'wigdist --f' generates some sample figures.
   Usage:  [d,f]=wigdist(x,nmin,nmax);
           [d,f]=wigdist(x,nmin,nmax,m);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2004--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
aresame ARESAME Test whether two N-D arrays are the same.
doublen DOUBLEN Interpolates a time series to double its length.
fixlabels FIXLABELS Specify precision of axes labels.
flipmap FLIPMAP Flips the current colormap upside-down.
frac FRAC Fraction: FRAC(A,B)=A./B
hlines HLINES Add horizontal lines to a plot.
isodd ISODD True for odd integer values; false otherwise.
letterlabels LETTERLABELS For automatically putting letter labels on subplots.
linestyle LINESTYLE Rapidly set color, style, and width properties of lines.
maxmax MAXMAX(X)=MAX(X(ISFINITE(X)))
morlwave MORLWAVE Morlet wavelet.
morsewave MORSEWAVE Generalized Morse wavelets of Olhede and Walden (2002).
packfig PACKFIG Squeeze together rows and/or columns of the current figure.
reporttest REPORTTEST Reports the result of an m-file function auto-test.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
vdiff VDIFF Length-preserving first central difference.
vlines VLINES Add vertical lines to a plot.
vrep VREP Replicates an array along a specified dimension.
wigdist WIGDIST Wigner distribtion (alias-free algorithm).
xtick XTICK Sets locations of x-axis tick marks.
ytick YTICK Sets locations of y-axis tick marks.
This function is called by:
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jspectral jSpectral: Multitaper spectral analysis, and other time series tools
wigdist WIGDIST Wigner distribtion (alias-free algorithm).