Description of xoffset
Home > jlab > xoffset.m
xoffset
XOFFSET  Offsets lines in the x-direction after plotting.
   XOFFSET allows data to be manipulated after it has been plotted, by
   operating on the data stored in the figure itself.  This may be used
   only with 2-D line plots (not symbol plots, contour plots, etc.).
   XOFFSET offsets all lines in the current axes a specified amount.
   XOFFSET(N) or XOFFSET N, where N is a *real* number, offsets each
   column of the X-data by an amount N from the previous column.  N must
   be a number, not a variable whose value is a number.
   XOFFSET(N) or XOFFSET N, where N is an *imaginary* number, offsets
   each column of the X-data by an amount imag(N)*DX from the previous
   column, where DX is the X-axis length of the original (unoffset) plot.
   XOFFSET(M,N) or XOFFSET M N, applies the same offsets to each of M
   groups of lines. For example, for complex-valued data Z use UVPLOT(Z)
   followed by XOFFSET 2 N.
   XOFFSET with no arguments returns the data to its original (unoffset)
   orientation [as do XOFFSET(0) and XOFFSET(0i)].
   XOFFSET also allow multiple axes to be manipulated simultaneously.
   XOFFSET LOCK and XOFFSET UNLOCK lock and unlock all Y-data in the
   current figure. When LOCK is on, calls to XOFFSET are applied to each
   subplot individually.
   See also YOFFSET, LINESTYLE.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
axeshandles AXESHANDLES Returns handles to all axes children.
linehandles LINEHANDLES Finds all line and patch handles from a given set of axes.
This function is called by:
jgraph jGraph: Plotting tools and refinements for making high-quality figures