Description of xtick
Home > jlab > xtick.m
xtick
XTICK  Sets locations of x-axis tick marks.
   XTICK(DX) or XTICK DX where DX is a number uses DX as the interval
   between successive x-tick marks, with the endpoints being the axes
   limits, and applies this to the current axis.
   XTICK(X) where X is an array sets the 'xtick' property of the current
   axis to X.
   XTICK with no input arguments attempts to make an educated guess for
   setting 'nice' tickmark locations, usually with good results.
   XTICK(H) or XTICK(H,X) or XTICK(H,DX) applies the change to axes H.
   See also YTICK, ZTICK.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2002--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
closedcurves CLOSEDCURVES Locate and interpolate closed curves in a possibly periodic domain.
curvemoments CURVEMOMENTS Centroid, area, and many other moments of a closed curve.
ecconv ECCONV Converts between eccentricity measures.
ellband ELLBAND Bandwidth of modulated elliptical signals in two or three dimensions.
ellvel ELLVEL Average and instantaneous ellipse velocities.
fixlabels FIXLABELS Specify precision of axes labels.
instmom INSTMOM Univariate and multivariate instantaneous moments.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
morsebox MORSEBOX Heisenberg time-frequency box for generalized Morse wavelets.
morsefreq MORSEFREQ Frequency measures for generalized Morse wavelets. [with F. Rekibi]
mspec MSPEC Multitaper power and cross spectra.
periodize PERIODIZE Returns a doubly periodic version of an input array.
polysmooth POLYSMOOTH Smoothing scattered 2D data with local polynomial fitting.
psi2fields PSI2FIELDS Velocity and other fields from the streamfunction. [with P.E. Isachsen]
wigdist WIGDIST Wigner distribtion (alias-free algorithm).