Description of xy2latlon
Home > jlab > xy2latlon.m
xy2latlon
 XY2LATLON  Converts local Cartesian coordinates into latitude and longitude.
   [LAT,LON]=XY2LATLON(X,Y,LATO,LONO) converts (X,Y) position with units
   of kilometers, specifying a location in a plane tangent to the earth
   at the point (LATO,LONO), into latitude and longitude locations.
   LONO may each either be specified on the interval [-180, 180] or on the
   interval [0, 360].  Output longitudes LON are defined to be within the
   interval [-180, 180].
   LAT and LON may be computed with either the full spherical geometry,
   the default, or using a small angle approximation.  To specify the
   small angle approximation use XY2LATLON(...,'small').
   LAT and LON are defined to be NAN for points with SQRT(X^2+Y^2)
   exceeding the radius of the earth.
   XY2LATLON(CX,LATO,LONO) with three input arguments, where CX is the
   complex-valued displacement CX=X+SQRT(-1)*Y, also works
   The radius of the earth is given by the function RADEARTH.
   ___________________________________________________________________
   Cell array input / output
   XY2LATLON returns cell array output given cell array input.
   That is, if the input arguments are all cell arrays of length K,
   containing K different numerical arrays, then the output will also be
   cell arrays of length K.
   This also works if X and Y, or alternatively CX, are cell arrays but
   LATO and LONO are scalars.
   ___________________________________________________________________
   XY2LATLON is inverted by LATLON2XY.
   See also LATLON2XY, LATLON2UV.
   Usage:  [lat,lon]=xy2latlon(x,y,lato,lono);
           [lat,lon]=xy2latlon(cx,lato,lono);
   _________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2005--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
cellimag CELLIMAG Imaginary part of each element in a cell array.
cellreal CELLREAL Real part of each element in a cell array.
frac FRAC Fraction: FRAC(A,B)=A./B
jdeg2rad JDEG2RAD Converts degrees to radians.
jrad2deg JRAD2DEG Converts radians to degrees.
radearth RADEARTH The radius of the earth in kilometers.
rot ROT Complex-valued rotation: ROT(X)=EXP(SQRT(-1)*X)
xyz2latlon XYZ2LATLON Converts 3D Cartesian coordinates into latitude and longitude.
This function is called by:
ellipseplot ELLIPSEPLOT Plot ellipses.
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.
jsphere jSphere: Tools for latitude, longitude, and spherical geometry
latlon2xy LATLON2XY Converts latitude and longitude into local Cartesian coordinates.