Description of yoffset
Home > jlab > yoffset.m
yoffset
YOFFSET  Offsets lines in the y-direction after plotting.
   YOFFSET allows data to be manipulated after it has been plotted, by
   operating on the data stored in the figure itself.  This may be used
   only with 2-D line plots (not symbol plots, contour plots, etc.).
   YOFFSET offsets all lines in the current axes a specified amount.
   YOFFSET(N) or YOFFSET N, where N is a *real* number, offsets each
   column of the Y-data by an amount N from the previous column.  N must
   be a number, not a variable whose value is a number.
   YOFFSET(N) or YOFFSET N, where N is an *imaginary* number, offsets
   each column of the Y-data by an amount imag(N)*DY from the previous
   column, where DY is the Y-axis length of the original (unoffset) plot.
   YOFFSET(M,N) or YOFFSET M N, applies the same offsets to each of M
   groups of lines. For example, for complex-valued data Z use UVPLOT(Z)
   followed by YOFFSET 2 N.
   YOFFSET with no arguments returns the data to its original (unoffset)
   orientation [as do YOFFSET(0) and YOFFSET(0i)].
   YOFFSET also allow multiple axes to be manipulated simultaneously.
   YOFFSET LOCK and YOFFSET UNLOCK lock and unlock all Y-data in the
   current figure. When LOCK is on, calls to YOFFSET are applied to each
   subplot individually.
   See also YOFFSET, LINESTYLE.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2000--2015 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
axeshandles AXESHANDLES Returns handles to all axes children.
linehandles LINEHANDLES Finds all line and patch handles from a given set of axes.
This function is called by:
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.