Description of ztick
Home > jlab > ztick.m
ztick
ZTICK  Sets locations of z-axis tick marks.
   ZTICK(DZ) or ZTICK DX where DX is a number uses DZ as the interval
   between successive z-tick marks, with the endpoints being the axes
   limits, and applies this to the current axis.
   ZTICK(Z) where Z is an array sets the 'ztick' property of the current
   axis to Z.
   ZTICK with no input arguments attempts to make an educated guess for
   setting 'nice' tickmark locations, usually with good results.
   ZTICK(H) or ZTICK(H,Z) or ZTICK(H,DZ) applies the change to axes H.
   See also XTICK, YTICK.
   __________________________________________________________________
   This is part of JLAB --- type 'help jlab' for more information
   (C) 2008--2014 J.M. Lilly --- type 'help jlab_license' for details
This function calls:
This function is called by:
fixlabels FIXLABELS Specify precision of axes labels.
jgraph jGraph: Plotting tools and refinements for making high-quality figures
jlab_makefigs JLAB_MAKEFIGS Makes figures for papers by J.M. Lilly.